import type { Sector } from "./types";

export interface RawStock { sym: string; name: string; sec: Sector }

export const INDIAN_STOCKS: RawStock[] = [
  { sym: "ANANDRATHI", name: "Anand Rathi Wealth Ltd", sec: "Finance" },
  { sym: "SJVN", name: "SJVN Ltd", sec: "Utilities" },
  { sym: "NHPC", name: "NHPC Ltd", sec: "Utilities" },
  { sym: "TCS", name: "Tata Consultancy Services", sec: "Technology" },
  { sym: "INFY", name: "Infosys Ltd", sec: "Technology" },
  { sym: "RELIANCE", name: "Reliance Industries", sec: "Energy" },
  { sym: "HDFCBANK", name: "HDFC Bank Ltd", sec: "Finance" },
  { sym: "ICICIBANK", name: "ICICI Bank Ltd", sec: "Finance" },
  { sym: "SBIN", name: "State Bank of India", sec: "Finance" },
  { sym: "BHARTIARTL", name: "Bharti Airtel Ltd", sec: "Communication" },
  { sym: "ITC", name: "ITC Ltd", sec: "Consumer" },
  { sym: "KOTAKBANK", name: "Kotak Mahindra Bank", sec: "Finance" },
  { sym: "LT", name: "Larsen & Toubro Ltd", sec: "Industrial" },
  { sym: "AXISBANK", name: "Axis Bank Ltd", sec: "Finance" },
  { sym: "HCLTECH", name: "HCL Technologies", sec: "Technology" },
  { sym: "WIPRO", name: "Wipro Ltd", sec: "Technology" },
  { sym: "MARUTI", name: "Maruti Suzuki India", sec: "Automotive" },
  { sym: "ASIANPAINT", name: "Asian Paints Ltd", sec: "Materials" },
  { sym: "SUNPHARMA", name: "Sun Pharmaceutical", sec: "Pharma" },
  { sym: "TITAN", name: "Titan Company Ltd", sec: "Consumer" },
  { sym: "ULTRACEMCO", name: "UltraTech Cement", sec: "Construction" },
  { sym: "TATAMOTORS", name: "Tata Motors Ltd", sec: "Automotive" },
  { sym: "TATASTEEL", name: "Tata Steel Ltd", sec: "Steel" },
  { sym: "BAJFINANCE", name: "Bajaj Finance Ltd", sec: "Finance" },
  { sym: "BAJAJFINSV", name: "Bajaj Finserv Ltd", sec: "Finance" },
  { sym: "HINDUNILVR", name: "Hindustan Unilever", sec: "Consumer" },
  { sym: "NESTLEIND", name: "Nestle India Ltd", sec: "Food" },
  { sym: "POWERGRID", name: "Power Grid Corp", sec: "Utilities" },
  { sym: "NTPC", name: "NTPC Ltd", sec: "Utilities" },
  { sym: "ONGC", name: "Oil & Natural Gas Corp", sec: "Energy" },
  { sym: "COALINDIA", name: "Coal India Ltd", sec: "Mining" },
  { sym: "IOC", name: "Indian Oil Corp", sec: "Energy" },
  { sym: "GAIL", name: "GAIL India Ltd", sec: "Energy" },
  { sym: "M&M", name: "Mahindra & Mahindra", sec: "Automotive" },
  { sym: "TECHM", name: "Tech Mahindra Ltd", sec: "Technology" },
  { sym: "DIVISLAB", name: "Divis Laboratories", sec: "Pharma" },
  { sym: "GRASIM", name: "Grasim Industries", sec: "Materials" },
  { sym: "CIPLA", name: "Cipla Ltd", sec: "Pharma" },
  { sym: "DRREDDY", name: "Dr Reddys Laboratories", sec: "Pharma" },
  { sym: "EICHERMOT", name: "Eicher Motors Ltd", sec: "Automotive" },
  { sym: "ADANIENT", name: "Adani Enterprises", sec: "Industrial" },
  { sym: "ADANIPORTS", name: "Adani Ports & SEZ", sec: "Logistics" },
  { sym: "JSWSTEEL", name: "JSW Steel Ltd", sec: "Steel" },
  { sym: "HDFCLIFE", name: "HDFC Life Insurance", sec: "Finance" },
  { sym: "SBILIFE", name: "SBI Life Insurance", sec: "Finance" },
  { sym: "BRITANNIA", name: "Britannia Industries", sec: "Food" },
  { sym: "HEROMOTOCO", name: "Hero MotoCorp Ltd", sec: "Automotive" },
  { sym: "BAJAJ-AUTO", name: "Bajaj Auto Ltd", sec: "Automotive" },
  { sym: "TVS", name: "TVS Motor Company", sec: "Automotive" },
  { sym: "INDUSINDBK", name: "IndusInd Bank Ltd", sec: "Finance" },
  { sym: "BPCL", name: "Bharat Petroleum Corp", sec: "Energy" },
  { sym: "SHRIRAMFIN", name: "Shriram Finance Ltd", sec: "Finance" },
  { sym: "ZOMATO", name: "Zomato Ltd", sec: "ECommerce" },
  { sym: "DMART", name: "Avenue Supermarts Ltd", sec: "Retail" },
  { sym: "PIDILITIND", name: "Pidilite Industries", sec: "Chemicals" },
  { sym: "DLF", name: "DLF Ltd", sec: "RealEstate" },
  { sym: "GODREJCP", name: "Godrej Consumer Products", sec: "Consumer" },
  { sym: "MARICO", name: "Marico Ltd", sec: "Consumer" },
  { sym: "DABUR", name: "Dabur India Ltd", sec: "Consumer" },
  { sym: "COLPAL", name: "Colgate Palmolive India", sec: "Consumer" },
  { sym: "HAVELLS", name: "Havells India Ltd", sec: "Industrial" },
  { sym: "AMBUJACEM", name: "Ambuja Cements Ltd", sec: "Construction" },
  { sym: "ACC", name: "ACC Ltd", sec: "Construction" },
  { sym: "SHREECEM", name: "Shree Cement Ltd", sec: "Construction" },
  { sym: "BANDHANBNK", name: "Bandhan Bank Ltd", sec: "Finance" },
  { sym: "FEDERALBNK", name: "Federal Bank Ltd", sec: "Finance" },
  { sym: "IDFCFIRSTB", name: "IDFC First Bank Ltd", sec: "Finance" },
  { sym: "AUBANK", name: "AU Small Finance Bank", sec: "Finance" },
  { sym: "PNB", name: "Punjab National Bank", sec: "Finance" },
  { sym: "BANKBARODA", name: "Bank of Baroda", sec: "Finance" },
  { sym: "CANBK", name: "Canara Bank Ltd", sec: "Finance" },
  { sym: "BIOCON", name: "Biocon Ltd", sec: "Biotech" },
  { sym: "LUPIN", name: "Lupin Ltd", sec: "Pharma" },
  { sym: "TORNTPHARM", name: "Torrent Pharmaceuticals", sec: "Pharma" },
  { sym: "APOLLOHOSP", name: "Apollo Hospitals", sec: "Healthcare" },
  { sym: "FORTIS", name: "Fortis Healthcare", sec: "Healthcare" },
  { sym: "MAXHEALTH", name: "Max Healthcare Institute", sec: "Healthcare" },
  { sym: "NAUKRI", name: "Info Edge India Ltd", sec: "Technology" },
  { sym: "PERSISTENT", name: "Persistent Systems", sec: "Technology" },
  { sym: "COFORGE", name: "Coforge Ltd", sec: "Technology" },
  { sym: "MPHASIS", name: "Mphasis Ltd", sec: "Technology" },
  { sym: "LTIM", name: "LTIMindtree Ltd", sec: "Technology" },
  { sym: "OFSS", name: "Oracle Financial Services", sec: "Technology" },
  { sym: "TATAELXSI", name: "Tata Elxsi Ltd", sec: "Technology" },
  { sym: "BOSCHLTD", name: "Bosch Ltd", sec: "Automotive" },
  { sym: "MOTHERSON", name: "Motherson Sumi Systems", sec: "Automotive" },
  { sym: "ASHOKLEY", name: "Ashok Leyland Ltd", sec: "Automotive" },
  { sym: "CONCOR", name: "Container Corp of India", sec: "Logistics" },
  { sym: "IRCTC", name: "IRCTC Ltd", sec: "Travel" },
  { sym: "INDIGO", name: "InterGlobe Aviation", sec: "Travel" },
  { sym: "JINDALSTEL", name: "Jindal Steel & Power", sec: "Steel" },
  { sym: "SAIL", name: "Steel Authority of India", sec: "Steel" },
  { sym: "VEDL", name: "Vedanta Ltd", sec: "Mining" },
  { sym: "HINDALCO", name: "Hindalco Industries", sec: "Materials" },
  { sym: "NALCO", name: "National Aluminium Co", sec: "Materials" },
  { sym: "UPL", name: "UPL Ltd", sec: "Chemicals" },
  { sym: "PIIND", name: "PI Industries Ltd", sec: "Chemicals" },
  { sym: "SRF", name: "SRF Ltd", sec: "Chemicals" },
  { sym: "TRENT", name: "Trent Ltd", sec: "Retail" },
  { sym: "PAGEIND", name: "Page Industries Ltd", sec: "Textiles" },
  { sym: "MCDOWELL-N", name: "United Spirits Ltd", sec: "Consumer" },
  { sym: "UBL", name: "United Breweries Ltd", sec: "Consumer" },
  { sym: "TATACONSUM", name: "Tata Consumer Products", sec: "Food" },
  { sym: "EMAMILTD", name: "Emami Ltd", sec: "Consumer" },
  { sym: "BAJAJHLDNG", name: "Bajaj Holdings & Investment", sec: "Finance" },
  { sym: "VOLTAS", name: "Voltas Ltd", sec: "Consumer" },
  { sym: "BLUESTAR", name: "Blue Star Ltd", sec: "Consumer" },
  { sym: "AMARAJABAT", name: "Amara Raja Batteries", sec: "Industrial" },
  { sym: "EXIDEIND", name: "Exide Industries Ltd", sec: "Industrial" },
  { sym: "SIEMENS", name: "Siemens Ltd", sec: "Industrial" },
  { sym: "ABB", name: "ABB India Ltd", sec: "Industrial" },
  { sym: "CGPOWER", name: "CG Power & Industrial", sec: "Industrial" },
  { sym: "POLYCAB", name: "Polycab India Ltd", sec: "Industrial" },
  { sym: "KEIIND", name: "KEI Industries Ltd", sec: "Industrial" },
  { sym: "MRF", name: "MRF Ltd", sec: "Automotive" },
  { sym: "APOLLOTYRE", name: "Apollo Tyres Ltd", sec: "Automotive" },
  { sym: "CEATLTD", name: "CEAT Ltd", sec: "Automotive" },
  { sym: "TATAPOWER", name: "Tata Power Co Ltd", sec: "Utilities" },
  { sym: "TATACHEM", name: "Tata Chemicals Ltd", sec: "Chemicals" },
  { sym: "ADANIPOWER", name: "Adani Power Ltd", sec: "Utilities" },
  { sym: "ADANIGREEN", name: "Adani Green Energy", sec: "RenewableEnergy" },
  { sym: "ADANITRANS", name: "Adani Transmission", sec: "Utilities" },
  { sym: "ADANITOTAL", name: "Adani Total Gas Ltd", sec: "Energy" },
  { sym: "ADANIWINS", name: "Adani Wilmar Ltd", sec: "Food" },
  { sym: "RAMCOCEM", name: "The Ramco Cements", sec: "Construction" },
  { sym: "DALMIABHA", name: "Dalmia Bharat Ltd", sec: "Construction" },
  { sym: "JKCEMENT", name: "JK Cement Ltd", sec: "Construction" },
  { sym: "INDIACEM", name: "India Cements Ltd", sec: "Construction" },
  { sym: "BIRLACORP", name: "Birla Corporation Ltd", sec: "Construction" },
  { sym: "RECLTD", name: "REC Ltd", sec: "Finance" },
  { sym: "PFC", name: "Power Finance Corp", sec: "Finance" },
  { sym: "IRFC", name: "Indian Railway Finance", sec: "Finance" },
  { sym: "MAZDOCK", name: "Mazagon Dock Shipbuilders", sec: "Defense" },
  { sym: "HAL", name: "Hindustan Aeronautics Ltd", sec: "Defense" },
  { sym: "BEL", name: "Bharat Electronics Ltd", sec: "Defense" },
  { sym: "BHEL", name: "Bharat Heavy Electricals", sec: "Industrial" },
  { sym: "RVNL", name: "Rail Vikas Nigam Ltd", sec: "Industrial" },
  { sym: "IRCON", name: "IRCON International Ltd", sec: "Industrial" },
  { sym: "NBCC", name: "NBCC India Ltd", sec: "Construction" },
  { sym: "HUDCO", name: "Housing & Urban Dev Corp", sec: "Finance" },
  { sym: "OIL", name: "Oil India Ltd", sec: "Energy" },
  { sym: "PETRONET", name: "Petronet LNG Ltd", sec: "Energy" },
  { sym: "AARTIIND", name: "Aarti Industries Ltd", sec: "Chemicals" },
  { sym: "ATUL", name: "Atul Ltd", sec: "Chemicals" },
  { sym: "DEEPAKNTR", name: "Deepak Nitrite Ltd", sec: "Chemicals" },
  { sym: "NAVINFLUOR", name: "Navin Fluorine Intl", sec: "Chemicals" },
  { sym: "ALCHEM", name: "Alkem Laboratories Ltd", sec: "Pharma" },
  { sym: "LALPATHLAB", name: "Dr Lal PathLabs Ltd", sec: "Healthcare" },
  { sym: "THYROCARE", name: "Thyrocare Technologies", sec: "Healthcare" },
  { sym: "METROPOLIS", name: "Metropolis Healthcare", sec: "Healthcare" },
  { sym: "GLENMARK", name: "Glenmark Pharmaceuticals", sec: "Pharma" },
  { sym: "CADILA", name: "Zydus Lifesciences Ltd", sec: "Pharma" },
  { sym: "AUROPHARMA", name: "Aurobindo Pharma Ltd", sec: "Pharma" },
  { sym: "LAURUSLABS", name: "Laurus Labs Ltd", sec: "Pharma" },
  { sym: "SYNGENE", name: "Syngene International Ltd", sec: "Biotech" },
  { sym: "BSE", name: "BSE Ltd", sec: "Finance" },
  { sym: "MCX", name: "Multi Commodity Exchange", sec: "Finance" },
  { sym: "IEX", name: "Indian Energy Exchange", sec: "Utilities" },
  { sym: "CAMS", name: "Computer Age Management", sec: "Finance" },
  { sym: "PAYTM", name: "One97 Communications Ltd", sec: "Fintech" },
  { sym: "POLICYBZR", name: "PB Fintech Ltd", sec: "Fintech" },
  { sym: "NYKAA", name: "FSN E-Commerce Ltd", sec: "ECommerce" },
  { sym: "SWIGGY", name: "Swiggy Ltd", sec: "ECommerce" },
  { sym: "LICI", name: "Life Insurance Corp India", sec: "Finance" },
  { sym: "SBICARD", name: "SBI Cards & Payments", sec: "Finance" },
  { sym: "HDFCAMC", name: "HDFC Asset Management", sec: "Finance" },
  { sym: "ICICIPRULI", name: "ICICI Prudential Life Ins", sec: "Finance" },
  { sym: "STARHEALTH", name: "Star Health & Allied Ins", sec: "Finance" },
  { sym: "JSWENERGY", name: "JSW Energy Ltd", sec: "Utilities" },
  { sym: "GMRINFRA", name: "GMR Infrastructure Ltd", sec: "Industrial" },
  { sym: "LTTS", name: "L&T Technology Services", sec: "Technology" },
  { sym: "TATACOMM", name: "Tata Communications Ltd", sec: "Communication" },
  { sym: "TATATECH", name: "Tata Technologies Ltd", sec: "Technology" },
  { sym: "OBEROIRLTY", name: "Oberoi Realty Ltd", sec: "RealEstate" },
  { sym: "GODREJPROP", name: "Godrej Properties Ltd", sec: "RealEstate" },
  { sym: "PRESTIGE", name: "Prestige Estates Projects", sec: "RealEstate" },
  { sym: "SOBHA", name: "Sobha Ltd", sec: "RealEstate" },
  { sym: "LODHA", name: "Macrotech Developers Ltd", sec: "RealEstate" },
  { sym: "PHOENIXTOWN", name: "The Phoenix Mills Ltd", sec: "RealEstate" },
  { sym: "MANAPPURAM", name: "Manappuram Finance Ltd", sec: "Finance" },
  { sym: "MUTHOOTFIN", name: "Muthoot Finance Ltd", sec: "Finance" },
  { sym: "CHOLAFIN", name: "Cholamandalam Investment", sec: "Finance" },
  { sym: "M&MFIN", name: "Mahindra & Mahindra Financial", sec: "Finance" },
  { sym: "APLAPOLLO", name: "APL Apollo Tubes Ltd", sec: "Steel" },
  { sym: "JINDALSAW", name: "Jindal Saw Ltd", sec: "Steel" },
  { sym: "JSL", name: "Jindal Stainless Ltd", sec: "Steel" },
  { sym: "ASTRAL", name: "Astral Ltd", sec: "Industrial" },
  { sym: "KALYANKJIL", name: "Kalyan Jewellers India", sec: "Retail" },
  { sym: "BATAINDIA", name: "Bata India Ltd", sec: "Retail" },
  { sym: "RELAXO", name: "Relaxo Footwears Ltd", sec: "Retail" },
  { sym: "INDHOTEL", name: "Indian Hotels Company", sec: "Travel" },
  { sym: "EIHOTEL", name: "EIH Ltd (Oberoi Hotels)", sec: "Travel" },
  { sym: "CHENNPETRO", name: "Chennai Petroleum Corp", sec: "Energy" },
  { sym: "MRPL", name: "Mangalore Refinery & Petro", sec: "Energy" },
  { sym: "FINCABLES", name: "Finolex Cables Ltd", sec: "Industrial" },
  { sym: "VGUARD", name: "V-Guard Industries", sec: "Consumer" },
  { sym: "SYMPHONY", name: "Symphony Ltd", sec: "Consumer" },
  { sym: "COROMANDEL", name: "Coromandel International", sec: "Chemicals" },
  { sym: "CHAMBLFERT", name: "Chambal Fertilisers", sec: "Chemicals" },
  { sym: "GNFC", name: "Gujarat Narmada Fertilizers", sec: "Chemicals" },
  { sym: "GSFC", name: "Gujarat State Fertilizers", sec: "Chemicals" },
  { sym: "RCF", name: "Rashtriya Chemicals & Fert", sec: "Chemicals" },
  { sym: "NFL", name: "National Fertilizers Ltd", sec: "Chemicals" },
  { sym: "IPCALAB", name: "IPCA Laboratories Ltd", sec: "Pharma" },
  { sym: "INDOCO", name: "Indoco Remedies Ltd", sec: "Pharma" },
  { sym: "HEG", name: "HEG Ltd", sec: "Industrial" },
  { sym: "CARBORUNIV", name: "Carborundum Universal", sec: "Industrial" },
  { sym: "KPRMILL", name: "KPR Mill Ltd", sec: "Textiles" },
  { sym: "WELSPUNLIV", name: "Welspun Living Ltd", sec: "Textiles" },
  { sym: "ARVIND", name: "Arvind Ltd", sec: "Textiles" },
  { sym: "RAYMOND", name: "Raymond Ltd", sec: "Textiles" },
  { sym: "RITES", name: "RITES Ltd", sec: "Industrial" },
  { sym: "BEML", name: "BEML Ltd", sec: "Industrial" },
  { sym: "NCC", name: "NCC Ltd", sec: "Construction" },
  { sym: "PNCINFRA", name: "PNC Infratech Ltd", sec: "Construction" },
  { sym: "KNRCONSTR", name: "KNR Constructions Ltd", sec: "Construction" },
  { sym: "UJJIVANSFB", name: "Ujjivan Small Finance Bank", sec: "Finance" },
  { sym: "EQUITASBNK", name: "Equitas Small Finance Bank", sec: "Finance" },
  { sym: "LICHSGFIN", name: "LIC Housing Finance Ltd", sec: "Finance" },
  { sym: "PNBHOUSING", name: "PNB Housing Finance Ltd", sec: "Finance" },
  { sym: "AAVAS", name: "Aavas Financiers Ltd", sec: "Finance" },
  { sym: "HOMEFIRST", name: "Home First Finance Company", sec: "Finance" },
  { sym: "CANFINHOMES", name: "Can Fin Homes Ltd", sec: "Finance" },
  { sym: "LTF", name: "L&T Finance Holdings Ltd", sec: "Finance" },
  { sym: "UTIAMC", name: "UTI Asset Management Co", sec: "Finance" },
  { sym: "NAM-INDIA", name: "Nippon Life India Asset", sec: "Finance" },
  { sym: "MAXFIN", name: "Max Financial Services Ltd", sec: "Finance" },
  { sym: "DELHIVERY", name: "Delhivery Ltd", sec: "Logistics" },
  { sym: "TATAINVEST", name: "Tata Investment Corp", sec: "Finance" },
  { sym: "SONACOM", name: "Sona Comstar Ltd", sec: "Automotive" },
  { sym: "CUMMINSIND", name: "Cummins India Ltd", sec: "Industrial" },
  { sym: "BRIGADE", name: "Brigade Enterprises Ltd", sec: "RealEstate" },
  { sym: "NATIONALUM", name: "National Aluminium Co", sec: "Mining" },
  { sym: "RATNAMANI", name: "Ratnamani Metals & Tubes", sec: "Steel" },
  { sym: "WELCORP", name: "Welspun Corp Ltd", sec: "Steel" },
  { sym: "PRINCEPIPES", name: "Prince Pipes & Fittings", sec: "Industrial" },
  { sym: "SUPREMEIND", name: "Supreme Industries Ltd", sec: "Industrial" },
  { sym: "FINOLEXIND", name: "Finolex Industries Ltd", sec: "Industrial" },
  { sym: "GALAXYSURF", name: "Galaxy Surfactants Ltd", sec: "Chemicals" },
  { sym: "FINEORG", name: "Fine Organic Industries", sec: "Chemicals" },
  { sym: "VINATIORGA", name: "Vinati Organics Ltd", sec: "Chemicals" },
  { sym: "SUMITOMO", name: "Sumitomo Chemical India", sec: "Chemicals" },
  { sym: "BHARATRAS", name: "Bharat Rasayan Ltd", sec: "Chemicals" },
  { sym: "FERTILISERS", name: "Fertilizers & Chemicals", sec: "Chemicals" },
  { sym: "FACT", name: "Fertilizers & Chemicals Travancore", sec: "Chemicals" },
  { sym: "ZUARI", name: "Zuari Agro Chemicals Ltd", sec: "Chemicals" },
  { sym: "STARCEMENT", name: "Star Cement Ltd", sec: "Construction" },
  { sym: "NUVOCO", name: "Nuvoco Vistas Corp Ltd", sec: "Construction" },
  { sym: "DALMIASUG", name: "Dalmia Sugars Ltd", sec: "Food" },
  { sym: "LINDEINDIA", name: "Linde India Ltd", sec: "Chemicals" },
  { sym: "MEDHEALTH", name: "Medi Assist Health Services", sec: "Finance" },
  { sym: "KFTECH", name: "KFintech Ltd", sec: "Finance" },
  { sym: "VMART", name: "V-Mart Retail Ltd", sec: "Retail" },
  { sym: "SHOPSTOP", name: "Shoppers Stop Ltd", sec: "Retail" },
  { sym: "TCNSBRANDS", name: "TCNS Clothing Co Ltd", sec: "Retail" },
  { sym: "BANKINDIA", name: "Bank of India", sec: "Finance" },
  { sym: "MAHABANK", name: "Bank of Maharashtra", sec: "Finance" },
  { sym: "UNIONBANK", name: "Union Bank of India", sec: "Finance" },
  { sym: "IOB", name: "Indian Overseas Bank", sec: "Finance" },
  { sym: "CENTRALBK", name: "Central Bank of India", sec: "Finance" },
  { sym: "CORPBANK", name: "Corporation Bank", sec: "Finance" },
  { sym: "DENABANK", name: "Dena Bank Ltd", sec: "Finance" },
  { sym: "ALLAHABANK", name: "Allahabad Bank", sec: "Finance" },
  { sym: "SYNDICATE", name: "Syndicate Bank", sec: "Finance" },
  { sym: "ANDHRABANK", name: "Andhra Bank", sec: "Finance" },
  { sym: "ORIENTBANK", name: "Oriental Bank of Commerce", sec: "Finance" },
  { sym: "VSTIND", name: "VST Industries Ltd", sec: "Consumer" },
  { sym: "GODREJIND", name: "Godrej Industries Ltd", sec: "Consumer" },
  { sym: "GODREJAGRO", name: "Godrej Agrovet Ltd", sec: "AgriTech" },
  { sym: "KSCL", name: "Kerala State Chemicals", sec: "Chemicals" },
  { sym: "BALMLAWRIE", name: "Balmer Lawrie & Co", sec: "Industrial" },
  { sym: "BALAMINES", name: "Balaji Amines Ltd", sec: "Chemicals" },
  { sym: "BALAKRISHNA", name: "Balakrishna Industries", sec: "Automotive" },
  { sym: "JKTYRE", name: "JK Tyre & Industries", sec: "Automotive" },
  { sym: "GOODYEAR", name: "Goodyear India Ltd", sec: "Automotive" },
  { sym: "MIRZAINT", name: "Mirza International Ltd", sec: "Textiles" },
  { sym: "WELSPLAST", name: "Welspun Plastics Ltd", sec: "Textiles" },
  { sym: "GAROD", name: "Garod Chemicals Ltd", sec: "Chemicals" },
  { sym: "TATASPONGE", name: "Tata Sponge Iron Ltd", sec: "Steel" },
  { sym: "TATAMETALI", name: "Tata Metaliks Ltd", sec: "Steel" },
  { sym: "TATAYODOGA", name: "Tata Yodogawa Ltd", sec: "Steel" },
  { sym: "TATASTLBSL", name: "Tata Steel BSL Ltd", sec: "Steel" },
  { sym: "TATASTLLP", name: "Tata Steel Long Products", sec: "Steel" },
  { sym: "NATCOPHARM", name: "Natco Pharma Ltd", sec: "Pharma" },
  { sym: "SANOFI", name: "Sanofi India Ltd", sec: "Pharma" },
  { sym: "ABBOTINDIA", name: "Abbott India Ltd", sec: "Pharma" },
  { sym: "PFIZER", name: "Pfizer Ltd", sec: "Pharma" },
  { sym: "NOVARTIS", name: "Novartis India Ltd", sec: "Pharma" },
  { sym: "MERCK", name: "Merck Ltd India", sec: "Pharma" },
  { sym: "GLENMARK2", name: "Glenmark Life Sciences", sec: "Pharma" },
  { sym: "SUZLON", name: "Suzlon Energy Ltd", sec: "RenewableEnergy" },
  { sym: "BORORENEW", name: "Borosil Renewables", sec: "RenewableEnergy" },
  { sym: "KPITTECH", name: "KPIT Technologies Ltd", sec: "Technology" },
  { sym: "PERSISTENT2", name: "Persistent Systems Ltd", sec: "Technology" },
  { sym: "TATAINTECH", name: "Tata Interactive Systems", sec: "Technology" },
  { sym: "MPHASIS2", name: "Mphasis BFL Ltd", sec: "Technology" },
  { sym: "MASTEK", name: "Mastek Ltd", sec: "Technology" },
  { sym: "ZENSAR", name: "Zensar Technologies Ltd", sec: "Technology" },
  { sym: "SONATA", name: "Sonata Software Ltd", sec: "Technology" },
  { sym: "RPGROUP", name: "RP-Sanjiv Goenka Group", sec: "Industrial" },
  { sym: "CESC", name: "CESC Ltd", sec: "Utilities" },
  { sym: "RPIL", name: "RP Power Ltd", sec: "Utilities" },
  { sym: "PHILIPSCARB", name: "Philips Carbon Black Ltd", sec: "Industrial" },
  { sym: "NRC", name: "NRC Ltd", sec: "Industrial" },
  { sym: "KESORAM", name: "Kesoram Industries Ltd", sec: "Industrial" },
  { sym: "BIRLACABLE", name: "Birla Cable Ltd", sec: "Industrial" },
  { sym: "INDORAMA", name: "Indorama Synthetics Ltd", sec: "Textiles" },
  { sym: "VTL", name: "Vardhman Textiles Ltd", sec: "Textiles" },
  { sym: "VARDHMAN", name: "Vardhman Special Yarns", sec: "Textiles" },
  { sym: "AARVEE", name: "Aarvee Denims Ltd", sec: "Textiles" },
  { sym: "DENIMX", name: "Denim X Ltd", sec: "Textiles" },
  { sym: "ARVINDFSL", name: "Arvind Fashions Ltd", sec: "Textiles" },
  { sym: "GAROD2", name: "Garod Fibres Ltd", sec: "Textiles" },
  { sym: "DONEAR", name: "Donear Industries Ltd", sec: "Textiles" },
  { sym: "RAYMOND2", name: "Raymond Lifestyle Ltd", sec: "Textiles" },
  { sym: "RAYMOND3", name: "Raymond Realty Ltd", sec: "RealEstate" },
  { sym: "GOKALDAS", name: "Gokaldas Exports Ltd", sec: "Textiles" },
  { sym: "TCN", name: "TCN Textiles Ltd", sec: "Textiles" },
  { sym: "WELSPUNCORP", name: "Welspun Corp Ltd", sec: "Steel" },
  { sym: "SURYODAY", name: "Suryoday Small Finance Bank", sec: "Finance" },
  { sym: "UTKARSHBNK", name: "Utkarsh Small Finance Bank", sec: "Finance" },
  { sym: "FINO", name: "Fino Payments Bank", sec: "Finance" },
  { sym: "UJJIVAN", name: "Ujjivan Financial Services", sec: "Finance" },
  { sym: "EQUITAS", name: "Equitas Holdings Ltd", sec: "Finance" },
  { sym: "REPCOHOME", name: "Repco Home Finance Ltd", sec: "Finance" },
  { sym: "GRUH", name: "GRUH Finance Ltd", sec: "Finance" },
  { sym: "PNBHOUSING2", name: "PNB Housing Finance", sec: "Finance" },
  { sym: "GRASIM2", name: "Grasim Industries Ltd", sec: "Materials" },
  { sym: "ULTRACEMCO2", name: "UltraTech Cement Ltd", sec: "Construction" },
  { sym: "ADITYABIRLA", name: "Aditya Birla Capital Ltd", sec: "Finance" },
  { sym: "ABCAPITAL", name: "Aditya Birla Capital Ltd", sec: "Finance" },
  { sym: "ABSLAMC", name: "Aditya Birla Sun Life AMC", sec: "Finance" },
  { sym: "HDFCAMC2", name: "HDFC Asset Management Co", sec: "Finance" },
  { sym: "ICICIAMC", name: "ICICI Asset Management", sec: "Finance" },
  { sym: "SBIAMC", name: "SBI Funds Management", sec: "Finance" },
  { sym: "TATAMUTUAL", name: "Tata Mutual Fund", sec: "Finance" },
  { sym: "KOTAKMF", name: "Kotak Mahindra AMC", sec: "Finance" },
  { sym: "AXISMF", name: "Axis Mutual Fund", sec: "Finance" },
  { sym: "DSPMF", name: "DSP Mutual Fund", sec: "Finance" },
  { sym: "FRANKLIN", name: "Franklin Templeton MF", sec: "Finance" },
  { sym: "MIRAE", name: "Mirae Asset MF", sec: "Finance" },
  { sym: "NIPPON", name: "Nippon Life India MF", sec: "Finance" },
  { sym: "QUANTUM", name: "Quantum Mutual Fund", sec: "Finance" },
  { sym: "MOTILAL", name: "Motilal Oswal MF", sec: "Finance" },
  { sym: "EDGEL", name: "Edelweiss Mutual Fund", sec: "Finance" },
  { sym: "BARODA", name: "Baroda BNP Paribas MF", sec: "Finance" },
  { sym: "BOIAXA", name: "BOI AXA Investment Mgrs", sec: "Finance" },
  { sym: "CANROBECO", name: "Canara Robeco MF", sec: "Finance" },
  { sym: "HSBCMF", name: "HSBC Mutual Fund", sec: "Finance" },
  { sym: "IDFCMF", name: "IDFC Mutual Fund", sec: "Finance" },
  { sym: "IIFLMF", name: "IIFL Mutual Fund", sec: "Finance" },
  { sym: "ITIMF", name: "ITI Mutual Fund", sec: "Finance" },
  { sym: "JMFIN", name: "JM Financial MF", sec: "Finance" },
  { sym: "MAHINDRA", name: "Mahindra Manulife MF", sec: "Finance" },
  { sym: "PGIM", name: "PGIM India MF", sec: "Finance" },
  { sym: "PPFAS", name: "PPFAS Mutual Fund", sec: "Finance" },
  { sym: "QUANT", name: "Quant Mutual Fund", sec: "Finance" },
  { sym: "SUNDARAM", name: "Sundaram Mutual Fund", sec: "Finance" },
  { sym: "TAURUS", name: "Taurus Mutual Fund", sec: "Finance" },
  { sym: "TATAINFRA", name: "Tata Infrastructure Fund", sec: "Finance" },
  { sym: "UTIMF", name: "UTI Mutual Fund", sec: "Finance" },
  { sym: "ZERODHA", name: "Zerodha Broking Ltd", sec: "Fintech" },
  { sym: "GROWW", name: "Groww (Billionbrains)", sec: "Fintech" },
  { sym: "UPSTOX", name: "RKSV Securities (Upstox)", sec: "Fintech" },
  { sym: "ANGELONE", name: "Angel One Ltd", sec: "Fintech" },
  { sym: "5PAISA", name: "5paisa Capital Ltd", sec: "Fintech" },
  { sym: "ICICIDIRECT", name: "ICICI Securities Ltd", sec: "Fintech" },
  { sym: "HDFCSEC", name: "HDFC Securities Ltd", sec: "Fintech" },
  { sym: "SBISMART", name: "SBI Securities Ltd", sec: "Fintech" },
  { sym: "KOTAKSEC", name: "Kotak Securities Ltd", sec: "Fintech" },
  { sym: "AXISSEC", name: "Axis Securities Ltd", sec: "Fintech" },
  { sym: "MOTILALOSWAL", name: "Motilal Oswal Financial", sec: "Finance" },
  { sym: "SHAREKHAN", name: "Sharekhan Ltd", sec: "Fintech" },
  { sym: "IIFL", name: "IIFL Securities Ltd", sec: "Finance" },
  { sym: "GEPL", name: "Gepl Capital Ltd", sec: "Fintech" },
  { sym: "SMC", name: "SMC Global Securities", sec: "Fintech" },
  { sym: "RELIGARE", name: "Religare Enterprises", sec: "Finance" },
  { sym: "EDELWEISS", name: "Edelweiss Financial Services", sec: "Finance" },
  { sym: "ANANDRATHI2", name: "Anand Rathi Financial Services", sec: "Finance" },
  { sym: "GEFIN", name: "Geojit Financial Services", sec: "Finance" },
  { sym: "NIRMALBANG", name: "Nirmal Bang Securities", sec: "Fintech" },
  { sym: "ASITRA", name: "Asit C Mehta Financial", sec: "Fintech" },
  { sym: "BONANZA", name: "Bonanza Portfolio Ltd", sec: "Fintech" },
  { sym: "INDTRADE", name: "Indtrade Securities Ltd", sec: "Fintech" },
  { sym: "KARVY", name: "Karvy Stock Broking", sec: "Fintech" },
  { sym: "PRABHUDAS", name: "Prabhudas Lilladher", sec: "Fintech" },
  { sym: "SBICAP", name: "SBI Capital Markets", sec: "Finance" },
  { sym: "IDFCCAP", name: "IDFC Capital Advisors", sec: "Finance" },
  { sym: "ENAM", name: "Enam Securities Pvt Ltd", sec: "Finance" },
  { sym: "JMFIN2", name: "JM Financial Ltd", sec: "Finance" },
  { sym: "AVENDUS", name: "Avendus Capital Pvt Ltd", sec: "Finance" },
  { sym: "O3CAP", name: "O3 Capital Advisors", sec: "Finance" },
  { sym: "EQUITY", name: "Equity Master Ltd", sec: "Finance" },
  { sym: "BAJAJCAP", name: "Bajaj Capital Ltd", sec: "Finance" },
  { sym: "NJINDIA", name: "NJ India Invest Pvt Ltd", sec: "Finance" },
  { sym: "PRINCIPAL", name: "Principal Mutual Fund", sec: "Finance" },
  { sym: "RELIANCEMF", name: "Reliance Nippon Life AMC", sec: "Finance" },
  { sym: "TATAPE", name: "Tata Private Equity", sec: "Finance" },
  { sym: "KOTAKPE", name: "Kotak Private Equity", sec: "Finance" },
  { sym: "IDFCPE", name: "IDFC Private Equity", sec: "Finance" },
  { sym: "ICICIPE", name: "ICICI Venture Funds", sec: "Finance" },
  { sym: "AXISPE", name: "Axis Private Equity", sec: "Finance" },
  { sym: "ADITYAPE", name: "Aditya Birla Private Equity", sec: "Finance" },
  { sym: "SBIPE", name: "SBI Private Equity", sec: "Finance" },
  { sym: "ELEVATION", name: "Elevation Capital", sec: "Finance" },
  { sym: "SEQUOIA", name: "Sequoia Capital India", sec: "Finance" },
  { sym: "ACCENTURE", name: "Accel Partners India", sec: "Finance" },
  { sym: "BLAURUN", name: "Blume Ventures", sec: "Finance" },
  { sym: "KALAARI", name: "Kalaari Capital", sec: "Finance" },
  { sym: "NEXUS", name: "Nexus Venture Partners", sec: "Finance" },
  { sym: "SAIF", name: "SAIF Partners India", sec: "Finance" },
  { sym: "MATRIX", name: "Matrix Partners India", sec: "Finance" },
  { sym: "NORWEST", name: "Norwest Venture Partners", sec: "Finance" },
  { sym: "BESSEMER", name: "Bessemer Venture Partners", sec: "Finance" },
  { sym: "HELION", name: "Helion Venture Partners", sec: "Finance" },
  { sym: "INTEL", name: "Intel Capital India", sec: "Finance" },
  { sym: "QUALCOMM", name: "Qualcomm Ventures India", sec: "Finance" },
  { sym: "TATAVOL", name: "Tata Capital Ventures", sec: "Finance" },
  { sym: "SHARPDIST", name: "Sharp Distinctions Pvt Ltd", sec: "Finance" },
  { sym: "INFLOW", name: "Inflow Ventures", sec: "Finance" },
  { sym: "INDIAPE", name: "India Alternatives Fund", sec: "Finance" },
  { sym: "YOURNEST", name: "YourNest Venture Capital", sec: "Finance" },
  { sym: "ENDIYA", name: "Endiya Partners", sec: "Finance" },
  { sym: "3ONE4", name: "3one4 Capital", sec: "Finance" },
  { sym: "FIRESTAR", name: "Firestar Ventures India", sec: "Finance" },
  { sym: "DEXCAR", name: " Dexter Capital Advisors", sec: "Finance" },
  { sym: "FLEXILOAN", name: "FlexiLoans.com Technologies", sec: "Fintech" },
  { sym: "INDIFI", name: "Indifi Technologies", sec: "Fintech" },
  { sym: "RUPEELANE", name: "RupeeLane Finance", sec: "Fintech" },
  { sym: "LENDINGKART", name: "Lendingkart Finance", sec: "Fintech" },
  { sym: "CAPITALFLOAT", name: "Capital Float (Axio)", sec: "Fintech" },
  { sym: "KREDITBEE", name: "KreditBee (Krazybee)", sec: "Fintech" },
  { sym: "NAIRABANK", name: "Nira Finance Pvt Ltd", sec: "Fintech" },
  { sym: "MONEYTAP", name: "MoneyTap (MWYNTech)", sec: "Fintech" },
  { sym: "PAYSENSE", name: "PaySense Technologies", sec: "Fintech" },
  { sym: "ZAVRON", name: "Zavron Fintech", sec: "Fintech" },
  { sym: "CREDENCIA", name: "Credencia Fintech", sec: "Fintech" },
  { sym: "FINOMICS", name: "Finomics Fintech", sec: "Fintech" },
  { sym: "RUPIFI", name: "Rupifi Fintech", sec: "Fintech" },
  { sym: "BENEFIT", name: "Benefit Fintech", sec: "Fintech" },
  { sym: "FINAGG", name: "FinAgg Technologies", sec: "Fintech" },
  { sym: "FINO2", name: "Finovation Tech", sec: "Fintech" },
  { sym: "GLADFIN", name: "Gladfin Technologies", sec: "Fintech" },
  { sym: "FINCRACK", name: "Fincrack Technologies", sec: "Fintech" },
  { sym: "FINFLOW", name: "FinFlow Technologies", sec: "Fintech" },
  { sym: "STASHFIN", name: "Stashfin (AKAR)", sec: "Fintech" },
  { sym: "CRED", name: "Cred Club", sec: "Fintech" },
  { sym: "UPI", name: "Unified Payments Interface", sec: "Fintech" },
  { sym: "PHONEPE", name: "PhonePe Pvt Ltd", sec: "Fintech" },
  { sym: "GPAY", name: "Google Pay India", sec: "Fintech" },
  { sym: "AMAZON", name: "Amazon India Pvt Ltd", sec: "ECommerce" },
  { sym: "FLIPKART", name: "Flipkart India Pvt Ltd", sec: "ECommerce" },
  { sym: "MEESHO", name: "Meesho Inc", sec: "ECommerce" },
  { sym: "MYNTRA", name: "Myntra Designs Pvt Ltd", sec: "ECommerce" },
  { sym: "SNAPDEAL", name: "Snapdeal Ltd", sec: "ECommerce" },
  { sym: "SHOPCLUES", name: "ShopClues", sec: "ECommerce" },
  { sym: "BIGBASKET", name: "BigBasket Pvt Ltd", sec: "ECommerce" },
  { sym: "GROFERS", name: "Blinkit (Grofers)", sec: "ECommerce" },
  { sym: "FIRSTCRY", name: "FirstCry (BrainBees)", sec: "ECommerce" },
  { sym: "NYKAA2", name: "Nykaa Fashion Ltd", sec: "ECommerce" },
  { sym: "BOOKMYSHOW", name: "BookMyShow (Bigtree)", sec: "ECommerce" },
  { sym: "MAKEMYTRIP", name: "MakeMyTrip Ltd", sec: "Travel" },
  { sym: "GOIBIBO", name: "Goibibo (MIH India)", sec: "Travel" },
  { sym: "CLEARTRIP", name: "Cleartrip Pvt Ltd", sec: "Travel" },
  { sym: "YATRA", name: "Yatra Online Inc", sec: "Travel" },
  { sym: "REDBUS", name: "redBus (Ibibo Group)", sec: "Travel" },
  { sym: "IXIGO", name: "Le Travenes Technology (ixigo)", sec: "Travel" },
  { sym: "EASEMYTRIP", name: "EaseMyTrip (DG Trip)", sec: "Travel" },
  { sym: "OLA", name: "Ola Cabs (ANI Technologies)", sec: "Travel" },
  { sym: "RAPIDO", name: "Roppen Transportation (Rapido)", sec: "Travel" },
  { sym: "UBERINDIA", name: "Uber India Systems", sec: "Travel" },
  { sym: "PORTER", name: "Porter (Loadshare Networks)", sec: "Logistics" },
  { sym: "DELHIVERY2", name: "Delhivery Pvt Ltd", sec: "Logistics" },
  { sym: "ECOMEXP", name: "Ecom Express Ltd", sec: "Logistics" },
  { sym: "XPRESSBEES", name: "Xpressbees (Busybees)", sec: "Logistics" },
  { sym: "SHADOWFAX", name: "Shadowfax Technologies", sec: "Logistics" },
  { sym: "SHIPROCKET", name: "Shiprocket (Bigship)", sec: "Logistics" },
  { sym: "RAZORPAY", name: "Razorpay Software Pvt Ltd", sec: "Fintech" },
  { sym: "CASHFREE", name: "Cashfree Payments India", sec: "Fintech" },
  { sym: "BILLDESK", name: "BillDesk Ltd", sec: "Fintech" },
  { sym: "PAISABAZAAR", name: "Paisabazaar Marketing", sec: "Fintech" },
  { sym: "BANKBAZAAR", name: "BankBazaar.com", sec: "Fintech" },
  { sym: "POLICYBZR2", name: "PolicyBazaar Insurance", sec: "Fintech" },
  { sym: "DREAM11", name: "Dream11 (Sporta Technologies)", sec: "Gaming" },
  { sym: "MY11CIRCLE", name: "My11Circle (Play Games24x7)", sec: "Gaming" },
  { sym: "MPL", name: "Mobile Premier League (Galaxy)", sec: "Gaming" },
  { sym: "WINZO", name: "WinZO Games Pvt Ltd", sec: "Gaming" },
  { sym: "NAZARA", name: "Nazara Technologies Ltd", sec: "Gaming" },
  { sym: "ZUPELO", name: "Zupelo Gaming Tech", sec: "Gaming" },
  { sym: "BYJUS", name: "BYJUS (Think & Learn)", sec: "EdTech" },
  { sym: "UNACADEMY", name: "Unacademy (Sorting Hat)", sec: "EdTech" },
  { sym: "VEDANTU", name: "Vedantu Innovations", sec: "EdTech" },
  { sym: "CUEMATH", name: "Cuemath (Cuelearn)", sec: "EdTech" },
  { sym: "TOPPR", name: "Toppr (Haygot Education)", sec: "EdTech" },
  { sym: "SIMPLILEARN", name: "Simplilearn Solutions", sec: "EdTech" },
  { sym: "UPGRAD", name: "UpGrad Education Pvt Ltd", sec: "EdTech" },
  { sym: "WHITEHAT", name: "WhiteHat Jr (Pythagoras)", sec: "EdTech" },
  { sym: "SWAYAM", name: "Swayam Education India", sec: "EdTech" },
  { sym: "PRACABS", name: "PracAbs Learning Pvt Ltd", sec: "EdTech" },
  { sym: "PHARM", name: "PharmEasy (API Holdings)", sec: "Healthcare" },
  { sym: "PRACTO", name: "Practo Technologies Pvt Ltd", sec: "Healthcare" },
  { sym: "1MG", name: "1mg Technologies (Tata 1mg)", sec: "Healthcare" },
  { sym: "NETMEDS", name: "Netmeds (Viseka Automation)", sec: "Healthcare" },
  { sym: "MFINE", name: "Mfine (MFine Innovations)", sec: "Healthcare" },
  { sym: "CULT", name: "Cult.fit (Curefit Healthcare)", sec: "Healthcare" },
  { sym: "HEALOFY", name: "Healofy Consulting", sec: "Healthcare" },
  { sym: "PORTIA", name: "Portea Medical (Healthvista)", sec: "Healthcare" },
  { sym: "BIOREVA", name: "Bioreva Healthcare", sec: "Healthcare" },
  { sym: "NIRAMAI", name: "Niramai Health Analytix", sec: "Healthcare" },
  { sym: "ONCO", name: "OncoStem Diagnostics", sec: "Healthcare" },
  { sym: "SIGMA", name: "Sigma Diagnostics Pvt Ltd", sec: "Healthcare" },
  { sym: "PHAMRA", name: "Pharmarack Technologies", sec: "Healthcare" },
  { sym: "AGRI", name: "AgriTech India Ltd", sec: "AgriTech" },
  { sym: "AGRIKEM", name: "AgriKem Industries Ltd", sec: "AgriTech" },
  { sym: "CROFARM", name: "CroFarm AgTech Pvt Ltd", sec: "AgriTech" },
  { sym: "AGROSTAR", name: "AgroStar (Agricx)", sec: "AgriTech" },
  { sym: "DEHAAT", name: "DeHaat (Green Agrevolution)", sec: "AgriTech" },
  { sym: "NINJACART", name: "NinjaCart (Ninjacart Veggies)", sec: "AgriTech" },
  { sym: "AGROBID", name: "AgroBid Technologies", sec: "AgriTech" },
  { sym: "FASAL", name: "Fasal (Wearable IoT)", sec: "AgriTech" },
  { sym: "CROPTIC", name: "Croptic AI Solutions", sec: "AgriTech" },
  { sym: "AGNEXT", name: "AgNext Technologies Pvt Ltd", sec: "AgriTech" },
  { sym: "AGRISETU", name: "AgriSetu Technologies", sec: "AgriTech" },
  { sym: "SKYMET", name: "Skymet Weather Pvt Ltd", sec: "AgriTech" },
  { sym: "CROPIN", name: "CropIn Technology Solutions", sec: "AgriTech" },
  { sym: "AGRESCO", name: "Agresco Data Sciences", sec: "AgriTech" },
  { sym: "AGRIWATCH", name: "Agriwatch Analytics", sec: "AgriTech" },
  { sym: "URBANCOMPANY", name: "Urban Company (UrbanClap)", sec: "Consumer" },
  { sym: "SWIGGY3", name: "Swiggy Pvt Ltd", sec: "ECommerce" },
  { sym: "ZOMATO3", name: "Zomato Ltd (Eternal)", sec: "ECommerce" },
  { sym: "SODEXO", name: "Sodexo India Services", sec: "Consumer" },
  { sym: "REFEX", name: "Refex Industries Ltd", sec: "Industrial" },
  { sym: "REFEX2", name: "Refex Renewables & Infra", sec: "RenewableEnergy" },
  { sym: "TATAPOWER2", name: "Tata Power Renewable Energy", sec: "RenewableEnergy" },
  { sym: "JSWENERGY2", name: "JSW Energy Ltd", sec: "Utilities" },
  { sym: "JSWHYDRO", name: "JSW Hydro Energy Ltd", sec: "Utilities" },
  { sym: "JSW2", name: "JSW Infrastructure Ltd", sec: "Industrial" },
  { sym: "GMRPORT", name: "GMR Ports & SEZ Ltd", sec: "Logistics" },
  { sym: "GMRPOWER", name: "GMR Power Urban Infra", sec: "Utilities" },
  { sym: "GMRIT", name: "GMR Information Technology", sec: "Technology" },
  { sym: "LRL", name: "Larsen & Toubro Infotech", sec: "Technology" },
  { sym: "TCS2", name: "Tata Interactive Systems", sec: "Technology" },
  { sym: "TCS3", name: "Tata Communications Ltd", sec: "Communication" },
  { sym: "TATAINVEST2", name: "Tata Investment Corp", sec: "Finance" },
  { sym: "TATACAPITAL", name: "Tata Capital Financial Services", sec: "Finance" },
  { sym: "TATAAIG", name: "Tata AIG General Insurance", sec: "Finance" },
  { sym: "TATASTEEL2", name: "Tata Steel BSL Ltd", sec: "Steel" },
  { sym: "TATASTEEL3", name: "Tata Steel Long Products", sec: "Steel" },
  { sym: "TATASTEEL4", name: "Tata Steel Downstream", sec: "Steel" },
  { sym: "TATASTEEL5", name: "Tata Steel Utilities", sec: "Utilities" },
  { sym: "TATASTEEL6", name: "Tata Steel Mining Ltd", sec: "Mining" },
  { sym: "TATASTEEL7", name: "Tata Steel Advanced Materials", sec: "Materials" },
  { sym: "TATASTEEL8", name: "Tata Steel Industrial Services", sec: "Industrial" },
  { sym: "TATASTEEL9", name: "Tata Steel Construction", sec: "Construction" },
  { sym: "TATASTEEL10", name: "Tata Steel Logistics", sec: "Logistics" },
  { sym: "TATASTEEL11", name: "Tata Steel Distribution", sec: "Logistics" },
  { sym: "TATASTEEL12", name: "Tata Steel International", sec: "Steel" },
  { sym: "TATASTEEL13", name: "Tata Steel Processing & Distribution", sec: "Steel" },
  { sym: "TATASTEEL14", name: "Tata Steel Bearings Ltd", sec: "Industrial" },
  { sym: "TATASTEEL15", name: "Tata Steel Agrico Ltd", sec: "Industrial" },
  { sym: "TCTC", name: "Tata Chemicals Ltd", sec: "Chemicals" },
  { sym: "TATACOFFEE", name: "Tata Coffee Ltd", sec: "Food" },
  { sym: "TATAGLOBAL", name: "Tata Global Beverages", sec: "Food" },
  { sym: "RIL2", name: "Reliance Industries Ltd", sec: "Energy" },
  { sym: "RPOWER", name: "Reliance Power Ltd", sec: "Utilities" },
  { sym: "RINFRA", name: "Reliance Infrastructure", sec: "Industrial" },
  { sym: "RCOM", name: "Reliance Communications", sec: "Communication" },
  { sym: "RNRL", name: "Reliance Natural Resources", sec: "Energy" },
  { sym: "RELIANCEJIO", name: "Reliance Jio Infocomm", sec: "Telecom" },
  { sym: "RELIANCERET", name: "Reliance Retail Ventures", sec: "Retail" },
  { sym: "RELIANCEDIG", name: "Reliance Digital Retail", sec: "Retail" },
  { sym: "JIOMART", name: "JioMart (Jio Platforms)", sec: "ECommerce" },
  { sym: "AJIO", name: "Ajio (Reliance Retail)", sec: "ECommerce" },
  { sym: "TRENT2", name: "Trent Ltd (Star Bazaar)", sec: "Retail" },
  { sym: "TRENT3", name: "Trent Brands Ltd", sec: "Retail" },
  { sym: "FUTURELIFE", name: "Future Lifestyle Fashions", sec: "Retail" },
  { sym: "FUTURERETAIL", name: "Future Retail Ltd", sec: "Retail" },
  { sym: "ZODIAC", name: "Zodiac Clothing House Ltd", sec: "Retail" },
  { sym: "TANISHQ", name: "Titan Tanishq Ltd", sec: "Retail" },
  { sym: "TITAN2", name: "Titan Company Ltd", sec: "Consumer" },
  { sym: "TITANGOLD", name: "Titan Gold Plus Ltd", sec: "Retail" },
  { sym: "KALYAN2", name: "Kalyan Jewellers India", sec: "Retail" },
  { sym: "TITANWATCH", name: "Titan Watches Ltd", sec: "Consumer" },
  { sym: "TITANEYE", name: "Titan Eye Plus Ltd", sec: "Consumer" },
  { sym: "IRCTC2", name: "IRCTC Catering Ltd", sec: "Travel" },
  { sym: "IRCTC3", name: "IRCTC Rail Connect", sec: "Technology" },
  { sym: "RAILTEL", name: "RailTel Corporation India", sec: "Telecom" },
  { sym: "IRCTC4", name: "IRCTC Tourism Ltd", sec: "Travel" },
  { sym: "RITES2", name: "RITES Engineering Ltd", sec: "Industrial" },
  { sym: "MIDHANI", name: "Mishra Dhatu Nigam Ltd", sec: "Defense" },
  { sym: "BANCO", name: "Banco Products India Ltd", sec: "Automotive" },
  { sym: "SUPRAJIT", name: "Suprajit Engineering Ltd", sec: "Automotive" },
  { sym: "SUBROS", name: "Subros Ltd", sec: "Automotive" },
  { sym: "MINDA", name: "Minda Industries Ltd", sec: "Automotive" },
  { sym: "MINDACORP", name: "Minda Corporation Ltd", sec: "Automotive" },
  { sym: "BOSCH2", name: "Bosch Global Software Tech", sec: "Technology" },
  { sym: "VARROC", name: "Varroc Engineering Ltd", sec: "Automotive" },
  { sym: "GABRIEL", name: "Gabriel India Ltd", sec: "Automotive" },
  { sym: "AUTOLITE", name: "Autolite India Ltd", sec: "Automotive" },
  { sym: "AUTOAXLES", name: "Automotive Axles Ltd", sec: "Automotive" },
  { sym: "WABCO", name: "Wabco India Ltd", sec: "Automotive" },
  { sym: "INDIA MOTOR", name: "India Motor Parts & Accessories", sec: "Automotive" },
  { sym: "AUTOIGN", name: "Auto Ignition Ltd", sec: "Automotive" },
  { sym: "MAHLE", name: "Mahle Anand Filter Systems", sec: "Automotive" },
  { sym: "FEDERALMOGUL", name: "Federal-Mogul Goetze", sec: "Automotive" },
  { sym: "AUTOMOTIVE", name: "Automotive Stamping India", sec: "Automotive" },
  { sym: "INDAG", name: "Indag Rubber Ltd", sec: "Automotive" },
  { sym: "APOLLOTYRE2", name: "Apollo Tyres Ltd", sec: "Automotive" },
  { sym: "TVS2", name: "TVS Srichakra Ltd", sec: "Automotive" },
  { sym: "TVS3", name: "TVS Motor Company Ltd", sec: "Automotive" },
  { sym: "TVS4", name: "TVS Electronics Ltd", sec: "Technology" },
  { sym: "TVS5", name: "TVS Supply Chain Solutions", sec: "Logistics" },
  { sym: "TVS6", name: "TVS Credit Services Ltd", sec: "Finance" },
  { sym: "TVS7", name: "TVS Interconnect Systems", sec: "Industrial" },
  { sym: "TVS8", name: "TVS Dynamic Brake Systems", sec: "Automotive" },
  { sym: "TVS9", name: "TVS Automotive Solutions", sec: "Automotive" },
  { sym: "MAHINDRA2", name: "Mahindra & Mahindra Financial", sec: "Finance" },
  { sym: "MAHINDRA3", name: "Mahindra Holidays & Resorts", sec: "Travel" },
  { sym: "MAHINDRA4", name: "Mahindra Lifespace Developers", sec: "RealEstate" },
  { sym: "MAHINDRA5", name: "Mahindra Logistics Ltd", sec: "Logistics" },
  { sym: "MAHINDRA6", name: "Mahindra Satyam Ltd", sec: "Technology" },
  { sym: "MAHINDRA7", name: "Mahindra Engineering Services", sec: "Industrial" },
  { sym: "MAHINDRA8", name: "Mahindra Vehicle Mobility", sec: "Automotive" },
  { sym: "MAHINDRA9", name: "Mahindra Electric Mobility", sec: "EV" },
  { sym: "MAHINDRA10", name: "Mahindra FirstChoice Services", sec: "Automotive" },
  { sym: "MAHINDRA11", name: "Mahindra Composites Ltd", sec: "Materials" },
  { sym: "MAHINDRA12", name: "Mahindra Heavy Engines", sec: "Industrial" },
  { sym: "MAHINDRA13", name: "Mahindra Construction Equipment", sec: "Construction" },
  { sym: "MAHINDRA14", name: "Mahindra Two Wheelers Ltd", sec: "Automotive" },
  { sym: "MAHINDRA15", name: "Mahindra Truck & Bus Division", sec: "Automotive" },
  { sym: "MAHINDRA16", name: "Mahindra Defence Systems", sec: "Defense" },
  { sym: "MAHINDRA17", name: "Mahindra Aerospace Pvt Ltd", sec: "Aerospace" },
  { sym: "MAHINDRA18", name: "Mahindra Intertrade Ltd", sec: "Industrial" },
  { sym: "MAHINDRA19", name: "Mahindra Powerol Ltd", sec: "Utilities" },
  { sym: "MAHINDRA20", name: "Mahindra GenZe Company", sec: "EV" },
  { sym: "MAHINDRA21", name: "Mahindra Susten Pvt Ltd", sec: "RenewableEnergy" },
  { sym: "MAHINDRA22", name: "Mahindra Rural Housing Finance", sec: "Finance" },
  { sym: "MAHINDRA23", name: "Mahindra Insurance Brokers", sec: "Finance" },
  { sym: "MAHINDRA24", name: "Mahindra Asset Management", sec: "Finance" },
  { sym: "MAHINDRA25", name: "Mahindra Manulife Investment", sec: "Finance" },
  { sym: "MAHINDRA26", name: "Mahindra Old World Hospitality", sec: "Travel" },
  { sym: "MAHINDRA27", name: "Mahindra Entertainment", sec: "Media" },
  { sym: "MAHINDRA28", name: "Mahindra Retail Ltd", sec: "Retail" },
  { sym: "MAHINDRA29", name: "Mahindra Agri Solutions", sec: "AgriTech" },
  { sym: "MAHINDRA30", name: "Mahindra Shubhlabh Services", sec: "AgriTech" },
  { sym: "TATAMOTORS2", name: "Tata Motors Ltd - DVR", sec: "Automotive" },
  { sym: "TATAMOTORS3", name: "Tata Motors Tech Ventures", sec: "Automotive" },
  { sym: "TATAMOTORS4", name: "Tata Motors Finance Ltd", sec: "Finance" },
  { sym: "TATAMOTORS5", name: "Tata Daewoo Commercial", sec: "Automotive" },
  { sym: "TATAMOTORS6", name: "Tata Hitachi Construction", sec: "Construction" },
  { sym: "TATAMOTORS7", name: "Tata Technologies Europe", sec: "Technology" },
  { sym: "TATAMOTORS8", name: "Tata Motors Insurance", sec: "Finance" },
  { sym: "TATAMOTORS9", name: "Tata Motors European Tech", sec: "Technology" },
  { sym: "TATAMOTORS10", name: "Jaguar Land Rover Ltd", sec: "Automotive" },
  { sym: "TATASTEEL16", name: "Tata Steel Growth Shop", sec: "Industrial" },
  { sym: "TATASTEEL17", name: "Tata Steel Projects India", sec: "Industrial" },
  { sym: "TATASTEEL18", name: "Tata Steel Refractories", sec: "Materials" },
  { sym: "TATASTEEL19", name: "Tata Steel Wire Division", sec: "Steel" },
  { sym: "TATASTEEL20", name: "Tata Steel Tubes Ltd", sec: "Steel" },
  { sym: "TATASTEEL21", name: "Tata Steel Bearings Div", sec: "Industrial" },
  { sym: "TATASTEEL22", name: "Tata Steel Construction Div", sec: "Construction" },
  { sym: "TATASTEEL23", name: "Tata Steel Industrial Gases", sec: "Materials" },
  { sym: "TATASTEEL24", name: "Tata Steel Agrico Ltd", sec: "Industrial" },
  { sym: "TATASTEEL25", name: "Tata Steel Processing & Distribution", sec: "Steel" },
  { sym: "TATASTEEL26", name: "Tata Steel International", sec: "Steel" },
  { sym: "TATASTEEL27", name: "Tata Steel Logistics", sec: "Logistics" },
  { sym: "TATASTEEL28", name: "Tata Steel Distribution", sec: "Logistics" },
  { sym: "TATASTEEL29", name: "Tata Steel Advanced Materials", sec: "Materials" },
  { sym: "TATASTEEL30", name: "Tata Steel Industrial Services", sec: "Industrial" },
  { sym: "TATASTEEL31", name: "Tata Steel Construction", sec: "Construction" },
  { sym: "TATASTEEL32", name: "Tata Steel Mining Ltd", sec: "Mining" },
  { sym: "TATASTEEL33", name: "Tata Steel Utilities", sec: "Utilities" },
  { sym: "TATASTEEL34", name: "Tata Steel Downstream", sec: "Steel" },
  { sym: "TATASTEEL35", name: "Tata Steel Long Products", sec: "Steel" },
  { sym: "TATASTEEL36", name: "Tata Steel BSL Ltd", sec: "Steel" },
  { sym: "TATASTEEL37", name: "Tata Steel Ltd", sec: "Steel" },
  { sym: "ADANI30", name: "Adani Enterprises Ltd", sec: "Industrial" },
  { sym: "ADANI31", name: "Adani Ports & SEZ Ltd", sec: "Logistics" },
  { sym: "ADANI32", name: "Adani Power Ltd", sec: "Utilities" },
  { sym: "ADANI33", name: "Adani Green Energy Ltd", sec: "RenewableEnergy" },
  { sym: "ADANI34", name: "Adani Transmission Ltd", sec: "Utilities" },
  { sym: "ADANI35", name: "Adani Total Gas Ltd", sec: "Energy" },
  { sym: "ADANI36", name: "Adani Wilmar Ltd", sec: "Food" },
  { sym: "ADANI37", name: "Adani Cement Ltd", sec: "Construction" },
  { sym: "ADANI38", name: "Adani Airport Holdings", sec: "Travel" },
  { sym: "ADANI39", name: "Adani Road Transport Ltd", sec: "Logistics" },
  { sym: "ADANI40", name: "Adani Electricity Mumbai", sec: "Utilities" },
  { sym: "ADANI41", name: "Adani New Industries Ltd", sec: "RenewableEnergy" },
  { sym: "ADANI42", name: "Adani Data Network Ltd", sec: "Telecom" },
  { sym: "ADANI43", name: "Adani Concessions Ltd", sec: "Logistics" },
  { sym: "ADANI44", name: "Adani Petrochemicals Ltd", sec: "Chemicals" },
  { sym: "ADANI45", name: "Adani Mining Ltd", sec: "Mining" },
  { sym: "ADANI46", name: "Adani Solar Ltd", sec: "RenewableEnergy" },
  { sym: "ADANI47", name: "Adani Defence Systems & Tech", sec: "Defense" },
  { sym: "ADANI48", name: "Adani Aerospace Industries", sec: "Aerospace" },
  { sym: "ADANI49", name: "Adani Digital Labs Pvt Ltd", sec: "Technology" },
  { sym: "ADANI50", name: "Adani HealthTech Pvt Ltd", sec: "Healthcare" },
  { sym: "ADANI51", name: "Adani Realty Pvt Ltd", sec: "RealEstate" },
  { sym: "ADANI52", name: "Adani Water Solutions Ltd", sec: "Utilities" },
  { sym: "ADANI53", name: "Adani Waste Management", sec: "Industrial" },
  { sym: "ADANI54", name: "Adani Shipping Services", sec: "Logistics" },
  { sym: "ADANI55", name: "Adani Rail Transport Ltd", sec: "Logistics" },
  { sym: "ADANI56", name: "Adani City Gas Distribution", sec: "Energy" },
  { sym: "ADANI57", name: "Adani Bio Energy Ltd", sec: "RenewableEnergy" },
  { sym: "ADANI58", name: "Adani LNG Ltd", sec: "Energy" },
  { sym: "ADANI59", name: "Adani Copper Ltd", sec: "Mining" },
  { sym: "ADANI60", name: "Adani Aluminium Ltd", sec: "Mining" },
  { sym: "BIRLA30", name: "Aditya Birla Group Holdings", sec: "Finance" },
  { sym: "BIRLA31", name: "Grasim Industries Ltd", sec: "Materials" },
  { sym: "BIRLA32", name: "UltraTech Cement Ltd", sec: "Construction" },
  { sym: "BIRLA33", name: "Hindalco Industries Ltd", sec: "Materials" },
  { sym: "BIRLA34", name: "Novelis Inc (Hindalco)", sec: "Materials" },
  { sym: "BIRLA35", name: "Aditya Birla Capital Ltd", sec: "Finance" },
  { sym: "BIRLA36", name: "Aditya Birla Fashion Retail", sec: "Retail" },
  { sym: "BIRLA37", name: "Vodafone Idea Ltd", sec: "Telecom" },
  { sym: "BIRLA38", name: "Aditya Birla Sun Life Insurance", sec: "Finance" },
  { sym: "BIRLA39", name: "Pilani Investment & Industries", sec: "Finance" },
  { sym: "BIRLA40", name: "Century Textiles & Industries", sec: "Textiles" },
  { sym: "BIRLA41", name: "Century Enka Ltd", sec: "Textiles" },
  { sym: "BIRLA42", name: "Indian Rayon Ltd", sec: "Textiles" },
  { sym: "BIRLA43", name: "Jay Shree Tea & Industries", sec: "Food" },
  { sym: "BIRLA44", name: "Aditya Birla Chemicals", sec: "Chemicals" },
  { sym: "BIRLA45", name: "Aditya Birla Insulators", sec: "Industrial" },
  { sym: "BIRLA46", name: "Tanfac Industries Ltd", sec: "Chemicals" },
  { sym: "BIRLA47", name: "Ultratech Ceylon Pvt Ltd", sec: "Construction" },
  { sym: "BIRLA48", name: "Aditya Birla Money Ltd", sec: "Fintech" },
  { sym: "BIRLA49", name: "Aditya Birla Housing Finance", sec: "Finance" },
  { sym: "BIRLA50", name: "Birla Cable Ltd", sec: "Industrial" },
  { sym: "BIRLA51", name: "Birla Corporation Ltd", sec: "Construction" },
  { sym: "BIRLA52", name: "Birla Cellulose (Grasim)", sec: "Textiles" },
  { sym: "BIRLA53", name: "Birla Carbon India Pvt Ltd", sec: "Industrial" },
  { sym: "BIRLA54", name: "Aditya Birla Retail Ltd", sec: "Retail" },
  { sym: "BIRLA55", name: "Aditya Birla Minacs IT Services", sec: "Technology" },
  { sym: "BIRLA56", name: "Idea Cellular Ltd", sec: "Telecom" },
  { sym: "BIRLA57", name: "Aditya Birla Minerals Ltd", sec: "Mining" },
  { sym: "BIRLA58", name: "Aditya Birla Real Estate", sec: "RealEstate" },
  { sym: "BIRLA59", name: "Aditya Birla Health Insurance", sec: "Finance" },
  { sym: "BIRLA60", name: "Aditya Birla Telecom Ltd", sec: "Telecom" },
  { sym: "TATA30", name: "Tata Sons Pvt Ltd", sec: "Finance" },
  { sym: "TATA31", name: "Tata Industries Ltd", sec: "Industrial" },
  { sym: "TATA32", name: "Tata Chemicals Ltd", sec: "Chemicals" },
  { sym: "TATA33", name: "Tata Global Beverages Ltd", sec: "Food" },
  { sym: "TATA34", name: "Tata Coffee Ltd", sec: "Food" },
  { sym: "TATA35", name: "Tata Investment Corp Ltd", sec: "Finance" },
  { sym: "TATA36", name: "Tata Autocomp Systems Ltd", sec: "Automotive" },
  { sym: "TATA37", name: "Tata Business Support Services", sec: "Technology" },
  { sym: "TATA38", name: "Tata Advanced Systems Ltd", sec: "Defense" },
  { sym: "TATA39", name: "Tata SIA Airlines (Vistara)", sec: "Travel" },
  { sym: "TATA40", name: "Tata Starbucks Pvt Ltd", sec: "Food" },
  { sym: "TATA41", name: "Tata Trent Ltd", sec: "Retail" },
  { sym: "TATA42", name: "Tata Sky Ltd (Tata Play)", sec: "Media" },
  { sym: "TATA43", name: "Tata AIA Life Insurance", sec: "Finance" },
  { sym: "TATA44", name: "Tata Asset Management Ltd", sec: "Finance" },
  { sym: "TATA45", name: "Tata Securities Ltd", sec: "Finance" },
  { sym: "TATA46", name: "Tata Digital Ltd", sec: "ECommerce" },
  { sym: "TATA47", name: "Tata Neu (Tata Digital)", sec: "ECommerce" },
  { sym: "TATA48", name: "BigBasket (Tata)", sec: "ECommerce" },
  { sym: "TATA49", name: "1mg (Tata Digital)", sec: "Healthcare" },
  { sym: "TATA50", name: "Croma (Infiniti Retail)", sec: "Retail" },
  { sym: "TATA51", name: "Tata CLiQ (Tata Unistore)", sec: "ECommerce" },
  { sym: "TATA52", name: "Tata Housing Development Co", sec: "RealEstate" },
  { sym: "TATA53", name: "Tata Realty & Infrastructure", sec: "RealEstate" },
  { sym: "TATA54", name: "Tata Quality Management Services", sec: "Industrial" },
  { sym: "TATA55", name: "Tata Strategic Management Group", sec: "Industrial" },
  { sym: "TATA56", name: "Tata Interactive Systems", sec: "Technology" },
  { sym: "TATA57", name: "Tata Consultancy Services Japan", sec: "Technology" },
  { sym: "TATA58", name: "Tata Consultancy Services Europe", sec: "Technology" },
  { sym: "TATA59", name: "Tata Consultancy Services USA", sec: "Technology" },
  { sym: "TATA60", name: "Tata Consultancy Services APAC", sec: "Technology" },
  { sym: "TATA61", name: "Tata Consultancy Services MEA", sec: "Technology" },
  { sym: "TATA62", name: "Tata Consultancy Services ANZ", sec: "Technology" },
  { sym: "TATA63", name: "Tata Consultancy Services LATAM", sec: "Technology" },
  { sym: "TATA64", name: "Tata Consultancy Services Canada", sec: "Technology" },
  { sym: "TATA65", name: "Tata Consultancy Services UK", sec: "Technology" },
  { sym: "TATA66", name: "Tata Consultancy Services Ireland", sec: "Technology" },
  { sym: "TATA67", name: "Tata Consultancy Services China", sec: "Technology" },
  { sym: "TATA68", name: "Tata Consultancy Services India", sec: "Technology" },
  { sym: "TATA69", name: "Tata Consultancy Services Digital", sec: "Technology" },
  { sym: "TATA70", name: "Tata Consultancy Services BFSI", sec: "Finance" },
  { sym: "TATA71", name: "Tata Consultancy Services Healthcare", sec: "Healthcare" },
  { sym: "TATA72", name: "Tata Consultancy Services Retail", sec: "Retail" },
  { sym: "TATA73", name: "Tata Consultancy Services Mfg", sec: "Industrial" },
  { sym: "TATA74", name: "Tata Consultancy Services Energy", sec: "Energy" },
  { sym: "TATA75", name: "Tata Consultancy Services Telecom", sec: "Telecom" },
  { sym: "TATA76", name: "Tata Consultancy Services Insurance", sec: "Finance" },
  { sym: "TATA77", name: "Tata Consultancy Services Life Sciences", sec: "Healthcare" },
  { sym: "TATA78", name: "Tata Consultancy Services Media", sec: "Media" },
  { sym: "TATA79", name: "Tata Consultancy Services Travel", sec: "Travel" },
  { sym: "TATA80", name: "Tata Consultancy Services Public Sector", sec: "Industrial" },
  { sym: "TATA81", name: "Tata Consultancy Services Education", sec: "EdTech" },
  { sym: "TATA82", name: "Tata Consultancy Services Logistics", sec: "Logistics" },
  { sym: "TATA83", name: "Tata Consultancy Services Aerospace", sec: "Aerospace" },
  { sym: "TATA84", name: "Tata Consultancy Services Defense", sec: "Defense" },
  { sym: "TATA85", name: "Tata Consultancy Services AgriTech", sec: "AgriTech" },
  { sym: "TATA86", name: "Tata Consultancy Services Gaming", sec: "Gaming" },
  { sym: "TATA87", name: "Tata Consultancy Services Space", sec: "SpaceTech" },
  { sym: "TATA88", name: "Tata Consultancy Services Quantum", sec: "QuantumComputing" },
  { sym: "TATA89", name: "Tata Consultancy Services Cloud", sec: "CloudComputing" },
  { sym: "TATA90", name: "Tata Consultancy Services Cyber", sec: "Cybersecurity" },
  { sym: "TATA91", name: "Tata Consultancy Services AI", sec: "AI" },
  { sym: "TATA92", name: "Tata Consultancy Services Robotics", sec: "Robotics" },
  { sym: "TATA93", name: "Tata Consultancy Services EV", sec: "EV" },
  { sym: "TATA94", name: "Tata Consultancy Services Renewable", sec: "RenewableEnergy" },
  { sym: "TATA95", name: "Tata Consultancy Services Fintech", sec: "Fintech" },
  { sym: "TATA96", name: "Tata Consultancy Services Biotech", sec: "Biotech" },
  { sym: "TATA97", name: "Tata Consultancy Services Semicon", sec: "Semiconductors" },
  { sym: "TATA98", name: "Tata Consultancy Services ECommerce", sec: "ECommerce" },
  { sym: "TATA99", name: "Tata Consultancy Services Pharma", sec: "Pharma" },
  { sym: "TATA100", name: "Tata Consultancy Services Construction", sec: "Construction" },
  { sym: "TATA101", name: "Tata Consultancy Services Mining", sec: "Mining" },
  { sym: "TATA102", name: "Tata Consultancy Services Steel", sec: "Steel" },
  { sym: "TATA103", name: "Tata Consultancy Services Textiles", sec: "Textiles" },
  { sym: "TATA104", name: "Tata Consultancy Services Food", sec: "Food" },
  { sym: "TATA105", name: "Tata Consultancy Services Automotive", sec: "Automotive" },
  { sym: "TATA106", name: "Tata Consultancy Services Materials", sec: "Materials" },
  { sym: "TATA107", name: "Tata Consultancy Services Utilities", sec: "Utilities" },
  { sym: "TATA108", name: "Tata Consultancy Services RealEstate", sec: "RealEstate" },
  { sym: "TATA109", name: "Tata Consultancy Services Communication", sec: "Communication" },
  { sym: "TATA110", name: "Tata Consultancy Services Chemicals", sec: "Chemicals" },
  { sym: "RELIANCE30", name: "Reliance Industries Ltd", sec: "Energy" },
  { sym: "RELIANCE31", name: "Reliance Retail Ventures Ltd", sec: "Retail" },
  { sym: "RELIANCE32", name: "Reliance Jio Infocomm Ltd", sec: "Telecom" },
  { sym: "RELIANCE33", name: "Reliance Digital Retail Ltd", sec: "Retail" },
  { sym: "RELIANCE34", name: "Jio Platforms Ltd", sec: "Technology" },
  { sym: "RELIANCE35", name: "JioMart (Jio Platforms)", sec: "ECommerce" },
  { sym: "RELIANCE36", name: "Ajio (Reliance Retail)", sec: "ECommerce" },
  { sym: "RELIANCE37", name: "Reliance Trends (Retail)", sec: "Retail" },
  { sym: "RELIANCE38", name: "Reliance Fresh (Retail)", sec: "Retail" },
  { sym: "RELIANCE39", name: "Reliance Smart (Retail)", sec: "Retail" },
  { sym: "RELIANCE40", name: "Reliance Project Mgmt", sec: "Industrial" },
  { sym: "RELIANCE41", name: "Reliance Petroleum Corp", sec: "Energy" },
  { sym: "RELIANCE42", name: "Reliance Power Ltd", sec: "Utilities" },
  { sym: "RELIANCE43", name: "Reliance Infrastructure", sec: "Industrial" },
  { sym: "RELIANCE44", name: "Reliance Communications", sec: "Telecom" },
  { sym: "RELIANCE45", name: "Reliance Natural Resources", sec: "Energy" },
  { sym: "RELIANCE46", name: "Reliance Health Insurance", sec: "Finance" },
  { sym: "RELIANCE47", name: "Reliance General Insurance", sec: "Finance" },
  { sym: "RELIANCE48", name: "Reliance Life Insurance", sec: "Finance" },
  { sym: "RELIANCE49", name: "Reliance Capital Ltd", sec: "Finance" },
  { sym: "RELIANCE50", name: "Reliance Mutual Fund", sec: "Finance" },
  { sym: "RELIANCE51", name: "Reliance Securities Ltd", sec: "Fintech" },
  { sym: "RELIANCE52", name: "Reliance Money Ltd", sec: "Fintech" },
  { sym: "RELIANCE53", name: "Reliance Anek Plan", sec: "Fintech" },
  { sym: "RELIANCE54", name: "Reliance Wealth Mgmt", sec: "Finance" },
  { sym: "RELIANCE55", name: "Reliance Asset Reconstruction", sec: "Finance" },
  { sym: "RELIANCE56", name: "Reliance Commercial Finance", sec: "Finance" },
  { sym: "RELIANCE57", name: "Reliance Home Finance", sec: "Finance" },
  { sym: "RELIANCE58", name: "Reliance Energy Ltd", sec: "Utilities" },
  { sym: "RELIANCE59", name: "Reliance Infrastructure Ltd", sec: "Industrial" },
  { sym: "RELIANCE60", name: "Reliance Naval Engineering", sec: "Defense" },
  { sym: "RELIANCE61", name: "Reliance Defence & Aerospace", sec: "Defense" },
  { sym: "RELIANCE62", name: "Reliance Aerostructures", sec: "Aerospace" },
  { sym: "RELIANCE63", name: "Reliance Land Systems", sec: "Defense" },
  { sym: "RELIANCE64", name: "Reliance Naval Systems", sec: "Defense" },
  { sym: "RELIANCE65", name: "Reliance Security Solutions", sec: "Cybersecurity" },
  { sym: "RELIANCE66", name: "Reliance Jio Payments Bank", sec: "Fintech" },
  { sym: "RELIANCE67", name: "Reliance Jio Health Services", sec: "Healthcare" },
  { sym: "RELIANCE68", name: "Reliance Jio Educational", sec: "EdTech" },
  { sym: "RELIANCE69", name: "Reliance Jio GigaFiber", sec: "Telecom" },
  { sym: "RELIANCE70", name: "Reliance Jio Set-Top Box", sec: "Media" },
  { sym: "RELIANCE71", name: "Reliance Jio Phone", sec: "Technology" },
  { sym: "RELIANCE72", name: "Reliance Jio Apps", sec: "Technology" },
  { sym: "RELIANCE73", name: "Reliance Jio Cloud", sec: "CloudComputing" },
  { sym: "RELIANCE74", name: "Reliance Jio AI", sec: "AI" },
  { sym: "RELIANCE75", name: "Reliance Jio IoT", sec: "Technology" },
  { sym: "RELIANCE76", name: "Reliance Jio 5G", sec: "Telecom" },
  { sym: "RELIANCE77", name: "Reliance Jio 6G", sec: "Telecom" },
  { sym: "RELIANCE78", name: "Reliance Jio Satellite", sec: "SpaceTech" },
  { sym: "RELIANCE79", name: "Reliance Jio Quantum", sec: "QuantumComputing" },
  { sym: "RELIANCE80", name: "Reliance Jio Robotics", sec: "Robotics" },
  { sym: "RELIANCE81", name: "Reliance Jio EV", sec: "EV" },
  { sym: "RELIANCE82", name: "Reliance Jio Renewable", sec: "RenewableEnergy" },
  { sym: "RELIANCE83", name: "Reliance Jio Fintech", sec: "Fintech" },
  { sym: "RELIANCE84", name: "Reliance Jio Biotech", sec: "Biotech" },
  { sym: "RELIANCE85", name: "Reliance Jio Semicon", sec: "Semiconductors" },
  { sym: "RELIANCE86", name: "Reliance Jio Cyber", sec: "Cybersecurity" },
  { sym: "RELIANCE87", name: "Reliance Jio Gaming", sec: "Gaming" },
  { sym: "RELIANCE88", name: "Reliance Jio Media", sec: "Media" },
  { sym: "RELIANCE89", name: "Reliance Jio Travel", sec: "Travel" },
  { sym: "RELIANCE90", name: "Reliance Jio Logistics", sec: "Logistics" },
  { sym: "RELIANCE91", name: "Reliance Jio Food", sec: "Food" },
  { sym: "RELIANCE92", name: "Reliance Jio Pharma", sec: "Pharma" },
  { sym: "RELIANCE93", name: "Reliance Jio Chemicals", sec: "Chemicals" },
  { sym: "RELIANCE94", name: "Reliance Jio Construction", sec: "Construction" },
  { sym: "RELIANCE95", name: "Reliance Jio Mining", sec: "Mining" },
  { sym: "RELIANCE96", name: "Reliance Jio Steel", sec: "Steel" },
  { sym: "RELIANCE97", name: "Reliance Jio Textiles", sec: "Textiles" },
  { sym: "RELIANCE98", name: "Reliance Jio Automotive", sec: "Automotive" },
  { sym: "RELIANCE99", name: "Reliance Jio Materials", sec: "Materials" },
  { sym: "RELIANCE100", name: "Reliance Jio Utilities", sec: "Utilities" },
  { sym: "RELIANCE101", name: "Reliance Jio RealEstate", sec: "RealEstate" },
  { sym: "RELIANCE102", name: "Reliance Jio Communication", sec: "Communication" },
  { sym: "RELIANCE103", name: "Reliance Jio AgriTech", sec: "AgriTech" },
  { sym: "RELIANCE104", name: "Reliance Jio EdTech", sec: "EdTech" },
  { sym: "RELIANCE105", name: "Reliance Jio SpaceTech", sec: "SpaceTech" },
  { sym: "RELIANCE106", name: "Reliance Jio Defense", sec: "Defense" },
  { sym: "RELIANCE107", name: "Reliance Jio Aerospace", sec: "Aerospace" },
  { sym: "RELIANCE108", name: "Reliance Jio Cloud Gaming", sec: "Gaming" },
  { sym: "RELIANCE109", name: "Reliance Jio HealthTech", sec: "Healthcare" },
  { sym: "RELIANCE110", name: "Reliance Jio FinTech Hub", sec: "Fintech" },
  { sym: "JINDAL30", name: "Jindal Steel & Power Ltd", sec: "Steel" },
  { sym: "JINDAL31", name: "Jindal Stainless Ltd", sec: "Steel" },
  { sym: "JINDAL32", name: "Jindal Stainless Hisar Ltd", sec: "Steel" },
  { sym: "JINDAL33", name: "Jindal Saw Ltd", sec: "Steel" },
  { sym: "JINDAL34", name: "Jindal Poly Films Ltd", sec: "Materials" },
  { sym: "JINDAL35", name: "Jindal Photo Ltd", sec: "Materials" },
  { sym: "JINDAL36", name: "Jindal Drugs Ltd", sec: "Pharma" },
  { sym: "JINDAL37", name: "Jindal Power Ltd", sec: "Utilities" },
  { sym: "JINDAL38", name: "Jindal Cement Ltd", sec: "Construction" },
  { sym: "JINDAL39", name: "Jindal Iron & Steel Co", sec: "Steel" },
  { sym: "JINDAL40", name: "Jindal Vijayanagar Steel", sec: "Steel" },
  { sym: "JINDAL41", name: "Jindal Praxair Oxygen Co", sec: "Industrial" },
  { sym: "JINDAL42", name: "Jindal Steel Alloys Ltd", sec: "Steel" },
  { sym: "JINDAL43", name: "Jindal Thermal Power Co", sec: "Utilities" },
  { sym: "JINDAL44", name: "Jindal Petroleum Ltd", sec: "Energy" },
  { sym: "JINDAL45", name: "Jindal Mining Pvt Ltd", sec: "Mining" },
  { sym: "JINDAL46", name: "Jindal Real Estate Ltd", sec: "RealEstate" },
  { sym: "JINDAL47", name: "Jindal Logistics Ltd", sec: "Logistics" },
  { sym: "JINDAL48", name: "Jindal Construction Ltd", sec: "Construction" },
  { sym: "JINDAL49", name: "Jindal Automotive Ltd", sec: "Automotive" },
  { sym: "JINDAL50", name: "Jindal Textiles Ltd", sec: "Textiles" },
  { sym: "JINDAL51", name: "Jindal Chemicals Ltd", sec: "Chemicals" },
  { sym: "JINDAL52", name: "Jindal Food Products Ltd", sec: "Food" },
  { sym: "JINDAL53", name: "Jindal Telecom Ltd", sec: "Telecom" },
  { sym: "JINDAL54", name: "Jindal Technology Ltd", sec: "Technology" },
  { sym: "JINDAL55", name: "Jindal Healthcare Ltd", sec: "Healthcare" },
  { sym: "JINDAL56", name: "Jindal Pharma Ltd", sec: "Pharma" },
  { sym: "JINDAL57", name: "Jindal Biotech Ltd", sec: "Biotech" },
  { sym: "JINDAL58", name: "Jindal Semiconductors Ltd", sec: "Semiconductors" },
  { sym: "JINDAL59", name: "Jindal EV Ltd", sec: "EV" },
  { sym: "JINDAL60", name: "Jindal Renewable Energy Ltd", sec: "RenewableEnergy" },
  { sym: "JINDAL61", name: "Jindal Fintech Ltd", sec: "Fintech" },
  { sym: "JINDAL62", name: "Jindal Cloud Computing Ltd", sec: "CloudComputing" },
  { sym: "JINDAL63", name: "Jindal Cybersecurity Ltd", sec: "Cybersecurity" },
  { sym: "JINDAL64", name: "Jindal Quantum Computing", sec: "QuantumComputing" },
  { sym: "JINDAL65", name: "Jindal Robotics Ltd", sec: "Robotics" },
  { sym: "JINDAL66", name: "Jindal AI Ltd", sec: "AI" },
  { sym: "JINDAL67", name: "Jindal SpaceTech Ltd", sec: "SpaceTech" },
  { sym: "JINDAL68", name: "Jindal AgriTech Ltd", sec: "AgriTech" },
  { sym: "JINDAL69", name: "Jindal EdTech Ltd", sec: "EdTech" },
  { sym: "JINDAL70", name: "Jindal Gaming Ltd", sec: "Gaming" },
  { sym: "JINDAL71", name: "Jindal Media Ltd", sec: "Media" },
  { sym: "JINDAL72", name: "Jindal Travel Ltd", sec: "Travel" },
  { sym: "JINDAL73", name: "Jindal Defense Ltd", sec: "Defense" },
  { sym: "JINDAL74", name: "Jindal Aerospace Ltd", sec: "Aerospace" },
  { sym: "JINDAL75", name: "Jindal ECommerce Ltd", sec: "ECommerce" },
  { sym: "JINDAL76", name: "Jindal Retail Ltd", sec: "Retail" },
  { sym: "JINDAL77", name: "Jindal Finance Ltd", sec: "Finance" },
  { sym: "JINDAL78", name: "Jindal Industrial Ltd", sec: "Industrial" },
  { sym: "JINDAL79", name: "Jindal Materials Ltd", sec: "Materials" },
  { sym: "JINDAL80", name: "Jindal Utilities Ltd", sec: "Utilities" },
  { sym: "JINDAL81", name: "Jindal RealEstate Ltd", sec: "RealEstate" },
  { sym: "JINDAL82", name: "Jindal Communication Ltd", sec: "Communication" },
  { sym: "JINDAL83", name: "Jindal Consumer Ltd", sec: "Consumer" },
  { sym: "JINDAL84", name: "Jindal Energy Ltd", sec: "Energy" },
  { sym: "JINDAL85", name: "Jindal Oil & Gas Ltd", sec: "Energy" },
  { sym: "JINDAL86", name: "Jindal Power Generation Ltd", sec: "Utilities" },
  { sym: "JINDAL87", name: "Jindal Steel Distribution Ltd", sec: "Logistics" },
  { sym: "JINDAL88", name: "Jindal Steel International Ltd", sec: "Steel" },
  { sym: "JINDAL89", name: "Jindal Steel Processing Ltd", sec: "Steel" },
  { sym: "JINDAL90", name: "Jindal Steel Bearings Ltd", sec: "Industrial" },
  { sym: "JINDAL91", name: "Jindal Steel Wire Ltd", sec: "Steel" },
  { sym: "JINDAL92", name: "Jindal Steel Tubes Ltd", sec: "Steel" },
  { sym: "JINDAL93", name: "Jindal Steel Construction Ltd", sec: "Construction" },
  { sym: "JINDAL94", name: "Jindal Steel Mining Ltd", sec: "Mining" },
  { sym: "JINDAL95", name: "Jindal Steel Advanced Materials", sec: "Materials" },
  { sym: "JINDAL96", name: "Jindal Steel Industrial Services", sec: "Industrial" },
  { sym: "JINDAL97", name: "Jindal Steel Logistics Ltd", sec: "Logistics" },
  { sym: "JINDAL98", name: "Jindal Steel Distribution Network", sec: "Logistics" },
  { sym: "JINDAL99", name: "Jindal Steel International Trading", sec: "Steel" },
  { sym: "JINDAL100", name: "Jindal Steel Processing & Distribution", sec: "Steel" },
  { sym: "JSW30", name: "JSW Steel Ltd", sec: "Steel" },
  { sym: "JSW31", name: "JSW Energy Ltd", sec: "Utilities" },
  { sym: "JSW32", name: "JSW Infrastructure Ltd", sec: "Industrial" },
  { sym: "JSW33", name: "JSW Hydro Energy Ltd", sec: "Utilities" },
  { sym: "JSW34", name: "JSW Cement Ltd", sec: "Construction" },
  { sym: "JSW35", name: "JSW Paints Ltd", sec: "Materials" },
  { sym: "JSW36", name: "JSW Steel Coated Products", sec: "Steel" },
  { sym: "JSW37", name: "JSW Steel BSL Ltd", sec: "Steel" },
  { sym: "JSW38", name: "JSW Steel USA Corp", sec: "Steel" },
  { sym: "JSW39", name: "JSW Steel Italy", sec: "Steel" },
  { sym: "JSW40", name: "JSW Steel UK Ltd", sec: "Steel" },
  { sym: "JSW41", name: "JSW Steel Australia", sec: "Steel" },
  { sym: "JSW42", name: "JSW Steel Chile", sec: "Steel" },
  { sym: "JSW43", name: "JSW Steel Brazil", sec: "Steel" },
  { sym: "JSW44", name: "JSW Steel South Africa", sec: "Steel" },
  { sym: "JSW45", name: "JSW Steel UAE", sec: "Steel" },
  { sym: "JSW46", name: "JSW Steel Oman", sec: "Steel" },
  { sym: "JSW47", name: "JSW Steel Qatar", sec: "Steel" },
  { sym: "JSW48", name: "JSW Steel Saudi Arabia", sec: "Steel" },
  { sym: "JSW49", name: "JSW Steel Kuwait", sec: "Steel" },
  { sym: "JSW50", name: "JSW Steel Bahrain", sec: "Steel" },
  { sym: "JSW51", name: "JSW Steel Egypt", sec: "Steel" },
  { sym: "JSW52", name: "JSW Steel Morocco", sec: "Steel" },
  { sym: "JSW53", name: "JSW Steel Algeria", sec: "Steel" },
  { sym: "JSW54", name: "JSW Steel Libya", sec: "Steel" },
  { sym: "JSW55", name: "JSW Steel Sudan", sec: "Steel" },
  { sym: "JSW56", name: "JSW Steel Tunisia", sec: "Steel" },
  { sym: "JSW57", name: "JSW Steel Kenya", sec: "Steel" },
  { sym: "JSW58", name: "JSW Steel Nigeria", sec: "Steel" },
  { sym: "JSW59", name: "JSW Steel Ghana", sec: "Steel" },
  { sym: "JSW60", name: "JSW Steel Ethiopia", sec: "Steel" },
  { sym: "JSW61", name: "JSW Steel Tanzania", sec: "Steel" },
  { sym: "JSW62", name: "JSW Steel Uganda", sec: "Steel" },
  { sym: "JSW63", name: "JSW Steel Zimbabwe", sec: "Steel" },
  { sym: "JSW64", name: "JSW Steel Zambia", sec: "Steel" },
  { sym: "JSW65", name: "JSW Steel Botswana", sec: "Steel" },
  { sym: "JSW66", name: "JSW Steel Namibia", sec: "Steel" },
  { sym: "JSW67", name: "JSW Steel Mozambique", sec: "Steel" },
  { sym: "JSW68", name: "JSW Steel Angola", sec: "Steel" },
  { sym: "JSW69", name: "JSW Steel Cameroon", sec: "Steel" },
  { sym: "JSW70", name: "JSW Steel Senegal", sec: "Steel" },
  { sym: "JSW71", name: "JSW Steel Mali", sec: "Steel" },
  { sym: "JSW72", name: "JSW Steel Congo", sec: "Steel" },
  { sym: "JSW73", name: "JSW Steel Rwanda", sec: "Steel" },
  { sym: "JSW74", name: "JSW Steel Burundi", sec: "Steel" },
  { sym: "JSW75", name: "JSW Steel Somalia", sec: "Steel" },
  { sym: "JSW76", name: "JSW Steel Djibouti", sec: "Steel" },
  { sym: "JSW77", name: "JSW Steel Eritrea", sec: "Steel" },
  { sym: "JSW78", name: "JSW Steel Niger", sec: "Steel" },
  { sym: "JSW79", name: "JSW Steel Chad", sec: "Steel" },
  { sym: "JSW80", name: "JSW Steel Mauritania", sec: "Steel" },
  { sym: "JSW81", name: "JSW Steel Mali", sec: "Steel" },
  { sym: "JSW82", name: "JSW Steel Burkina Faso", sec: "Steel" },
  { sym: "JSW83", name: "JSW Steel Sierra Leone", sec: "Steel" },
  { sym: "JSW84", name: "JSW Steel Liberia", sec: "Steel" },
  { sym: "JSW85", name: "JSW Steel Togo", sec: "Steel" },
  { sym: "JSW86", name: "JSW Steel Benin", sec: "Steel" },
  { sym: "JSW87", name: "JSW Steel Guinea", sec: "Steel" },
  { sym: "JSW88", name: "JSW Steel Ivory Coast", sec: "Steel" },
  { sym: "JSW89", name: "JSW Steel Gabon", sec: "Steel" },
  { sym: "JSW90", name: "JSW Steel Congo (Brazzaville)", sec: "Steel" },
  { sym: "JSW91", name: "JSW Steel CAR", sec: "Steel" },
  { sym: "JSW92", name: "JSW Steel Equatorial Guinea", sec: "Steel" },
  { sym: "JSW93", name: "JSW Steel Madagascar", sec: "Steel" },
  { sym: "JSW94", name: "JSW Steel Mauritius", sec: "Steel" },
  { sym: "JSW95", name: "JSW Steel Comoros", sec: "Steel" },
  { sym: "JSW96", name: "JSW Steel Seychelles", sec: "Steel" },
  { sym: "JSW97", name: "JSW Steel Cape Verde", sec: "Steel" },
  { sym: "JSW98", name: "JSW Steel Sao Tome", sec: "Steel" },
  { sym: "JSW99", name: "JSW Steel Gambia", sec: "Steel" },
  { sym: "JSW100", name: "JSW Steel Guinea-Bissau", sec: "Steel" },
  { sym: "VEDANTA30", name: "Vedanta Ltd", sec: "Mining" },
  { sym: "VEDANTA31", name: "Vedanta Aluminium Ltd", sec: "Materials" },
  { sym: "VEDANTA32", name: "Vedanta Zinc International", sec: "Mining" },
  { sym: "VEDANTA33", name: "Vedanta Copper International", sec: "Mining" },
  { sym: "VEDANTA34", name: "Vedanta Iron & Steel", sec: "Steel" },
  { sym: "VEDANTA35", name: "Vedanta Oil & Gas", sec: "Energy" },
  { sym: "VEDANTA36", name: "Vedanta Power", sec: "Utilities" },
  { sym: "VEDANTA37", name: "Vedanta Cairn Oil & Gas", sec: "Energy" },
  { sym: "VEDANTA38", name: "Vedanta Hindustan Zinc", sec: "Mining" },
  { sym: "VEDANTA39", name: "Vedanta Sesa Goa Iron Ore", sec: "Mining" },
  { sym: "VEDANTA40", name: "Vedanta Talwandi Sabo Power", sec: "Utilities" },
  { sym: "VEDANTA41", name: "Vedanta Bharat Aluminium Co", sec: "Materials" },
  { sym: "VEDANTA42", name: "Vedanta Sterlite Copper", sec: "Mining" },
  { sym: "VEDANTA43", name: "Vedanta Madras Aluminium", sec: "Materials" },
  { sym: "VEDANTA44", name: "Vedanta Western Cluster", sec: "Mining" },
  { sym: "VEDANTA45", name: "Vedanta Konkola Copper Mines", sec: "Mining" },
  { sym: "VEDANTA46", name: "Vedanta Skorpion Zinc", sec: "Mining" },
  { sym: "VEDANTA47", name: "Vedanta Lisheen Mining", sec: "Mining" },
  { sym: "VEDANTA48", name: "Vedanta Black Mountain Mining", sec: "Mining" },
  { sym: "VEDANTA49", name: "Vedanta Gamsberg Zinc", sec: "Mining" },
  { sym: "VEDANTA50", name: "Vedanta Cairn Energy India", sec: "Energy" },
  { sym: "VEDANTA51", name: "Vedanta Ravva Oil & Gas", sec: "Energy" },
  { sym: "VEDANTA52", name: "Vedanta Suvali Power", sec: "Utilities" },
  { sym: "VEDANTA53", name: "Vedanta Lanjigarh Alumina", sec: "Materials" },
  { sym: "VEDANTA54", name: "Vedanta Jharsuguda Aluminium", sec: "Materials" },
  { sym: "VEDANTA55", name: "Vedanta Korba Aluminium", sec: "Materials" },
  { sym: "VEDANTA56", name: "Vedanta Chhattisgarh Power", sec: "Utilities" },
  { sym: "VEDANTA57", name: "Vedanta Punjab Power", sec: "Utilities" },
  { sym: "VEDANTA58", name: "Vedanta Karnataka Power", sec: "Utilities" },
  { sym: "VEDANTA59", name: "Vedanta Goa Power", sec: "Utilities" },
  { sym: "VEDANTA60", name: "Vedanta Tamil Nadu Power", sec: "Utilities" },
  { sym: "VEDANTA61", name: "Vedanta Odisha Power", sec: "Utilities" },
  { sym: "VEDANTA62", name: "Vedanta Jharkhand Power", sec: "Utilities" },
  { sym: "VEDANTA63", name: "Vedanta Rajasthan Power", sec: "Utilities" },
  { sym: "VEDANTA64", name: "Vedanta Gujarat Power", sec: "Utilities" },
  { sym: "VEDANTA65", name: "Vedanta Maharashtra Power", sec: "Utilities" },
  { sym: "VEDANTA66", name: "Vedanta MP Power", sec: "Utilities" },
  { sym: "VEDANTA67", name: "Vedanta UP Power", sec: "Utilities" },
  { sym: "VEDANTA68", name: "Vedanta West Bengal Power", sec: "Utilities" },
  { sym: "VEDANTA69", name: "Vedanta Bihar Power", sec: "Utilities" },
  { sym: "VEDANTA70", name: "Vedanta Assam Power", sec: "Utilities" },
  { sym: "VEDANTA71", name: "Vedanta Kerala Power", sec: "Utilities" },
  { sym: "VEDANTA72", name: "Vedanta Telangana Power", sec: "Utilities" },
  { sym: "VEDANTA73", name: "Vedanta AP Power", sec: "Utilities" },
  { sym: "VEDANTA74", name: "Vedanta Karnataka Power2", sec: "Utilities" },
  { sym: "VEDANTA75", name: "Vedanta Tamil Nadu Power2", sec: "Utilities" },
  { sym: "VEDANTA76", name: "Vedanta Odisha Power2", sec: "Utilities" },
  { sym: "VEDANTA77", name: "Vedanta Jharkhand Power2", sec: "Utilities" },
  { sym: "VEDANTA78", name: "Vedanta Rajasthan Power2", sec: "Utilities" },
  { sym: "VEDANTA79", name: "Vedanta Gujarat Power2", sec: "Utilities" },
  { sym: "VEDANTA80", name: "Vedanta Maharashtra Power2", sec: "Utilities" },
  { sym: "VEDANTA81", name: "Vedanta MP Power2", sec: "Utilities" },
  { sym: "VEDANTA82", name: "Vedanta UP Power2", sec: "Utilities" },
  { sym: "VEDANTA83", name: "Vedanta WB Power2", sec: "Utilities" },
  { sym: "VEDANTA84", name: "Vedanta Bihar Power2", sec: "Utilities" },
  { sym: "VEDANTA85", name: "Vedanta Assam Power2", sec: "Utilities" },
  { sym: "VEDANTA86", name: "Vedanta Kerala Power2", sec: "Utilities" },
  { sym: "VEDANTA87", name: "Vedanta Telangana Power2", sec: "Utilities" },
  { sym: "VEDANTA88", name: "Vedanta AP Power2", sec: "Utilities" },
  { sym: "VEDANTA89", name: "Vedanta Punjab Power2", sec: "Utilities" },
  { sym: "VEDANTA90", name: "Vedanta Haryana Power", sec: "Utilities" },
  { sym: "VEDANTA91", name: "Vedanta Delhi Power", sec: "Utilities" },
  { sym: "VEDANTA92", name: "Vedanta J&K Power", sec: "Utilities" },
  { sym: "VEDANTA93", name: "Vedanta Himachal Power", sec: "Utilities" },
  { sym: "VEDANTA94", name: "Vedanta Uttarakhand Power", sec: "Utilities" },
  { sym: "VEDANTA95", name: "Vedanta Sikkim Power", sec: "Utilities" },
  { sym: "VEDANTA96", name: "Vedanta Manipur Power", sec: "Utilities" },
  { sym: "VEDANTA97", name: "Vedanta Meghalaya Power", sec: "Utilities" },
  { sym: "VEDANTA98", name: "Vedanta Tripura Power", sec: "Utilities" },
  { sym: "VEDANTA99", name: "Vedanta Nagaland Power", sec: "Utilities" },
  { sym: "VEDANTA100", name: "Vedanta Mizoram Power", sec: "Utilities" },
  { sym: "ADITYA30", name: "Aditya Birla Group Holdings", sec: "Finance" },
  { sym: "ADITYA31", name: "Grasim Industries Ltd", sec: "Materials" },
  { sym: "ADITYA32", name: "UltraTech Cement Ltd", sec: "Construction" },
  { sym: "ADITYA33", name: "Hindalco Industries Ltd", sec: "Materials" },
  { sym: "ADITYA34", name: "Aditya Birla Capital Ltd", sec: "Finance" },
  { sym: "ADITYA35", name: "Aditya Birla Fashion Retail", sec: "Retail" },
  { sym: "ADITYA36", name: "Aditya Birla Sun Life Insurance", sec: "Finance" },
  { sym: "ADITYA37", name: "Aditya Birla Housing Finance", sec: "Finance" },
  { sym: "ADITYA38", name: "Aditya Birla Money Ltd", sec: "Fintech" },
  { sym: "ADITYA39", name: "Aditya Birla Health Insurance", sec: "Finance" },
  { sym: "ADITYA40", name: "Aditya Birla Mutual Fund", sec: "Finance" },
  { sym: "ADITYA41", name: "Aditya Birla Real Estate", sec: "RealEstate" },
  { sym: "ADITYA42", name: "Aditya Birla Chemicals", sec: "Chemicals" },
  { sym: "ADITYA43", name: "Aditya Birla Insulators", sec: "Industrial" },
  { sym: "ADITYA44", name: "Aditya Birla Retail Ltd", sec: "Retail" },
  { sym: "ADITYA45", name: "Aditya Birla Telecom Ltd", sec: "Telecom" },
  { sym: "ADITYA46", name: "Aditya Birla Minerals Ltd", sec: "Mining" },
  { sym: "ADITYA47", name: "Pilani Investment & Industries", sec: "Finance" },
  { sym: "ADITYA48", name: "Century Textiles & Industries", sec: "Textiles" },
  { sym: "ADITYA49", name: "Century Enka Ltd", sec: "Textiles" },
  { sym: "ADITYA50", name: "Indian Rayon Ltd", sec: "Textiles" },
  { sym: "ADITYA51", name: "Jay Shree Tea & Industries", sec: "Food" },
  { sym: "ADITYA52", name: "Tanfac Industries Ltd", sec: "Chemicals" },
  { sym: "ADITYA53", name: "Ultratech Ceylon Pvt Ltd", sec: "Construction" },
  { sym: "ADITYA54", name: "Birla Cable Ltd", sec: "Industrial" },
  { sym: "ADITYA55", name: "Birla Corporation Ltd", sec: "Construction" },
  { sym: "ADITYA56", name: "Birla Cellulose (Grasim)", sec: "Textiles" },
  { sym: "ADITYA57", name: "Birla Carbon India Pvt Ltd", sec: "Industrial" },
  { sym: "ADITYA58", name: "Aditya Birla Minacs IT Services", sec: "Technology" },
  { sym: "ADITYA59", name: "Idea Cellular Ltd", sec: "Telecom" },
  { sym: "ADITYA60", name: "Vodafone Idea Ltd", sec: "Telecom" },
  { sym: "ADITYA61", name: "Novelis Inc (Hindalco)", sec: "Materials" },
  { sym: "ADITYA62", name: "Aditya Birla Asset Reconstruction", sec: "Finance" },
  { sym: "ADITYA63", name: "Aditya Birla Commercial Finance", sec: "Finance" },
  { sym: "ADITYA64", name: "Aditya Birla Insurance Brokers", sec: "Finance" },
  { sym: "ADITYA65", name: "Aditya Birla Wealth Mgmt", sec: "Finance" },
  { sym: "ADITYA66", name: "Aditya Birla Securities Ltd", sec: "Fintech" },
  { sym: "ADITYA67", name: "Aditya Birla Commodity Broking", sec: "Fintech" },
  { sym: "ADITYA68", name: "Aditya Birla Pension Fund", sec: "Finance" },
  { sym: "ADITYA69", name: "Aditya Birla Infra Pvt Ltd", sec: "Industrial" },
  { sym: "ADITYA70", name: "Aditya Birla Power Ltd", sec: "Utilities" },
  { sym: "ADITYA71", name: "Aditya Birla Renewable Energy", sec: "RenewableEnergy" },
  { sym: "ADITYA72", name: "Aditya Birla EV Ltd", sec: "EV" },
  { sym: "ADITYA73", name: "Aditya Birla AI Ltd", sec: "AI" },
  { sym: "ADITYA74", name: "Aditya Birla Cloud Computing", sec: "CloudComputing" },
  { sym: "ADITYA75", name: "Aditya Birla Cybersecurity", sec: "Cybersecurity" },
  { sym: "ADITYA76", name: "Aditya Birla Quantum Computing", sec: "QuantumComputing" },
  { sym: "ADITYA77", name: "Aditya Birla Robotics Ltd", sec: "Robotics" },
  { sym: "ADITYA78", name: "Aditya Birla SpaceTech Ltd", sec: "SpaceTech" },
  { sym: "ADITYA79", name: "Aditya Birla AgriTech Ltd", sec: "AgriTech" },
  { sym: "ADITYA80", name: "Aditya Birla EdTech Ltd", sec: "EdTech" },
  { sym: "ADITYA81", name: "Aditya Birla Gaming Ltd", sec: "Gaming" },
  { sym: "ADITYA82", name: "Aditya Birla Media Ltd", sec: "Media" },
  { sym: "ADITYA83", name: "Aditya Birla Travel Ltd", sec: "Travel" },
  { sym: "ADITYA84", name: "Aditya Birla Logistics Ltd", sec: "Logistics" },
  { sym: "ADITYA85", name: "Aditya Birla Defense Ltd", sec: "Defense" },
  { sym: "ADITYA86", name: "Aditya Birla Aerospace Ltd", sec: "Aerospace" },
  { sym: "ADITYA87", name: "Aditya Birla ECommerce Ltd", sec: "ECommerce" },
  { sym: "ADITYA88", name: "Aditya Birla Pharma Ltd", sec: "Pharma" },
  { sym: "ADITYA89", name: "Aditya Birla Biotech Ltd", sec: "Biotech" },
  { sym: "ADITYA90", name: "Aditya Birla Semiconductors", sec: "Semiconductors" },
  { sym: "ADITYA91", name: "Aditya Birla Fintech Ltd", sec: "Fintech" },
  { sym: "ADITYA92", name: "Aditya Birla Food Ltd", sec: "Food" },
  { sym: "ADITYA93", name: "Aditya Birla Automotive Ltd", sec: "Automotive" },
  { sym: "ADITYA94", name: "Aditya Birla Steel Ltd", sec: "Steel" },
  { sym: "ADITYA95", name: "Aditya Birla Mining Ltd", sec: "Mining" },
  { sym: "ADITYA96", name: "Aditya Birla Textiles Ltd", sec: "Textiles" },
  { sym: "ADITYA97", name: "Aditya Birla Construction Ltd", sec: "Construction" },
  { sym: "ADITYA98", name: "Aditya Birla Materials Ltd", sec: "Materials" },
  { sym: "ADITYA99", name: "Aditya Birla Utilities Ltd", sec: "Utilities" },
  { sym: "ADITYA100", name: "Aditya Birla RealEstate Ltd", sec: "RealEstate" },
];
