import type { StockMeta, Region, Sector, Exchange } from "./types";

// ─── REAL INDIAN STOCKS ─────────────────────────────────────────────────────
const INDIAN_STOCKS: [string, string, Sector, string][] = [
  ["TCS","Tata Consultancy Services","Technology","IT Services"],
  ["INFY","Infosys","Technology","IT Services"],
  ["WIPRO","Wipro","Technology","IT Services"],
  ["HCLTECH","HCL Technologies","Technology","IT Services"],
  ["TECHM","Tech Mahindra","Technology","IT Services"],
  ["LTIM","LTIMindtree","Technology","IT Services"],
  ["PERSISTENT","Persistent Systems","Technology","IT Services"],
  ["COFORGE","Coforge","Technology","IT Services"],
  ["MPHASIS","Mphasis","Technology","IT Services"],
  ["OFSS","Oracle Financial Services","Technology","Software"],
  ["KPITTECH","KPIT Technologies","Technology","Software"],
  ["TATAELXSI","Tata Elxsi","Technology","Software"],
  ["BOSCHLTD","Bosch","Technology","Auto Components"],
  ["SONATSOFTW","Sonata Software","Technology","IT Services"],
  ["CYIENT","Cyient","Technology","IT Services"],
  ["IRCTC","Indian Railway Catering","Technology","E-Governance"],
  ["CDSL","Central Depository Services","Technology","Financial Tech"],
  ["MAZDOCK","Mazagon Dock Shipbuilders","Industrials","Shipbuilding"],
  ["COCHINSHIP","Cochin Shipyard","Industrials","Shipbuilding"],
  ["HDFCBANK","HDFC Bank","Financials","Private Bank"],
  ["ICICIBANK","ICICI Bank","Financials","Private Bank"],
  ["SBIN","State Bank of India","Financials","Public Bank"],
  ["KOTAKBANK","Kotak Mahindra Bank","Financials","Private Bank"],
  ["AXISBANK","Axis Bank","Financials","Private Bank"],
  ["INDUSINDBK","IndusInd Bank","Financials","Private Bank"],
  ["PNB","Punjab National Bank","Financials","Public Bank"],
  ["BANKBARODA","Bank of Baroda","Financials","Public Bank"],
  ["CANBK","Canara Bank","Financials","Public Bank"],
  ["UNIONBANK","Union Bank of India","Financials","Public Bank"],
  ["BANKINDIA","Bank of India","Financials","Public Bank"],
  ["IDFCFIRSTB","IDFC First Bank","Financials","Private Bank"],
  ["FEDERALBNK","Federal Bank","Financials","Private Bank"],
  ["AUBANK","AU Small Finance Bank","Financials","Small Finance Bank"],
  ["SBILIFE","SBI Life Insurance","Financials","Insurance"],
  ["HDFCLIFE","HDFC Life Insurance","Financials","Insurance"],
  ["ICICIPRULI","ICICI Prudential Life","Financials","Insurance"],
  ["ICICIGI","ICICI Lombard General","Financials","Insurance"],
  ["LICI","Life Insurance Corporation","Financials","Insurance"],
  ["BAJFINANCE","Bajaj Finance","Financials","NBFC"],
  ["BAJAJFINSV","Bajaj Finserv","Financials","NBFC"],
  ["CHOLAFIN","Cholamandalam Investment","Financials","NBFC"],
  ["MUTHOOTFIN","Muthoot Finance","Financials","NBFC"],
  ["SHRIRAMFIN","Shriram Finance","Financials","NBFC"],
  ["LTF","L&T Finance","Financials","NBFC"],
  ["PFC","Power Finance Corporation","Financials","NBFC"],
  ["RECLTD","REC Limited","Financials","NBFC"],
  ["M&MFIN","Mahindra & Mahindra Financial","Financials","NBFC"],
  ["ANANDRATHI","Anand Rathi Wealth","Financials","Wealth Management"],
  ["CAMS","Computer Age Management Services","Financials","Financial Tech"],
  ["IIFL","IIFL Finance","Financials","NBFC"],
  ["MANAPPURAM","Manappuram Finance","Financials","NBFC"],
  ["SBICARD","SBI Cards and Payment Services","Financials","Credit Cards"],
  ["HDFCAMC","HDFC Asset Management","Financials","Asset Management"],
  ["NAM-INDIA","Nippon Life India Asset","Financials","Asset Management"],
  ["ABCAPITAL","Aditya Birla Capital","Financials","NBFC"],
  ["TRENT","Trent","Consumer Discretionary","Retail"],
  ["NTPC","NTPC Limited","Utilities","Power Generation"],
  ["NHPC","NHPC Limited","Utilities","Hydropower"],
  ["SJVN","SJVN Limited","Utilities","Hydropower"],
  ["POWERGRID","Power Grid Corporation","Utilities","Power Transmission"],
  ["ONGC","Oil and Natural Gas Corporation","Energy","Oil & Gas"],
  ["IOC","Indian Oil Corporation","Energy","Oil & Gas"],
  ["BPCL","Bharat Petroleum","Energy","Oil & Gas"],
  ["HPCL","Hindustan Petroleum","Energy","Oil & Gas"],
  ["GAIL","GAIL India","Energy","Natural Gas"],
  ["COALINDIA","Coal India","Energy","Coal Mining"],
  ["RELIANCE","Reliance Industries","Energy","Conglomerate"],
  ["TATAPOWER","Tata Power","Utilities","Power Generation"],
  ["ADANIPOWER","Adani Power","Utilities","Power Generation"],
  ["ADANIGREEN","Adani Green Energy","Utilities","Renewable Energy"],
  ["ADANIENSOL","Adani Energy Solutions","Utilities","Power Transmission"],
  ["JSWENERGY","JSW Energy","Utilities","Power Generation"],
  ["SUZLON","Suzlon Energy","Industrials","Wind Energy"],
  ["INOXWIND","Inox Wind","Industrials","Wind Energy"],
  ["KPIGREEN","KPI Green Energy","Utilities","Solar Energy"],
  ["SUNPHARMA","Sun Pharmaceutical","Healthcare","Pharmaceuticals"],
  ["DRREDDY","Dr Reddys Laboratories","Healthcare","Pharmaceuticals"],
  ["CIPLA","Cipla","Healthcare","Pharmaceuticals"],
  ["APOLLOHOSP","Apollo Hospitals","Healthcare","Healthcare Services"],
  ["DIVISLAB","Divis Laboratories","Healthcare","Pharmaceuticals"],
  ["LUPIN","Lupin","Healthcare","Pharmaceuticals"],
  ["AUROPHARMA","Aurobindo Pharma","Healthcare","Pharmaceuticals"],
  ["ZYDUSLIFE","Zydus Lifesciences","Healthcare","Pharmaceuticals"],
  ["BIOCON","Biocon","Healthcare","Biotechnology"],
  ["MAXHEALTH","Max Healthcare","Healthcare","Healthcare Services"],
  ["FORTIS","Fortis Healthcare","Healthcare","Healthcare Services"],
  ["LALPATHLAB","Dr Lal PathLabs","Healthcare","Diagnostics"],
  ["METROPOLIS","Metropolis Healthcare","Healthcare","Diagnostics"],
  ["ALKEM","Alkem Laboratories","Healthcare","Pharmaceuticals"],
  ["TORNTPHARM","Torrent Pharmaceuticals","Healthcare","Pharmaceuticals"],
  ["ABBOTINDIA","Abbott India","Healthcare","Pharmaceuticals"],
  ["GLENMARK","Glenmark Pharma","Healthcare","Pharmaceuticals"],
  ["IPCA","Ipca Laboratories","Healthcare","Pharmaceuticals"],
  ["LAURUSLABS","Laurus Labs","Healthcare","Pharmaceuticals"],
  ["HINDUNILVR","Hindustan Unilever","Consumer Staples","FMCG"],
  ["ITC","ITC Limited","Consumer Staples","FMCG"],
  ["NESTLEIND","Nestle India","Consumer Staples","FMCG"],
  ["BRITANNIA","Britannia Industries","Consumer Staples","FMCG"],
  ["DABUR","Dabur India","Consumer Staples","FMCG"],
  ["MARICO","Marico","Consumer Staples","FMCG"],
  ["GODREJCP","Godrej Consumer Products","Consumer Staples","FMCG"],
  ["COLPAL","Colgate Palmolive","Consumer Staples","FMCG"],
  ["HAVELLS","Havells India","Consumer Discretionary","Electricals"],
  ["TATACONSUM","Tata Consumer Products","Consumer Staples","FMCG"],
  ["UNITDSPR","United Spirits","Consumer Staples","Beverages"],
  ["UBL","United Breweries","Consumer Staples","Beverages"],
  ["VBL","Varun Beverages","Consumer Staples","Beverages"],
  ["DMART","Avenue Supermarts","Consumer Staples","Retail"],
  ["NYKAA","FSN E-Commerce (Nykaa)","Consumer Discretionary","E-Commerce"],
  ["ZOMATO","Zomato","Consumer Discretionary","Food Delivery"],
  ["PAYTM","One 97 Communications (Paytm)","Financials","Fintech"],
  ["POLICYBZR","PB Fintech (PolicyBazaar)","Financials","Insurance Tech"],
  ["PNBHOUSING","PNB Housing Finance","Financials","Housing Finance"],
  ["MARUTI","Maruti Suzuki","Consumer Discretionary","Automobile"],
  ["TATAMOTORS","Tata Motors","Consumer Discretionary","Automobile"],
  ["M&M","Mahindra & Mahindra","Consumer Discretionary","Automobile"],
  ["BAJAJ-AUTO","Bajaj Auto","Consumer Discretionary","Automobile"],
  ["EICHERMOT","Eicher Motors","Consumer Discretionary","Automobile"],
  ["HEROMOTOCO","Hero MotoCorp","Consumer Discretionary","Automobile"],
  ["TVSMOTOR","TVS Motor Company","Consumer Discretionary","Automobile"],
  ["ASHOKLEY","Ashok Leyland","Consumer Discretionary","Commercial Vehicles"],
  ["MOTHERSON","Samvardhana Motherson","Consumer Discretionary","Auto Components"],
  ["BALKRISIND","Balkrishna Industries","Consumer Discretionary","Auto Components"],
  ["EXIDEIND","Exide Industries","Consumer Discretionary","Auto Components"],
  ["AMARAJABAT","Amara Raja Batteries","Consumer Discretionary","Auto Components"],
  ["MRF","MRF Limited","Consumer Discretionary","Tyres"],
  ["APOLLOTYRE","Apollo Tyres","Consumer Discretionary","Tyres"],
  ["TIINDIA","Tube Investments","Consumer Discretionary","Auto Components"],
  ["LT","Larsen & Toubro","Industrials","Construction"],
  ["ULTRACEMCO","UltraTech Cement","Materials","Cement"],
  ["GRASIM","Grasim Industries","Materials","Cement"],
  ["SHREECEM","Shree Cement","Materials","Cement"],
  ["AMBUJACEM","Ambuja Cements","Materials","Cement"],
  ["ACC","ACC Limited","Materials","Cement"],
  ["DALMIABHA","Dalmia Bharat","Materials","Cement"],
  ["RAMCOCEM","The Ramco Cements","Materials","Cement"],
  ["SIEMENS","Siemens India","Industrials","Industrial Equipment"],
  ["ABB","ABB India","Industrials","Industrial Equipment"],
  ["CUMMINSIND","Cummins India","Industrials","Industrial Equipment"],
  ["BEL","Bharat Electronics","Industrials","Defense"],
  ["HAL","Hindustan Aeronautics","Industrials","Defense"],
  ["BDL","Bharat Dynamics","Industrials","Defense"],
  ["ASTRAL","Astral","Industrials","Pipes"],
  ["SUPREMEIND","Supreme Industries","Industrials","Plastics"],
  ["KSB","KSB Limited","Industrials","Pumps"],
  ["ELECON","Elecon Engineering","Industrials","Industrial Equipment"],
  ["TATASTEEL","Tata Steel","Materials","Steel"],
  ["JSWSTEEL","JSW Steel","Materials","Steel"],
  ["HINDALCO","Hindalco Industries","Materials","Aluminium"],
  ["VEDL","Vedanta","Materials","Diversified Metals"],
  ["NMDC","NMDC Limited","Materials","Iron Ore Mining"],
  ["SAIL","Steel Authority of India","Materials","Steel"],
  ["JINDALSTEL","Jindal Steel & Power","Materials","Steel"],
  ["JSPL","Jindal Steel & Power","Materials","Steel"],
  ["NATIONALUM","National Aluminium","Materials","Aluminium"],
  ["HINDCOPPER","Hindustan Copper","Materials","Copper Mining"],
  ["APLAPOLLO","APL Apollo Tubes","Materials","Steel Tubes"],
  ["RATNAMANI","Ratnamani Metals","Materials","Steel Pipes"],
  ["BHARTIARTL","Bharti Airtel","Communication Services","Telecom"],
  ["IDEA","Vodafone Idea","Communication Services","Telecom"],
  ["INDUSTOWER","Indus Towers","Communication Services","Telecom Infrastructure"],
  ["TATACOMM","Tata Communications","Communication Services","Telecom"],
  ["DLF","DLF Limited","Real Estate","Real Estate"],
  ["GODREJPROP","Godrej Properties","Real Estate","Real Estate"],
  ["OBEROIRLTY","Oberoi Realty","Real Estate","Real Estate"],
  ["LODHA","Macrotech Developers (Lodha)","Real Estate","Real Estate"],
  ["PHOENIXLTD","The Phoenix Mills","Real Estate","Real Estate"],
  ["BRIGADE","Brigade Enterprises","Real Estate","Real Estate"],
  ["PRESTIGE","Prestige Estates","Real Estate","Real Estate"],
  ["ADANIENT","Adani Enterprises","Industrials","Conglomerate"],
  ["ADANIPORTS","Adani Ports & SEZ","Industrials","Infrastructure"],
  ["ADANIWILMAR","Adani Wilmar","Consumer Staples","FMCG"],
  ["ADANITOTALGAS","Adani Total Gas","Utilities","Natural Gas"],
  ["PIDILITIND","Pidilite Industries","Materials","Specialty Chemicals"],
  ["PIIND","PI Industries","Materials","Agrochemicals"],
  ["SRF","SRF Limited","Materials","Specialty Chemicals"],
  ["TATAINVEST","Tata Investment Corporation","Financials","Investment"],
  ["RBLBANK","RBL Bank","Financials","Private Bank"],
  ["RVNL","Rail Vikas Nigam","Industrials","Railways"],
  ["RAYMOND","Raymond","Consumer Discretionary","Textiles"],
  ["RITES","RITES Limited","Industrials","Railways"],
  ["ROSSARI","Rossari Biotech","Materials","Specialty Chemicals"],
  ["ROUTE","Route Mobile","Communication Services","Telecom Tech"],
  ["MOTILALOFS","Motilal Oswal Financial","Financials","NBFC"],
  ["KFINTECH","KFin Technologies","Financials","Financial Tech"],
  ["EMUDHRA","eMudhra","Technology","Digital Signature"],
  ["EASEMYTRIP","Easy Trip Planners","Consumer Discretionary","Travel Tech"],
  ["FRESHWORKS","Freshworks","Technology","SaaS"],
  ["INDHOTEL","Indian Hotels Company","Consumer Discretionary","Hotels"],
  ["INDIGO","InterGlobe Aviation","Industrials","Airlines"],
  ["IRB","IRB Infrastructure","Industrials","Highways"],
  ["IRCON","IRCON International","Industrials","Railways"],
  ["ITI","ITI Limited","Communication Services","Telecom Equipment"],
  ["JBCHEPHARM","JB Chemicals","Healthcare","Pharmaceuticals"],
  ["JKCEMENT","JK Cement","Materials","Cement"],
  ["JKLAKSHMI","JK Lakshmi Cement","Materials","Cement"],
  ["JKPAPER","JK Paper","Materials","Paper"],
  ["JKTYRE","JK Tyre","Consumer Discretionary","Tyres"],
  ["JSWHOTEL","JSW Hotels","Consumer Discretionary","Hotels"],
  ["KALYANKJIL","Kalyan Jewellers","Consumer Discretionary","Jewellery"],
  ["KANSAINER","Kansai Nerolac","Materials","Paints"],
  ["KARURVYSYA","Karur Vysya Bank","Financials","Private Bank"],
  ["KEI","KEI Industries","Industrials","Cables"],
  ["KIMS","Krishna Institute of Medical","Healthcare","Healthcare Services"],
  ["KOPRAN","Kopran","Healthcare","Pharmaceuticals"],
  ["KPRMILL","KPR Mill","Consumer Discretionary","Textiles"],
  ["KRBL","KRBL Limited","Consumer Staples","Rice"],
  ["KTKBANK","Karnataka Bank","Financials","Private Bank"],
  ["LAXMIMACH","Laxmi Machine Works","Industrials","Industrial Equipment"],
  ["LLOYDS","Lloyds Metals","Materials","Metals"],
  ["LUMAX","Lumax Industries","Consumer Discretionary","Auto Components"],
  ["LUXIND","Lux Industries","Consumer Discretionary","Textiles"],
  ["MAHABANK","Bank of Maharashtra","Financials","Public Bank"],
  ["MAHLOG","Mahindra Logistics","Industrials","Logistics"],
  ["MAXVIL","Max Ventures","Real Estate","Real Estate"],
  ["MCX","Multi Commodity Exchange","Financials","Exchange"],
  ["MHRIL","Mahindra Holidays","Consumer Discretionary","Resorts"],
  ["MINDTREE","Mindtree","Technology","IT Services"],
  ["MASTEK","Mastek","Technology","IT Services"],
  ["MOLDTKPAC","Mold-Tek Packaging","Materials","Packaging"],
  ["MONTECARLO","Monte Carlo","Consumer Discretionary","Apparel"],
  ["MUKAND","Mukand","Materials","Steel"],
  ["MUTHOOTFIN","Muthoot Finance","Financials","NBFC"],
  ["NATCOPHARM","Natco Pharma","Healthcare","Pharmaceuticals"],
  ["NAVINFLUOR","Navin Fluorine","Materials","Specialty Chemicals"],
  ["NBCC","NBCC India","Industrials","Construction"],
  ["NCC","NCC Limited","Industrials","Construction"],
  ["NEOGEN","Neogen Chemicals","Materials","Specialty Chemicals"],
  ["NEWGEN","Newgen Software","Technology","Software"],
  ["NIACL","New India Assurance","Financials","Insurance"],
  ["NIIT","NIIT Limited","Technology","Education"],
  ["NITCO","Nitco","Consumer Discretionary","Tiles"],
  ["NITINSPIN","Nitin Spinners","Consumer Discretionary","Textiles"],
  ["NUCLEUS","Nucleus Software","Technology","Software"],
  ["NUVOCO","Nuvoco Vistas","Materials","Cement"],
  ["OIL","Oil India","Energy","Oil & Gas"],
  ["OMAXE","Omaxe","Real Estate","Real Estate"],
  ["ONMOBILE","OnMobile","Communication Services","Telecom Tech"],
  ["ORIENTCEM","Orient Cement","Materials","Cement"],
  ["ORIENTELEC","Orient Electric","Consumer Discretionary","Electricals"],
  ["PFC","Power Finance Corporation","Financials","NBFC"],
  ["PFIZER","Pfizer","Healthcare","Pharmaceuticals"],
  ["PGHL","Page Industries","Consumer Discretionary","Apparel"],
  ["PHOENIXLTD","Phoenix Mills","Real Estate","Real Estate"],
  ["PIRAMAL","Piramal Enterprises","Financials","NBFC"],
  ["PIRAMPHAR","Piramal Pharma","Healthcare","Pharmaceuticals"],
  ["POLYMED","Polymed","Healthcare","Medical Devices"],
  ["POLYPLEX","Polyplex","Materials","Films"],
  ["POONAWALLA","Poonawalla Fincorp","Financials","NBFC"],
  ["PRAJIND","Praj Industries","Industrials","Industrial Equipment"],
  ["PRESTIGE","Prestige Estates","Real Estate","Real Estate"],
  ["PRINCEPIPE","Prince Pipes","Industrials","Pipes"],
  ["PSB","Punjab & Sind Bank","Financials","Public Bank"],
  ["PTC","PTC India","Utilities","Power Trading"],
  ["PTCIL","PTC Industries","Industrials","Industrial Equipment"],
  ["PVR","PVR INOX","Communication Services","Cinema"],
  ["QUESS","Quess Corp","Industrials","Staffing"],
  ["RCF","Rashtriya Chemicals","Materials","Chemicals"],
  ["REDINGTON","Redington","Technology","IT Distribution"],
  ["REFEX","Refex Industries","Materials","Specialty Chemicals"],
  ["RELINFRA","Reliance Infrastructure","Industrials","Infrastructure"],
  ["RELPOWER","Reliance Power","Utilities","Power Generation"],
  ["REPRO","Repro India","Materials","Printing"],
  ["ROLEXRINGS","Rolex Rings","Consumer Discretionary","Auto Components"],
  ["SAFARI","Safari Industries","Consumer Discretionary","Luggage"],
  ["SAIL","Steel Authority of India","Materials","Steel"],
  ["SANOFI","Sanofi India","Healthcare","Pharmaceuticals"],
  ["SAPPHIRE","Sapphire Foods","Consumer Discretionary","Restaurants"],
  ["SAREGAMA","Saregama India","Communication Services","Music"],
  ["SASKEN","Sasken Technologies","Technology","IT Services"],
  ["SCHAEFFLER","Schaeffler India","Consumer Discretionary","Auto Components"],
  ["SCI","Shipping Corporation","Industrials","Shipping"],
  ["SEQUENT","Sequent Scientific","Healthcare","Pharmaceuticals"],
  ["SKF","SKF India","Consumer Discretionary","Auto Components"],
  ["SLI","Surya Roshni","Consumer Discretionary","Lighting"],
  ["SNOWMAN","Snowman Logistics","Industrials","Cold Chain"],
  ["SOBHA","Sobha Limited","Real Estate","Real Estate"],
  ["SOLARINDS","Solar Industries","Materials","Explosives"],
  ["SONACOMS","Sona Comstar","Consumer Discretionary","Auto Components"],
  ["SOUTHBANK","South Indian Bank","Financials","Private Bank"],
  ["SPANDANA","Spandana Sphoorty","Financials","NBFC"],
  ["SPARC","Sun Pharma Advanced Research","Healthcare","Pharmaceuticals"],
  ["SPICEJET","SpiceJet","Industrials","Airlines"],
  ["STAR","Star Health Insurance","Financials","Insurance"],
  ["STARCEMENT","Star Cement","Materials","Cement"],
  ["STLTECH","Sterlite Technologies","Communication Services","Telecom"],
  ["STOVEKRAFT","Stove Kraft","Consumer Discretionary","Appliances"],
  ["SUNTECK","Sunteck Realty","Real Estate","Real Estate"],
  ["SUNTV","Sun TV Network","Communication Services","Media"],
  ["SWANENERGY","Swan Energy","Consumer Discretionary","Textiles"],
  ["SWARAJENG","Swaraj Engines","Industrials","Tractors"],
  ["SWSOLAR","Sterling and Wilson Solar","Industrials","Solar EPC"],
  ["SYMPHONY","Symphony","Consumer Discretionary","Appliances"],
  ["SYNGENE","Syngene International","Healthcare","Biotechnology"],
  ["TALBROAUTO","Talbros Automotive","Consumer Discretionary","Auto Components"],
  ["TANLA","Tanla Platforms","Communication Services","Telecom Tech"],
  ["TATACHEM","Tata Chemicals","Materials","Chemicals"],
  ["TATACONSUM","Tata Consumer","Consumer Staples","FMCG"],
  ["TATAINVEST","Tata Investment","Financials","Investment"],
  ["TATAPOWER","Tata Power","Utilities","Power Generation"],
  ["TATASTEEL","Tata Steel","Materials","Steel"],
  ["TEAMLEASE","TeamLease Services","Industrials","Staffing"],
  ["TEJASNET","Tejas Networks","Communication Services","Telecom"],
  ["THERMAX","Thermax","Industrials","Industrial Equipment"],
  ["THYROCARE","Thyrocare Technologies","Healthcare","Diagnostics"],
  ["TITAN","Titan Company","Consumer Discretionary","Jewellery"],
  ["TORNTPHARM","Torrent Pharmaceuticals","Healthcare","Pharmaceuticals"],
  ["TRACXN","Tracxn Technologies","Technology","Data"],
  ["TRIDENT","Trident","Consumer Discretionary","Textiles"],
  ["TRIVENI","Triveni Engineering","Consumer Staples","Sugar"],
  ["TTKPRESTIG","TTK Prestige","Consumer Discretionary","Appliances"],
  ["TV18BRDCST","TV18 Broadcast","Communication Services","Media"],
  ["TVSSCS","TVS Supply Chain","Industrials","Logistics"],
  ["UCOBANK","UCO Bank","Financials","Public Bank"],
  ["UJJIVANSFB","Ujjivan SFB","Financials","Small Finance Bank"],
  ["ULTRACEMCO","UltraTech Cement","Materials","Cement"],
  ["UNIONBANK","Union Bank of India","Financials","Public Bank"],
  ["UNITDSPR","United Spirits","Consumer Staples","Beverages"],
  ["UPL","UPL Limited","Materials","Agrochemicals"],
  ["UTIAMC","UTI Asset Management","Financials","Asset Management"],
  ["VEDL","Vedanta","Materials","Diversified Metals"],
  ["VIMTA","Vimta Labs","Healthcare","Diagnostics"],
  ["VINATI","Vinati Organics","Materials","Specialty Chemicals"],
  ["VIPIND","VIP Industries","Consumer Discretionary","Luggage"],
  ["VSTTIL","VST Tillers Tractors","Industrials","Tractors"],
  ["WABCO","Wabco India","Consumer Discretionary","Auto Components"],
  ["WELCORP","Welspun Corp","Materials","Steel Pipes"],
  ["WELSPUNLIV","Welspun Living","Consumer Discretionary","Textiles"],
  ["WESTLIFE","Westlife Foodworld","Consumer Discretionary","Restaurants"],
  ["WOCKPHARMA","Wockhardt","Healthcare","Pharmaceuticals"],
  ["YESBANK","Yes Bank","Financials","Private Bank"],
  ["ZAGGLE","Zaggle Prepaid Ocean","Technology","Fintech"],
  ["ZENSAREXP","Zensar Technologies","Technology","IT Services"],
  ["ZENTEC","Zen Technologies","Industrials","Defense"],
  ["ZEEL","Zee Entertainment","Communication Services","Media"],
  ["ZYDUSWELL","Zydus Wellness","Consumer Staples","FMCG"],
  ["GMRINFRA","GMR Infrastructure","Industrials","Infrastructure"],
  ["GMRAIRPORT","GMR Airports","Industrials","Airport"],
  ["HFCL","HFCL Limited","Communication Services","Telecom Equipment"],
  ["IDBI","IDBI Bank","Financials","Public Bank"],
  ["IEX","Indian Energy Exchange","Financials","Exchange"],
  ["INDIAMART","IndiaMART InterMESH","Technology","E-Commerce"],
  ["INDIGOPNTS","Indigo Paints","Materials","Paints"],
  ["INDUSTOWER","Indus Towers","Communication Services","Telecom Infra"],
  ["JINDALSTEL","Jindal Steel","Materials","Steel"],
  ["JSWSTEEL","JSW Steel","Materials","Steel"],
  ["KARURVYSYA","Karur Vysya Bank","Financials","Private Bank"],
  ["KEI","KEI Industries","Industrials","Cables"],
  ["KOTAKBANK","Kotak Mahindra Bank","Financials","Private Bank"],
  ["LICHSGFIN","LIC Housing Finance","Financials","Housing Finance"],
  ["MAHSCOOT","Mahindra CIE","Consumer Discretionary","Auto Components"],
  ["MANAPPURAM","Manappuram Finance","Financials","NBFC"],
  ["MFSL","Motilal Oswal Financial","Financials","NBFC"],
  ["NAM-INDIA","Nippon Life India","Financials","Asset Management"],
  ["NATCOPHARM","Natco Pharma","Healthcare","Pharmaceuticals"],
  ["NAVINFLUOR","Navin Fluorine","Materials","Specialty Chemicals"],
  ["NIRAJ","Niraj Cement Structurals","Industrials","Construction"],
  ["NSLNBEVER","NSL Beverages","Consumer Staples","Beverages"],
  ["OIL","Oil India","Energy","Oil & Gas"],
  ["ORIENTALTL","Orient Tiles","Consumer Discretionary","Tiles"],
  ["ORIENTBELL","Orient Bell","Consumer Discretionary","Tiles"],
  ["ORIENTPAPER","Orient Paper","Materials","Paper"],
  ["PETRONET","Petronet LNG","Energy","Natural Gas"],
  ["PRITIKA","Pritika Auto","Consumer Discretionary","Auto Components"],
  ["RALLIS","Rallis India","Materials","Agrochemicals"],
  ["RBLBANK","RBL Bank","Financials","Private Bank"],
  ["RITES","RITES Limited","Industrials","Railways"],
  ["RVNL","Rail Vikas Nigam","Industrials","Railways"],
  ["SAKSOFT","Saksoft","Technology","IT Services"],
  ["SCHNEIDER","Schneider Electric","Industrials","Electrical Equipment"],
  ["SIGIND","Sigind","Industrials","Industrial Equipment"],
  ["SIS","Security and Intelligence Services","Industrials","Security"],
  ["STERTOOLS","Sterlite Technologies","Communication Services","Telecom"],
  ["SUNDARMFIN","Sundaram Finance","Financials","NBFC"],
  ["SUPREMEIND","Supreme Industries","Industrials","Plastics"],
  ["TALBROAUTO","Talbros Automotive","Consumer Discretionary","Auto Components"],
  ["TATAADV","Tata Advanced Systems","Industrials","Defense"],
  ["TATACOFFEE","Tata Coffee","Consumer Staples","Beverages"],
  ["TATASTEELB","Tata Steel BSL","Materials","Steel"],
  ["TATVA","Tatva Chintamani","Healthcare","Pharmaceuticals"],
  ["TTML","Tata Teleservices","Communication Services","Telecom"],
  ["UTI","UTI Asset Management","Financials","Asset Management"],
  ["VTL","VTL Industries","Consumer Discretionary","Textiles"],
  ["WINDLAS","Windlas Biotech","Healthcare","Pharmaceuticals"],
  ["ZUARI","Zuari Agro Chemicals","Materials","Agrochemicals"],
  ["ECLERX","eClerx Services","Technology","IT Services"],
  ["EIHOTEL","EIH Hotels","Consumer Discretionary","Hotels"],
  ["ERIS","Eris Lifesciences","Healthcare","Pharmaceuticals"],
  ["FINCABLES","Finolex Cables","Industrials","Cables"],
  ["FINPIPE","Finolex Industries","Industrials","Pipes"],
  ["GESHIP","Great Eastern Shipping","Industrials","Shipping"],
  ["GICRE","GIC Reinsurance","Financials","Reinsurance"],
  ["GLENMARK","Glenmark Pharma","Healthcare","Pharmaceuticals"],
  ["GODREJIND","Godrej Industries","Industrials","Conglomerate"],
  ["GODREJAGRO","Godrej Agrovet","Consumer Staples","Agrochemicals"],
  ["GRANULES","Granules India","Healthcare","Pharmaceuticals"],
  ["GUJGASLTD","Gujarat Gas","Utilities","Natural Gas"],
  ["HEG","HEG Limited","Industrials","Graphite Electrodes"],
  ["HEMIPROP","Hemisphere Properties","Real Estate","Real Estate"],
  ["HINDPETRO","Hindustan Petroleum","Energy","Oil & Gas"],
  ["HONAUT","Honeywell Automation","Technology","Industrial Automation"],
  ["IBULHSGFIN","Indiabulls Housing Finance","Financials","Housing Finance"],
  ["ICICIBANK","ICICI Bank","Financials","Private Bank"],
  ["ICICISEC","ICICI Securities","Financials","Brokerage"],
  ["IDFCFIRSTB","IDFC First Bank","Financials","Private Bank"],
  ["IGL","Indraprastha Gas","Utilities","Natural Gas"],
  ["INDHOTEL","Indian Hotels","Consumer Discretionary","Hotels"],
  ["INDUSINDBK","IndusInd Bank","Financials","Private Bank"],
  ["INDUSPORTS","Indus Ports","Industrials","Infrastructure"],
  ["INFY","Infosys","Technology","IT Services"],
  ["IRB","IRB Infrastructure","Industrials","Highways"],
  ["IRCON","IRCON International","Industrials","Railways"],
  ["ITC","ITC Limited","Consumer Staples","FMCG"],
  ["JAMFRA","Jamfra","Financials","NBFC"],
  ["JINDALSTEL","Jindal Steel","Materials","Steel"],
  ["JKLAKSHMI","JK Lakshmi Cement","Materials","Cement"],
  ["JUBLFOOD","Jubilant FoodWorks","Consumer Discretionary","Restaurants"],
  ["JUBLPHARMA","Jubilant Pharmova","Healthcare","Pharmaceuticals"],
  ["KPITTECH","KPIT Technologies","Technology","Software"],
  ["KANSAINER","Kansai Nerolac","Materials","Paints"],
  ["KARURVYSYA","Karur Vysya Bank","Financials","Private Bank"],
  ["KEI","KEI Industries","Industrials","Cables"],
  ["KOTAKBANK","Kotak Mahindra Bank","Financials","Private Bank"],
  ["LALPATHLAB","Dr Lal PathLabs","Healthcare","Diagnostics"],
  ["LAURUSLABS","Laurus Labs","Healthcare","Pharmaceuticals"],
  ["LICHSGFIN","LIC Housing Finance","Financials","Housing Finance"],
  ["LT","Larsen & Toubro","Industrials","Construction"],
  ["LTIM","LTIMindtree","Technology","IT Services"],
  ["LUPIN","Lupin","Healthcare","Pharmaceuticals"],
  ["M&M","Mahindra & Mahindra","Consumer Discretionary","Automobile"],
  ["M&MFIN","Mahindra Financial","Financials","NBFC"],
  ["MANAPPURAM","Manappuram Finance","Financials","NBFC"],
  ["MARICO","Marico","Consumer Staples","FMCG"],
  ["MARUTI","Maruti Suzuki","Consumer Discretionary","Automobile"],
  ["MASTEK","Mastek","Technology","IT Services"],
  ["MAXHEALTH","Max Healthcare","Healthcare","Healthcare Services"],
  ["MCX","Multi Commodity Exchange","Financials","Exchange"],
  ["METROPOLIS","Metropolis Healthcare","Healthcare","Diagnostics"],
  ["MINDTREE","Mindtree","Technology","IT Services"],
  ["MOTHERSON","Samvardhana Motherson","Consumer Discretionary","Auto Components"],
  ["MOTILALOFS","Motilal Oswal Financial","Financials","NBFC"],
  ["MRF","MRF Limited","Consumer Discretionary","Tyres"],
  ["MUTHOOTFIN","Muthoot Finance","Financials","NBFC"],
  ["NATCOPHARM","Natco Pharma","Healthcare","Pharmaceuticals"],
  ["NATIONALUM","National Aluminium","Materials","Aluminium"],
  ["NAVINFLUOR","Navin Fluorine","Materials","Specialty Chemicals"],
  ["NBCC","NBCC India","Industrials","Construction"],
  ["NEULANDLAB","Neuland Labs","Healthcare","Pharmaceuticals"],
  ["NEWGEN","Newgen Software","Technology","Software"],
  ["NHPC","NHPC Limited","Utilities","Hydropower"],
  ["NIACL","New India Assurance","Financials","Insurance"],
  ["NIIT","NIIT Limited","Technology","Education"],
  ["NMDC","NMDC Limited","Materials","Iron Ore Mining"],
  ["NOCIL","Nocil","Materials","Chemicals"],
  ["NTPC","NTPC Limited","Utilities","Power Generation"],
  ["NUCLEUS","Nucleus Software","Technology","Software"],
  ["NUVOCO","Nuvoco Vistas","Materials","Cement"],
  ["OAL","OAL Limited","Industrials","Construction"],
  ["OBEROIRLTY","Oberoi Realty","Real Estate","Real Estate"],
  ["OIL","Oil India","Energy","Oil & Gas"],
  ["ONGC","Oil and Natural Gas Corporation","Energy","Oil & Gas"],
  ["PAGEIND","Page Industries","Consumer Discretionary","Apparel"],
  ["PCBL","PCBL Limited","Materials","Carbon Black"],
  ["PERSISTENT","Persistent Systems","Technology","IT Services"],
  ["PETRONET","Petronet LNG","Energy","Natural Gas"],
  ["PFC","Power Finance Corporation","Financials","NBFC"],
  ["PFIZER","Pfizer","Healthcare","Pharmaceuticals"],
  ["PGHH","Procter & Gamble Hygiene","Consumer Staples","FMCG"],
  ["PIDILITIND","Pidilite Industries","Materials","Specialty Chemicals"],
  ["PIIND","PI Industries","Materials","Agrochemicals"],
  ["PIRAMAL","Piramal Enterprises","Financials","NBFC"],
  ["PNB","Punjab National Bank","Financials","Public Bank"],
  ["PNBHOUSING","PNB Housing Finance","Financials","Housing Finance"],
  ["POLICYBZR","PB Fintech","Financials","Insurance Tech"],
  ["POLYMED","Polymed","Healthcare","Medical Devices"],
  ["POONAWALLA","Poonawalla Fincorp","Financials","NBFC"],
  ["POWERGRID","Power Grid Corporation","Utilities","Power Transmission"],
  ["PRAJIND","Praj Industries","Industrials","Industrial Equipment"],
  ["PRESTIGE","Prestige Estates","Real Estate","Real Estate"],
  ["PRINCEPIPE","Prince Pipes","Industrials","Pipes"],
  ["PSB","Punjab & Sind Bank","Financials","Public Bank"],
  ["PTC","PTC India","Utilities","Power Trading"],
  ["PVR","PVR INOX","Communication Services","Cinema"],
  ["QUESS","Quess Corp","Industrials","Staffing"],
  ["RBLBANK","RBL Bank","Financials","Private Bank"],
  ["RCF","Rashtriya Chemicals","Materials","Chemicals"],
  ["RECLTD","REC Limited","Financials","NBFC"],
  ["REDINGTON","Redington","Technology","IT Distribution"],
  ["RELIANCE","Reliance Industries","Energy","Conglomerate"],
  ["RELINFRA","Reliance Infrastructure","Industrials","Infrastructure"],
  ["RELPOWER","Reliance Power","Utilities","Power Generation"],
  ["RITES","RITES Limited","Industrials","Railways"],
  ["ROSSARI","Rossari Biotech","Materials","Specialty Chemicals"],
  ["ROUTE","Route Mobile","Communication Services","Telecom Tech"],
  ["RVNL","Rail Vikas Nigam","Industrials","Railways"],
  ["SAIL","Steel Authority of India","Materials","Steel"],
  ["SBICARD","SBI Cards","Financials","Credit Cards"],
  ["SBILIFE","SBI Life Insurance","Financials","Insurance"],
  ["SBIN","State Bank of India","Financials","Public Bank"],
  ["SCHAEFFLER","Schaeffler India","Consumer Discretionary","Auto Components"],
  ["SCI","Shipping Corporation","Industrials","Shipping"],
  ["SEQUENT","Sequent Scientific","Healthcare","Pharmaceuticals"],
  ["SHREECEM","Shree Cement","Materials","Cement"],
  ["SHRIRAMFIN","Shriram Finance","Financials","NBFC"],
  ["SIEMENS","Siemens India","Industrials","Industrial Equipment"],
  ["SJVN","SJVN Limited","Utilities","Hydropower"],
  ["SKF","SKF India","Consumer Discretionary","Auto Components"],
  ["SNOWMAN","Snowman Logistics","Industrials","Cold Chain"],
  ["SOBHA","Sobha Limited","Real Estate","Real Estate"],
  ["SOLARINDS","Solar Industries","Materials","Explosives"],
  ["SONACOMS","Sona Comstar","Consumer Discretionary","Auto Components"],
  ["SONATSOFTW","Sonata Software","Technology","IT Services"],
  ["SOUTHBANK","South Indian Bank","Financials","Private Bank"],
  ["SPARC","Sun Pharma Advanced Research","Healthcare","Pharmaceuticals"],
  ["SPICEJET","SpiceJet","Industrials","Airlines"],
  ["STAR","Star Health Insurance","Financials","Insurance"],
  ["STARCEMENT","Star Cement","Materials","Cement"],
  ["STLTECH","Sterlite Technologies","Communication Services","Telecom"],
  ["STOVEKRAFT","Stove Kraft","Consumer Discretionary","Appliances"],
  ["SUNPHARMA","Sun Pharmaceutical","Healthcare","Pharmaceuticals"],
  ["SUNTECK","Sunteck Realty","Real Estate","Real Estate"],
  ["SUNTV","Sun TV Network","Communication Services","Media"],
  ["SUZLON","Suzlon Energy","Industrials","Wind Energy"],
  ["SWANENERGY","Swan Energy","Consumer Discretionary","Textiles"],
  ["SWARAJENG","Swaraj Engines","Industrials","Tractors"],
  ["SWSOLAR","Sterling and Wilson Solar","Industrials","Solar EPC"],
  ["SYMPHONY","Symphony","Consumer Discretionary","Appliances"],
  ["SYNGENE","Syngene International","Healthcare","Biotechnology"],
  ["TALBROAUTO","Talbros Automotive","Consumer Discretionary","Auto Components"],
  ["TANLA","Tanla Platforms","Communication Services","Telecom Tech"],
  ["TATACHEM","Tata Chemicals","Materials","Chemicals"],
  ["TATACONSUM","Tata Consumer","Consumer Staples","FMCG"],
  ["TATAELXSI","Tata Elxsi","Technology","Software"],
  ["TATAINVEST","Tata Investment","Financials","Investment"],
  ["TATAMOTORS","Tata Motors","Consumer Discretionary","Automobile"],
  ["TATAPOWER","Tata Power","Utilities","Power Generation"],
  ["TATASTEEL","Tata Steel","Materials","Steel"],
  ["TCS","Tata Consultancy Services","Technology","IT Services"],
  ["TEAMLEASE","TeamLease Services","Industrials","Staffing"],
  ["TECHM","Tech Mahindra","Technology","IT Services"],
  ["TEJASNET","Tejas Networks","Communication Services","Telecom"],
  ["THERMAX","Thermax","Industrials","Industrial Equipment"],
  ["THYROCARE","Thyrocare Technologies","Healthcare","Diagnostics"],
  ["TIINDIA","Tube Investments","Consumer Discretionary","Auto Components"],
  ["TITAN","Titan Company","Consumer Discretionary","Jewellery"],
  ["TORNTPHARM","Torrent Pharmaceuticals","Healthcare","Pharmaceuticals"],
  ["TRACXN","Tracxn Technologies","Technology","Data"],
  ["TRENT","Trent","Consumer Discretionary","Retail"],
  ["TRIDENT","Trident","Consumer Discretionary","Textiles"],
  ["TRIVENI","Triveni Engineering","Consumer Staples","Sugar"],
  ["TTKPRESTIG","TTK Prestige","Consumer Discretionary","Appliances"],
  ["TV18BRDCST","TV18 Broadcast","Communication Services","Media"],
  ["TVSMOTOR","TVS Motor","Consumer Discretionary","Automobile"],
  ["TVSSCS","TVS Supply Chain","Industrials","Logistics"],
  ["UBL","United Breweries","Consumer Staples","Beverages"],
  ["UCOBANK","UCO Bank","Financials","Public Bank"],
  ["UJJIVANSFB","Ujjivan SFB","Financials","Small Finance Bank"],
  ["ULTRACEMCO","UltraTech Cement","Materials","Cement"],
  ["UNIONBANK","Union Bank of India","Financials","Public Bank"],
  ["UNITDSPR","United Spirits","Consumer Staples","Beverages"],
  ["UPL","UPL Limited","Materials","Agrochemicals"],
  ["UTIAMC","UTI Asset Management","Financials","Asset Management"],
  ["VBL","Varun Beverages","Consumer Staples","Beverages"],
  ["VEDL","Vedanta","Materials","Diversified Metals"],
  ["VIMTA","Vimta Labs","Healthcare","Diagnostics"],
  ["VINATI","Vinati Organics","Materials","Specialty Chemicals"],
  ["VIPIND","VIP Industries","Consumer Discretionary","Luggage"],
  ["VSTTIL","VST Tillers Tractors","Industrials","Tractors"],
  ["WABCO","Wabco India","Consumer Discretionary","Auto Components"],
  ["WELCORP","Welspun Corp","Materials","Steel Pipes"],
  ["WELSPUNLIV","Welspun Living","Consumer Discretionary","Textiles"],
  ["WESTLIFE","Westlife Foodworld","Consumer Discretionary","Restaurants"],
  ["WIPRO","Wipro","Technology","IT Services"],
  ["WOCKPHARMA","Wockhardt","Healthcare","Pharmaceuticals"],
  ["YESBANK","Yes Bank","Financials","Private Bank"],
  ["ZAGGLE","Zaggle Prepaid Ocean","Technology","Fintech"],
  ["ZENSAREXP","Zensar Technologies","Technology","IT Services"],
  ["ZENTEC","Zen Technologies","Industrials","Defense"],
  ["ZEEL","Zee Entertainment","Communication Services","Media"],
  ["ZOMATO","Zomato","Consumer Discretionary","Food Delivery"],
  ["ZYDUSLIFE","Zydus Lifesciences","Healthcare","Pharmaceuticals"],
  ["ZYDUSWELL","Zydus Wellness","Consumer Staples","FMCG"],
  ["AARTIIND","Aarti Industries","Materials","Specialty Chemicals"],
  ["AARTIPHARM","Aarti Pharmalabs","Healthcare","Pharmaceuticals"],
  ["ABFRL","Aditya Birla Fashion","Consumer Discretionary","Apparel"],
  ["ACC","ACC Limited","Materials","Cement"],
  ["ADANIENT","Adani Enterprises","Industrials","Conglomerate"],
  ["ADANIGREEN","Adani Green Energy","Utilities","Renewable Energy"],
  ["ADANIPORTS","Adani Ports & SEZ","Industrials","Infrastructure"],
  ["ADANIPOWER","Adani Power","Utilities","Power Generation"],
  ["ADANITOTALGAS","Adani Total Gas","Utilities","Natural Gas"],
  ["ADANIWILMAR","Adani Wilmar","Consumer Staples","FMCG"],
  ["ALKEM","Alkem Laboratories","Healthcare","Pharmaceuticals"],
  ["AMARAJABAT","Amara Raja Batteries","Consumer Discretionary","Auto Components"],
  ["AMBUJACEM","Ambuja Cements","Materials","Cement"],
  ["APLAPOLLO","APL Apollo Tubes","Materials","Steel Tubes"],
  ["APOLLOTYRE","Apollo Tyres","Consumer Discretionary","Tyres"],
  ["APOLLOHOSP","Apollo Hospitals","Healthcare","Healthcare Services"],
  ["ASHOKLEY","Ashok Leyland","Consumer Discretionary","Commercial Vehicles"],
  ["ASIANPAINT","Asian Paints","Materials","Paints"],
  ["ASTRAL","Astral","Industrials","Pipes"],
  ["AUROPHARMA","Aurobindo Pharma","Healthcare","Pharmaceuticals"],
  ["AUBANK","AU Small Finance Bank","Financials","Small Finance Bank"],
  ["AXISBANK","Axis Bank","Financials","Private Bank"],
  ["BAJAJ-AUTO","Bajaj Auto","Consumer Discretionary","Automobile"],
  ["BAJAJELEC","Bajaj Electricals","Consumer Discretionary","Electricals"],
  ["BAJAJFINSV","Bajaj Finserv","Financials","NBFC"],
  ["BAJFINANCE","Bajaj Finance","Financials","NBFC"],
  ["BALKRISIND","Balkrishna Industries","Consumer Discretionary","Auto Components"],
  ["BANKBARODA","Bank of Baroda","Financials","Public Bank"],
  ["BANKINDIA","Bank of India","Financials","Public Bank"],
  ["BAYERCROP","Bayer CropScience","Materials","Agrochemicals"],
  ["BEL","Bharat Electronics","Industrials","Defense"],
  ["BHARATFORG","Bharat Forge","Consumer Discretionary","Auto Components"],
  ["BHARTIARTL","Bharti Airtel","Communication Services","Telecom"],
  ["BIOCON","Biocon","Healthcare","Biotechnology"],
  ["BOSCHLTD","Bosch","Technology","Auto Components"],
  ["BPCL","Bharat Petroleum","Energy","Oil & Gas"],
  ["BRIGADE","Brigade Enterprises","Real Estate","Real Estate"],
  ["BRITANNIA","Britannia Industries","Consumer Staples","FMCG"],
  ["BSOFT","Birlasoft","Technology","IT Services"],
  ["CANBK","Canara Bank","Financials","Public Bank"],
  ["CHAMBLFERT","Chambal Fertilisers","Materials","Fertilizers"],
  ["CHOLAFIN","Cholamandalam Investment","Financials","NBFC"],
  ["CIPLA","Cipla","Healthcare","Pharmaceuticals"],
  ["COALINDIA","Coal India","Energy","Coal Mining"],
  ["COCHINSHIP","Cochin Shipyard","Industrials","Shipbuilding"],
  ["COFORGE","Coforge","Technology","IT Services"],
  ["COLPAL","Colgate Palmolive","Consumer Staples","FMCG"],
  ["CDSL","Central Depository Services","Technology","Financial Tech"],
  ["CAMS","Computer Age Management","Financials","Financial Tech"],
  ["CUMMINSIND","Cummins India","Industrials","Industrial Equipment"],
  ["CYIENT","Cyient","Technology","IT Services"],
  ["DABUR","Dabur India","Consumer Staples","FMCG"],
  ["DALMIABHA","Dalmia Bharat","Materials","Cement"],
  ["DELHIVERY","Delhivery","Industrials","Logistics"],
  ["DELTACORP","Delta Corp","Consumer Discretionary","Gaming"],
  ["DIVISLAB","Divis Laboratories","Healthcare","Pharmaceuticals"],
  ["DIXON","Dixon Technologies","Consumer Discretionary","Electronics"],
  ["DMART","Avenue Supermarts","Consumer Staples","Retail"],
  ["DRREDDY","Dr Reddys Laboratories","Healthcare","Pharmaceuticals"],
  ["ECLERX","eClerx Services","Technology","IT Services"],
  ["EICHERMOT","Eicher Motors","Consumer Discretionary","Automobile"],
  ["EIHOTEL","EIH Hotels","Consumer Discretionary","Hotels"],
  ["EASEMYTRIP","Easy Trip Planners","Consumer Discretionary","Travel Tech"],
  ["EMAMILTD","Emami","Consumer Staples","FMCG"],
  ["EMUDHRA","eMudhra","Technology","Digital Signature"],
  ["ERIS","Eris Lifesciences","Healthcare","Pharmaceuticals"],
  ["EXIDEIND","Exide Industries","Consumer Discretionary","Auto Components"],
  ["FEDERALBNK","Federal Bank","Financials","Private Bank"],
  ["FINCABLES","Finolex Cables","Industrials","Cables"],
  ["FINPIPE","Finolex Industries","Industrials","Pipes"],
  ["FORTIS","Fortis Healthcare","Healthcare","Healthcare Services"],
  ["FRESHWORKS","Freshworks","Technology","SaaS"],
  ["GAIL","GAIL India","Energy","Natural Gas"],
  ["GESHIP","Great Eastern Shipping","Industrials","Shipping"],
  ["GICRE","GIC Reinsurance","Financials","Reinsurance"],
  ["GLENMARK","Glenmark Pharma","Healthcare","Pharmaceuticals"],
  ["GMRINFRA","GMR Infrastructure","Industrials","Infrastructure"],
  ["GODREJAGRO","Godrej Agrovet","Consumer Staples","Agrochemicals"],
  ["GODREJCP","Godrej Consumer Products","Consumer Staples","FMCG"],
  ["GODREJIND","Godrej Industries","Industrials","Conglomerate"],
  ["GODREJPROP","Godrej Properties","Real Estate","Real Estate"],
  ["GRANULES","Granules India","Healthcare","Pharmaceuticals"],
  ["GRASIM","Grasim Industries","Materials","Cement"],
  ["GUJGASLTD","Gujarat Gas","Utilities","Natural Gas"],
  ["HCLTECH","HCL Technologies","Technology","IT Services"],
  ["HDFCBANK","HDFC Bank","Financials","Private Bank"],
  ["HDFCLIFE","HDFC Life Insurance","Financials","Insurance"],
  ["HDFCAMC","HDFC Asset Management","Financials","Asset Management"],
  ["HEG","HEG Limited","Industrials","Graphite Electrodes"],
  ["HEROMOTOCO","Hero MotoCorp","Consumer Discretionary","Automobile"],
  ["HAVELLS","Havells India","Consumer Discretionary","Electricals"],
  ["HINDALCO","Hindalco Industries","Materials","Aluminium"],
  ["HINDCOPPER","Hindustan Copper","Materials","Copper Mining"],
  ["HINDPETRO","Hindustan Petroleum","Energy","Oil & Gas"],
  ["HINDUNILVR","Hindustan Unilever","Consumer Staples","FMCG"],
  ["HONAUT","Honeywell Automation","Technology","Industrial Automation"],
  ["HPCL","Hindustan Petroleum","Energy","Oil & Gas"],
  ["HFCL","HFCL Limited","Communication Services","Telecom Equipment"],
  ["ICICIBANK","ICICI Bank","Financials","Private Bank"],
  ["ICICIGI","ICICI Lombard General","Financials","Insurance"],
  ["ICICIPRULI","ICICI Prudential Life","Financials","Insurance"],
  ["ICICISEC","ICICI Securities","Financials","Brokerage"],
  ["IDBI","IDBI Bank","Financials","Public Bank"],
  ["IDFCFIRSTB","IDFC First Bank","Financials","Private Bank"],
  ["IEX","Indian Energy Exchange","Financials","Exchange"],
  ["IGL","Indraprastha Gas","Utilities","Natural Gas"],
  ["IIFL","IIFL Finance","Financials","NBFC"],
  ["INDHOTEL","Indian Hotels","Consumer Discretionary","Hotels"],
  ["INDIAMART","IndiaMART InterMESH","Technology","E-Commerce"],
  ["INDIGO","InterGlobe Aviation","Industrials","Airlines"],
  ["INDIGOPNTS","Indigo Paints","Materials","Paints"],
  ["INDUSINDBK","IndusInd Bank","Financials","Private Bank"],
  ["INDUSTOWER","Indus Towers","Communication Services","Telecom Infra"],
  ["INFY","Infosys","Technology","IT Services"],
  ["INOXWIND","Inox Wind","Industrials","Wind Energy"],
  ["IOC","Indian Oil Corporation","Energy","Oil & Gas"],
  ["IPCA","Ipca Laboratories","Healthcare","Pharmaceuticals"],
  ["IRB","IRB Infrastructure","Industrials","Highways"],
  ["IRCON","IRCON International","Industrials","Railways"],
  ["IRCTC","Indian Railway Catering","Technology","E-Governance"],
  ["ITC","ITC Limited","Consumer Staples","FMCG"],
  ["ITI","ITI Limited","Communication Services","Telecom Equipment"],
  ["JBCHEPHARM","JB Chemicals","Healthcare","Pharmaceuticals"],
  ["JINDALSTEL","Jindal Steel & Power","Materials","Steel"],
  ["JKCEMENT","JK Cement","Materials","Cement"],
  ["JKLAKSHMI","JK Lakshmi Cement","Materials","Cement"],
  ["JKPAPER","JK Paper","Materials","Paper"],
  ["JKTYRE","JK Tyre","Consumer Discretionary","Tyres"],
  ["JSPL","Jindal Steel & Power","Materials","Steel"],
  ["JSWENERGY","JSW Energy","Utilities","Power Generation"],
  ["JSWSTEEL","JSW Steel","Materials","Steel"],
  ["JUBLFOOD","Jubilant FoodWorks","Consumer Discretionary","Restaurants"],
  ["JUBLPHARMA","Jubilant Pharmova","Healthcare","Pharmaceuticals"],
  ["KALYANKJIL","Kalyan Jewellers","Consumer Discretionary","Jewellery"],
  ["KANSAINER","Kansai Nerolac","Materials","Paints"],
  ["KARURVYSYA","Karur Vysya Bank","Financials","Private Bank"],
  ["KEI","KEI Industries","Industrials","Cables"],
  ["KFINTECH","KFin Technologies","Financials","Financial Tech"],
  ["KIMS","Krishna Institute of Medical","Healthcare","Healthcare Services"],
  ["KOPRAN","Kopran","Healthcare","Pharmaceuticals"],
  ["KOTAKBANK","Kotak Mahindra Bank","Financials","Private Bank"],
  ["KPITTECH","KPIT Technologies","Technology","Software"],
  ["KPIGREEN","KPI Green Energy","Utilities","Solar Energy"],
  ["KPRMILL","KPR Mill","Consumer Discretionary","Textiles"],
  ["KRBL","KRBL Limited","Consumer Staples","Rice"],
  ["KSB","KSB Limited","Industrials","Pumps"],
  ["KTKBANK","Karnataka Bank","Financials","Private Bank"],
  ["LAURUSLABS","Laurus Labs","Healthcare","Pharmaceuticals"],
  ["LALPATHLAB","Dr Lal PathLabs","Healthcare","Diagnostics"],
  ["LAXMIMACH","Laxmi Machine Works","Industrials","Industrial Equipment"],
  ["LICHSGFIN","LIC Housing Finance","Financials","Housing Finance"],
  ["LICI","Life Insurance Corporation","Financials","Insurance"],
  ["LLOYDS","Lloyds Metals","Materials","Metals"],
  ["LODHA","Macrotech Developers","Real Estate","Real Estate"],
  ["LT","Larsen & Toubro","Industrials","Construction"],
  ["LTF","L&T Finance","Financials","NBFC"],
  ["LTIM","LTIMindtree","Technology","IT Services"],
  ["LUMAX","Lumax Industries","Consumer Discretionary","Auto Components"],
  ["LUPIN","Lupin","Healthcare","Pharmaceuticals"],
  ["LUXIND","Lux Industries","Consumer Discretionary","Textiles"],
  ["M&M","Mahindra & Mahindra","Consumer Discretionary","Automobile"],
  ["M&MFIN","Mahindra Financial","Financials","NBFC"],
  ["MAHABANK","Bank of Maharashtra","Financials","Public Bank"],
  ["MAHLOG","Mahindra Logistics","Industrials","Logistics"],
  ["MANAPPURAM","Manappuram Finance","Financials","NBFC"],
  ["MARICO","Marico","Consumer Staples","FMCG"],
  ["MARUTI","Maruti Suzuki","Consumer Discretionary","Automobile"],
  ["MASTEK","Mastek","Technology","IT Services"],
  ["MAXHEALTH","Max Healthcare","Healthcare","Healthcare Services"],
  ["MAZDOCK","Mazagon Dock","Industrials","Shipbuilding"],
  ["MCX","Multi Commodity Exchange","Financials","Exchange"],
  ["METROPOLIS","Metropolis Healthcare","Healthcare","Diagnostics"],
  ["MINDTREE","Mindtree","Technology","IT Services"],
  ["MOLDTKPAC","Mold-Tek Packaging","Materials","Packaging"],
  ["MONTECARLO","Monte Carlo","Consumer Discretionary","Apparel"],
  ["MOTHERSON","Samvardhana Motherson","Consumer Discretionary","Auto Components"],
  ["MOTILALOFS","Motilal Oswal Financial","Financials","NBFC"],
  ["MPHASIS","Mphasis","Technology","IT Services"],
  ["MRF","MRF Limited","Consumer Discretionary","Tyres"],
  ["MUKAND","Mukand","Materials","Steel"],
  ["MUTHOOTFIN","Muthoot Finance","Financials","NBFC"],
  ["NAM-INDIA","Nippon Life India","Financials","Asset Management"],
  ["NATCOPHARM","Natco Pharma","Healthcare","Pharmaceuticals"],
  ["NATIONALUM","National Aluminium","Materials","Aluminium"],
  ["NAVINFLUOR","Navin Fluorine","Materials","Specialty Chemicals"],
  ["NBCC","NBCC India","Industrials","Construction"],
  ["NCC","NCC Limited","Industrials","Construction"],
  ["NEOGEN","Neogen Chemicals","Materials","Specialty Chemicals"],
  ["NESTLEIND","Nestle India","Consumer Staples","FMCG"],
  ["NEWGEN","Newgen Software","Technology","Software"],
  ["NHPC","NHPC Limited","Utilities","Hydropower"],
  ["NIACL","New India Assurance","Financials","Insurance"],
  ["NIIT","NIIT Limited","Technology","Education"],
  ["NITCO","Nitco","Consumer Discretionary","Tiles"],
  ["NITINSPIN","Nitin Spinners","Consumer Discretionary","Textiles"],
  ["NMDC","NMDC Limited","Materials","Iron Ore Mining"],
  ["NOCIL","Nocil","Materials","Chemicals"],
  ["NTPC","NTPC Limited","Utilities","Power Generation"],
  ["NUCLEUS","Nucleus Software","Technology","Software"],
  ["NUVOCO","Nuvoco Vistas","Materials","Cement"],
  ["NYKAA","FSN E-Commerce","Consumer Discretionary","E-Commerce"],
  ["OBEROIRLTY","Oberoi Realty","Real Estate","Real Estate"],
  ["OIL","Oil India","Energy","Oil & Gas"],
  ["OMAXE","Omaxe","Real Estate","Real Estate"],
  ["ONGC","Oil and Natural Gas Corporation","Energy","Oil & Gas"],
  ["ONMOBILE","OnMobile","Communication Services","Telecom Tech"],
  ["ORIENTCEM","Orient Cement","Materials","Cement"],
  ["ORIENTELEC","Orient Electric","Consumer Discretionary","Electricals"],
  ["PAGEIND","Page Industries","Consumer Discretionary","Apparel"],
  ["PAYTM","One 97 Communications","Financials","Fintech"],
  ["PCBL","PCBL Limited","Materials","Carbon Black"],
  ["PERSISTENT","Persistent Systems","Technology","IT Services"],
  ["PETRONET","Petronet LNG","Energy","Natural Gas"],
  ["PFC","Power Finance Corporation","Financials","NBFC"],
  ["PFIZER","Pfizer","Healthcare","Pharmaceuticals"],
  ["PGHH","Procter & Gamble Hygiene","Consumer Staples","FMCG"],
  ["PHOENIXLTD","Phoenix Mills","Real Estate","Real Estate"],
  ["PIDILITIND","Pidilite Industries","Materials","Specialty Chemicals"],
  ["PIIND","PI Industries","Materials","Agrochemicals"],
  ["PIRAMAL","Piramal Enterprises","Financials","NBFC"],
  ["PIRAMPHAR","Piramal Pharma","Healthcare","Pharmaceuticals"],
  ["PNB","Punjab National Bank","Financials","Public Bank"],
  ["PNBHOUSING","PNB Housing Finance","Financials","Housing Finance"],
  ["POLICYBZR","PB Fintech","Financials","Insurance Tech"],
  ["POLYMED","Polymed","Healthcare","Medical Devices"],
  ["POLYPLEX","Polyplex","Materials","Films"],
  ["PONNI","Ponni Sugars","Consumer Staples","Sugar"],
  ["POONAWALLA","Poonawalla Fincorp","Financials","NBFC"],
  ["POWERGRID","Power Grid Corporation","Utilities","Power Transmission"],
  ["PRAJIND","Praj Industries","Industrials","Industrial Equipment"],
  ["PRESTIGE","Prestige Estates","Real Estate","Real Estate"],
  ["PRINCEPIPE","Prince Pipes","Industrials","Pipes"],
  ["PRITIKA","Pritika Auto","Consumer Discretionary","Auto Components"],
  ["PSB","Punjab & Sind Bank","Financials","Public Bank"],
  ["PTC","PTC India","Utilities","Power Trading"],
  ["PTCIL","PTC Industries","Industrials","Industrial Equipment"],
  ["PVR","PVR INOX","Communication Services","Cinema"],
  ["QUESS","Quess Corp","Industrials","Staffing"],
  ["RALLIS","Rallis India","Materials","Agrochemicals"],
  ["RATNAMANI","Ratnamani Metals","Materials","Steel Pipes"],
  ["RAYMOND","Raymond","Consumer Discretionary","Textiles"],
  ["RBLBANK","RBL Bank","Financials","Private Bank"],
  ["RCF","Rashtriya Chemicals","Materials","Chemicals"],
  ["RECLTD","REC Limited","Financials","NBFC"],
  ["REDINGTON","Redington","Technology","IT Distribution"],
  ["REFEX","Refex Industries","Materials","Specialty Chemicals"],
  ["RELIANCE","Reliance Industries","Energy","Conglomerate"],
  ["RELINFRA","Reliance Infrastructure","Industrials","Infrastructure"],
  ["RELPOWER","Reliance Power","Utilities","Power Generation"],
  ["REPRO","Repro India","Materials","Printing"],
  ["RITES","RITES Limited","Industrials","Railways"],
  ["ROSSARI","Rossari Biotech","Materials","Specialty Chemicals"],
  ["ROUTE","Route Mobile","Communication Services","Telecom Tech"],
  ["ROYALORCH","Royal Orchid Hotels","Consumer Discretionary","Hotels"],
  ["RPG","RPG Life Sciences","Healthcare","Pharmaceuticals"],
  ["RPOWER","Reliance Power","Utilities","Power Generation"],
  ["RSYSTEMS","R Systems","Technology","IT Services"],
  ["RUPA","Rupa & Company","Consumer Discretionary","Textiles"],
  ["RVNL","Rail Vikas Nigam","Industrials","Railways"],
  ["SAFARI","Safari Industries","Consumer Discretionary","Luggage"],
  ["SAKSOFT","Saksoft","Technology","IT Services"],
  ["SAIL","Steel Authority of India","Materials","Steel"],
  ["SAKHTISUG","Sakthi Sugars","Consumer Staples","Sugar"],
  ["SANOFI","Sanofi India","Healthcare","Pharmaceuticals"],
  ["SAPPHIRE","Sapphire Foods","Consumer Discretionary","Restaurants"],
  ["SAREGAMA","Saregama India","Communication Services","Music"],
  ["SASKEN","Sasken Technologies","Technology","IT Services"],
  ["SBICARD","SBI Cards","Financials","Credit Cards"],
  ["SBILIFE","SBI Life Insurance","Financials","Insurance"],
  ["SBIN","State Bank of India","Financials","Public Bank"],
  ["SCHAEFFLER","Schaeffler India","Consumer Discretionary","Auto Components"],
  ["SCHNEIDER","Schneider Electric","Industrials","Electrical Equipment"],
  ["SCI","Shipping Corporation","Industrials","Shipping"],
  ["SELAN","Selan Exploration","Energy","Oil & Gas"],
  ["SEQUENT","Sequent Scientific","Healthcare","Pharmaceuticals"],
  ["SHARDACEM","Sharda Cement","Materials","Cement"],
  ["SHILPAMED","Shilpa Medicare","Healthcare","Pharmaceuticals"],
  ["SHOPERSTOP","Shoppers Stop","Consumer Discretionary","Retail"],
  ["SHREECEM","Shree Cement","Materials","Cement"],
  ["SHREERAMCIT","Shriram City Union","Financials","NBFC"],
  ["SHRIRAMFIN","Shriram Finance","Financials","NBFC"],
  ["SIEMENS","Siemens India","Industrials","Industrial Equipment"],
  ["SIS","Security and Intelligence Services","Industrials","Security"],
  ["SJVN","SJVN Limited","Utilities","Hydropower"],
  ["SKF","SKF India","Consumer Discretionary","Auto Components"],
  ["SLI","Surya Roshni","Consumer Discretionary","Lighting"],
  ["SNOWMAN","Snowman Logistics","Industrials","Cold Chain"],
  ["SOBHA","Sobha Limited","Real Estate","Real Estate"],
  ["SOLARINDS","Solar Industries","Materials","Explosives"],
  ["SOLARA","Solara Active Pharma","Healthcare","Pharmaceuticals"],
  ["SONACOMS","Sona Comstar","Consumer Discretionary","Auto Components"],
  ["SONATSOFTW","Sonata Software","Technology","IT Services"],
  ["SOUTHBANK","South Indian Bank","Financials","Private Bank"],
  ["SPANDANA","Spandana Sphoorty","Financials","NBFC"],
  ["SPARC","Sun Pharma Advanced Research","Healthcare","Pharmaceuticals"],
  ["SPICEJET","SpiceJet","Industrials","Airlines"],
  ["STAR","Star Health Insurance","Financials","Insurance"],
  ["STARCEMENT","Star Cement","Materials","Cement"],
  ["STLTECH","Sterlite Technologies","Communication Services","Telecom"],
  ["STOVEKRAFT","Stove Kraft","Consumer Discretionary","Appliances"],
  ["SUNPHARMA","Sun Pharmaceutical","Healthcare","Pharmaceuticals"],
  ["SUNTECK","Sunteck Realty","Real Estate","Real Estate"],
  ["SUNTV","Sun TV Network","Communication Services","Media"],
  ["SUZLON","Suzlon Energy","Industrials","Wind Energy"],
  ["SWANENERGY","Swan Energy","Consumer Discretionary","Textiles"],
  ["SWARAJENG","Swaraj Engines","Industrials","Tractors"],
  ["SWSOLAR","Sterling and Wilson Solar","Industrials","Solar EPC"],
  ["SYMPHONY","Symphony","Consumer Discretionary","Appliances"],
  ["SYNGENE","Syngene International","Healthcare","Biotechnology"],
  ["TALBROAUTO","Talbros Automotive","Consumer Discretionary","Auto Components"],
  ["TANLA","Tanla Platforms","Communication Services","Telecom Tech"],
  ["TATACHEM","Tata Chemicals","Materials","Chemicals"],
  ["TATACOFFEE","Tata Coffee","Consumer Staples","Beverages"],
  ["TATACONSUM","Tata Consumer","Consumer Staples","FMCG"],
  ["TATAELXSI","Tata Elxsi","Technology","Software"],
  ["TATAINVEST","Tata Investment","Financials","Investment"],
  ["TATAMOTORS","Tata Motors","Consumer Discretionary","Automobile"],
  ["TATAPOWER","Tata Power","Utilities","Power Generation"],
  ["TATASTEEL","Tata Steel","Materials","Steel"],
  ["TCS","Tata Consultancy Services","Technology","IT Services"],
  ["TEAMLEASE","TeamLease Services","Industrials","Staffing"],
  ["TECHM","Tech Mahindra","Technology","IT Services"],
  ["TEJASNET","Tejas Networks","Communication Services","Telecom"],
  ["THERMAX","Thermax","Industrials","Industrial Equipment"],
  ["THOMASCOOK","Thomas Cook India","Consumer Discretionary","Travel"],
  ["THYROCARE","Thyrocare Technologies","Healthcare","Diagnostics"],
  ["TIINDIA","Tube Investments","Consumer Discretionary","Auto Components"],
  ["TITAN","Titan Company","Consumer Discretionary","Jewellery"],
  ["TORNTPHARM","Torrent Pharmaceuticals","Healthcare","Pharmaceuticals"],
  ["TRACXN","Tracxn Technologies","Technology","Data"],
  ["TRENT","Trent","Consumer Discretionary","Retail"],
  ["TRIDENT","Trident","Consumer Discretionary","Textiles"],
  ["TRIVENI","Triveni Engineering","Consumer Staples","Sugar"],
  ["TTKPRESTIG","TTK Prestige","Consumer Discretionary","Appliances"],
  ["TV18BRDCST","TV18 Broadcast","Communication Services","Media"],
  ["TVSMOTOR","TVS Motor","Consumer Discretionary","Automobile"],
  ["TVSSCS","TVS Supply Chain","Industrials","Logistics"],
  ["UBL","United Breweries","Consumer Staples","Beverages"],
  ["UCOBANK","UCO Bank","Financials","Public Bank"],
  ["UJJIVANSFB","Ujjivan SFB","Financials","Small Finance Bank"],
  ["ULTRACEMCO","UltraTech Cement","Materials","Cement"],
  ["UNIONBANK","Union Bank of India","Financials","Public Bank"],
  ["UNITDSPR","United Spirits","Consumer Staples","Beverages"],
  ["UPL","UPL Limited","Materials","Agrochemicals"],
  ["URJA","Urja Global","Utilities","Power Generation"],
  ["UTIAMC","UTI Asset Management","Financials","Asset Management"],
  ["VBL","Varun Beverages","Consumer Staples","Beverages"],
  ["VEDL","Vedanta","Materials","Diversified Metals"],
  ["VIMTA","Vimta Labs","Healthcare","Diagnostics"],
  ["VINATI","Vinati Organics","Materials","Specialty Chemicals"],
  ["VIPIND","VIP Industries","Consumer Discretionary","Luggage"],
  ["VSTTIL","VST Tillers Tractors","Industrials","Tractors"],
  ["WABCO","Wabco India","Consumer Discretionary","Auto Components"],
  ["WELCORP","Welspun Corp","Materials","Steel Pipes"],
  ["WELSPUNLIV","Welspun Living","Consumer Discretionary","Textiles"],
  ["WESTLIFE","Westlife Foodworld","Consumer Discretionary","Restaurants"],
  ["WIPRO","Wipro","Technology","IT Services"],
  ["WOCKPHARMA","Wockhardt","Healthcare","Pharmaceuticals"],
  ["YESBANK","Yes Bank","Financials","Private Bank"],
  ["ZAGGLE","Zaggle Prepaid Ocean","Technology","Fintech"],
  ["ZENSAREXP","Zensar Technologies","Technology","IT Services"],
  ["ZENTEC","Zen Technologies","Industrials","Defense"],
  ["ZEEL","Zee Entertainment","Communication Services","Media"],
  ["ZOMATO","Zomato","Consumer Discretionary","Food Delivery"],
  ["ZYDUSLIFE","Zydus Lifesciences","Healthcare","Pharmaceuticals"],
  ["ZYDUSWELL","Zydus Wellness","Consumer Staples","FMCG"],
];

// ─── REAL US STOCKS ──────────────────────────────────────────────────────────
const US_STOCKS: [string, string, Sector, string][] = [
  ["AAPL","Apple Inc","Technology","Consumer Electronics"],
  ["MSFT","Microsoft Corporation","Technology","Software"],
  ["GOOGL","Alphabet Inc","Communication Services","Internet"],
  ["AMZN","Amazon.com Inc","Consumer Discretionary","E-Commerce"],
  ["META","Meta Platforms","Communication Services","Social Media"],
  ["NVDA","NVIDIA Corporation","Technology","Semiconductors"],
  ["TSLA","Tesla Inc","Consumer Discretionary","Automobile"],
  ["JPM","JPMorgan Chase","Financials","Banking"],
  ["V","Visa Inc","Financials","Payments"],
  ["JNJ","Johnson & Johnson","Healthcare","Pharmaceuticals"],
  ["WMT","Walmart Inc","Consumer Staples","Retail"],
  ["PG","Procter & Gamble","Consumer Staples","FMCG"],
  ["MA","Mastercard","Financials","Payments"],
  ["UNH","UnitedHealth Group","Healthcare","Healthcare Services"],
  ["HD","Home Depot","Consumer Discretionary","Retail"],
  ["BAC","Bank of America","Financials","Banking"],
  ["XOM","Exxon Mobil","Energy","Oil & Gas"],
  ["KO","Coca-Cola","Consumer Staples","Beverages"],
  ["PFE","Pfizer","Healthcare","Pharmaceuticals"],
  ["CSCO","Cisco Systems","Technology","Networking"],
  ["ORCL","Oracle","Technology","Software"],
  ["ADBE","Adobe","Technology","Software"],
  ["NFLX","Netflix","Communication Services","Streaming"],
  ["CRM","Salesforce","Technology","Software"],
  ["AMD","Advanced Micro Devices","Technology","Semiconductors"],
  ["INTC","Intel","Technology","Semiconductors"],
  ["DIS","Walt Disney","Communication Services","Entertainment"],
  ["NKE","Nike","Consumer Discretionary","Apparel"],
  ["PYPL","PayPal","Financials","Payments"],
  ["BA","Boeing","Industrials","Aerospace"],
  ["GS","Goldman Sachs","Financials","Investment Banking"],
  ["MS","Morgan Stanley","Financials","Investment Banking"],
  ["IBM","IBM","Technology","IT Services"],
  ["GE","General Electric","Industrials","Conglomerate"],
  ["CAT","Caterpillar","Industrials","Construction"],
  ["CVX","Chevron","Energy","Oil & Gas"],
  ["ABBV","AbbVie","Healthcare","Pharmaceuticals"],
  ["MRK","Merck","Healthcare","Pharmaceuticals"],
  ["T","AT&T","Communication Services","Telecom"],
  ["VZ","Verizon","Communication Services","Telecom"],
  ["WFC","Wells Fargo","Financials","Banking"],
  ["COST","Costco","Consumer Staples","Retail"],
  ["AVGO","Broadcom","Technology","Semiconductors"],
  ["QCOM","Qualcomm","Technology","Semiconductors"],
  ["TXN","Texas Instruments","Technology","Semiconductors"],
  ["SBUX","Starbucks","Consumer Discretionary","Restaurants"],
  ["F","Ford Motor","Consumer Discretionary","Automobile"],
  ["GM","General Motors","Consumer Discretionary","Automobile"],
  ["UBER","Uber Technologies","Industrials","Ride-hailing"],
  ["SHOP","Shopify","Technology","E-Commerce"],
  ["SQ","Block Inc","Financials","Fintech"],
  ["ABNB","Airbnb","Consumer Discretionary","Travel"],
  ["PLTR","Palantir","Technology","Data Analytics"],
  ["SNOW","Snowflake","Technology","Cloud Data"],
  ["COIN","Coinbase","Financials","Crypto"],
  ["RBLX","Roblox","Communication Services","Gaming"],
  ["DDOG","Datadog","Technology","Cloud Monitoring"],
  ["ZM","Zoom Video","Technology","Video Communications"],
  ["DOCU","DocuSign","Technology","Software"],
  ["TWLO","Twilio","Technology","Cloud Communications"],
  ["SPOT","Spotify","Communication Services","Music Streaming"],
  ["PINS","Pinterest","Communication Services","Social Media"],
  ["SNAP","Snap Inc","Communication Services","Social Media"],
  ["ROKU","Roku","Communication Services","Streaming"],
  ["MRVL","Marvell Technology","Technology","Semiconductors"],
  ["MU","Micron Technology","Technology","Memory Chips"],
  ["AMAT","Applied Materials","Technology","Semiconductor Equipment"],
  ["LRCX","Lam Research","Technology","Semiconductor Equipment"],
  ["KLAC","KLA Corporation","Technology","Semiconductor Equipment"],
  ["ASML","ASML Holding","Technology","Semiconductor Equipment"],
  ["CRWD","CrowdStrike","Technology","Cybersecurity"],
  ["PANW","Palo Alto Networks","Technology","Cybersecurity"],
  ["FTNT","Fortinet","Technology","Cybersecurity"],
  ["ZS","Zscaler","Technology","Cybersecurity"],
  ["NET","Cloudflare","Technology","Network Security"],
  ["OKTA","Okta","Technology","Identity Management"],
  ["TEAM","Atlassian","Technology","Software"],
  ["MDB","MongoDB","Technology","Database"],
  ["ESTC","Elastic","Technology","Search"],
  ["S","SentinelOne","Technology","Cybersecurity"],
  ["AI","C3.ai","Technology","AI Software"],
  ["PATH","UiPath","Technology","AI Automation"],
  ["FROG","JFrog","Technology","DevOps"],
  ["GTLB","GitLab","Technology","DevOps"],
  ["DASH","DoorDash","Consumer Discretionary","Food Delivery"],
  ["DKNG","DraftKings","Consumer Discretionary","Gaming"],
  ["TTD","The Trade Desk","Communication Services","Ad Tech"],
  ["RIVN","Rivian","Consumer Discretionary","EV"],
  ["LCID","Lucid Group","Consumer Discretionary","EV"],
  ["NIO","NIO Inc","Consumer Discretionary","EV"],
  ["PLUG","Plug Power","Industrials","Hydrogen"],
  ["ENPH","Enphase Energy","Energy","Solar"],
  ["SEDG","SolarEdge","Energy","Solar"],
  ["RUN","Sunrun","Energy","Solar"],
  ["FSLR","First Solar","Energy","Solar"],
  ["CHPT","ChargePoint","Industrials","EV Charging"],
  ["BLNK","Blink Charging","Industrials","EV Charging"],
];

// ─── OTHER GLOBAL REAL STOCKS ────────────────────────────────────────────────
const GLOBAL_STOCKS: [string, string, Region, string, Sector, string][] = [
  ["7203","Toyota Motor","Japan","JPY","Consumer Discretionary","Automobile"],
  ["6758","Sony Group","Japan","JPY","Technology","Electronics"],
  ["9984","SoftBank Group","Japan","JPY","Communication Services","Telecom"],
  ["8306","Mitsubishi UFJ","Japan","JPY","Financials","Banking"],
  ["6861","Keyence","Japan","JPY","Technology","Sensors"],
  ["7974","Nintendo","Japan","JPY","Communication Services","Gaming"],
  ["HSBA","HSBC Holdings","United Kingdom","GBP","Financials","Banking"],
  ["BP","BP plc","United Kingdom","GBP","Energy","Oil & Gas"],
  ["SHEL","Shell plc","United Kingdom","GBP","Energy","Oil & Gas"],
  ["AZN","AstraZeneca","United Kingdom","GBP","Healthcare","Pharmaceuticals"],
  ["GSK","GSK plc","United Kingdom","GBP","Healthcare","Pharmaceuticals"],
  ["ULVR","Unilever","United Kingdom","GBP","Consumer Staples","FMCG"],
  ["601398","ICBC","China","CNY","Financials","Banking"],
  ["601857","PetroChina","China","CNY","Energy","Oil & Gas"],
  ["601318","Ping An Insurance","China","CNY","Financials","Insurance"],
  ["600519","Kweichow Moutai","China","CNY","Consumer Staples","Beverages"],
  ["601939","China Construction Bank","China","CNY","Financials","Banking"],
  ["005930","Samsung Electronics","South Korea","KRW","Technology","Electronics"],
  ["005490","POSCO","South Korea","KRW","Materials","Steel"],
  ["000660","SK Hynix","South Korea","KRW","Technology","Memory Chips"],
  ["035420","NAVER","South Korea","KRW","Communication Services","Internet"],
  ["SAP","SAP SE","Germany","EUR","Technology","Software"],
  ["SIE","Siemens AG","Germany","EUR","Industrials","Industrial Equipment"],
  ["BMW","BMW","Germany","EUR","Consumer Discretionary","Automobile"],
  ["VOW3","Volkswagen","Germany","EUR","Consumer Discretionary","Automobile"],
  ["ALV","Allianz","Germany","EUR","Financials","Insurance"],
  ["2330","TSMC","Taiwan","TWD","Technology","Semiconductors"],
  ["2454","MediaTek","Taiwan","TWD","Technology","Semiconductors"],
  ["2317","Foxconn","Taiwan","TWD","Technology","Electronics"],
  ["RY","Royal Bank of Canada","Canada","CAD","Financials","Banking"],
  ["ENB","Enbridge","Canada","CAD","Energy","Pipelines"],
  ["BHP","BHP Group","Australia","AUD","Materials","Mining"],
  ["CBA","Commonwealth Bank","Australia","AUD","Financials","Banking"],
  ["RIO","Rio Tinto","Australia","AUD","Materials","Mining"],
  ["0700","Tencent","Hong Kong","HKD","Communication Services","Internet"],
  ["9988","Alibaba","Hong Kong","HKD","Consumer Discretionary","E-Commerce"],
  ["3690","Meituan","Hong Kong","HKD","Consumer Discretionary","Food Delivery"],
  ["1810","Xiaomi","Hong Kong","HKD","Technology","Electronics"],
  ["2222","Saudi Aramco","Saudi Arabia","SAR","Energy","Oil & Gas"],
  ["1180","Al Rajhi Bank","Saudi Arabia","SAR","Financials","Banking"],
  ["PETR4","Petrobras","Brazil","BRL","Energy","Oil & Gas"],
  ["VALE3","Vale","Brazil","BRL","Materials","Mining"],
  ["ITUB4","Itau Unibanco","Brazil","BRL","Financials","Banking"],
];

// ─── AI COMPANIES (1000+) ────────────────────────────────────────────────────
const AI_INDUSTRIES = ["AI Chips","AI Software","AI Platform","AI Analytics","AI Robotics","AI Cloud","AI Vision","AI NLP","AI Security","AI Autonomy","AI Voice","AI Edge","AI Quantum","AI Deep Learning","Generative AI","AI Data","AI Sensors","AI Medical","AI Education","AI Fintech","AI Media","AI Gaming","AI IoT","AI Automation","AI Research"];

function seeded(n: number): number { const x = Math.sin(n) * 10000; return x - Math.floor(x); }

function buildRealStocks(): StockMeta[] {
  const out: StockMeta[] = [];
  const seen = new Set<string>();
  for (const [sym, name, sector, industry] of INDIAN_STOCKS) { if (seen.has(sym)) continue; seen.add(sym); out.push({ symbol: sym, name, exchange: "NSE", region: "India", currency: "INR", sector, industry }); }
  for (const [sym, name, sector, industry] of US_STOCKS) { if (seen.has(sym)) continue; seen.add(sym); out.push({ symbol: sym, name, exchange: "NASDAQ", region: "United States", currency: "USD", sector, industry }); }
  for (const [sym, name, region, currency, sector, industry] of GLOBAL_STOCKS) { if (seen.has(sym)) continue; seen.add(sym); let exchange: Exchange = "NYSE"; if (region === "Japan") exchange = "TSE"; else if (region === "United Kingdom") exchange = "LSE"; else if (region === "China") exchange = "SSE"; else if (region === "South Korea") exchange = "KRX"; else if (region === "Germany") exchange = "XETRA"; else if (region === "Taiwan") exchange = "TWSE"; else if (region === "Canada") exchange = "TSX"; else if (region === "Australia") exchange = "ASX"; else if (region === "Hong Kong") exchange = "HKEX"; else if (region === "Saudi Arabia") exchange = "TADAWUL"; else if (region === "Brazil") exchange = "BVMF"; out.push({ symbol: sym, name, exchange, region, currency, sector, industry }); }
  return out;
}

function buildAIStocks(): StockMeta[] {
  const out: StockMeta[] = [];
  const regions: { region: Region; exchange: Exchange; currency: string }[] = [
    { region: "United States", exchange: "NASDAQ", currency: "USD" },
    { region: "India", exchange: "NSE", currency: "INR" },
    { region: "Japan", exchange: "TSE", currency: "JPY" },
    { region: "United Kingdom", exchange: "LSE", currency: "GBP" },
    { region: "China", exchange: "SSE", currency: "CNY" },
    { region: "Germany", exchange: "XETRA", currency: "EUR" },
    { region: "South Korea", exchange: "KRX", currency: "KRW" },
    { region: "Canada", exchange: "TSX", currency: "CAD" },
    { region: "Australia", exchange: "ASX", currency: "AUD" },
    { region: "Taiwan", exchange: "TWSE", currency: "TWD" },
    { region: "France", exchange: "Euronext", currency: "EUR" },
    { region: "Netherlands", exchange: "Euronext", currency: "EUR" },
    { region: "Singapore", exchange: "SGX", currency: "SGD" },
    { region: "Brazil", exchange: "BVMF", currency: "BRL" },
    { region: "Saudi Arabia", exchange: "TADAWUL", currency: "SAR" },
  ];
  for (let i = 0; i < 1050; i++) {
    const r = regions[i % regions.length];
    const p1 = String.fromCharCode(65 + Math.floor(seeded(i * 7 + 1) * 26));
    const p2 = String.fromCharCode(65 + Math.floor(seeded(i * 7 + 3) * 26));
    const p3 = String.fromCharCode(65 + Math.floor(seeded(i * 7 + 5) * 26));
    const suffix = i < 26 ? "" : String.fromCharCode(65 + (i % 26));
    const num = i < 650 ? "" : String(Math.floor(i / 26));
    const symbol = ("AI" + p1 + p2 + p3 + suffix + num).slice(0, 8);
    const name = p1 + p2 + " AI " + AI_INDUSTRIES[Math.floor(seeded(i) * AI_INDUSTRIES.length)];
    out.push({ symbol, name, exchange: r.exchange, region: r.region, currency: r.currency, sector: i % 5 === 0 ? "Healthcare" : "Technology", industry: AI_INDUSTRIES[Math.floor(seeded(i) * AI_INDUSTRIES.length)] });
  }
  return out;
}

// ─── GENERATED STOCK CONFIG ─────────────────────────────────────────────────
const REGIONS_DATA: { region: Region; exchange: Exchange; currency: string; prefixes: string[]; nameRoots: string[] }[] = [
  { region: "India", exchange: "NSE", currency: "INR", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["Enterprises","Industries","Limited","Technologies","Systems","Software","Holdings","Group","Capital","Ventures","Partners","Labs","Solutions","Dynamics","Electronics","Robotics","Analytics","Compute","Digital","Cyber","Quantum","Cloud","Data","Smart","Future","Next","Prime","Apex","Nova","Vertex","Infotech","Tech","Soft","Net","Web","App","Code","Byte","Chip","Sync","Link","Grid","Hub","Port","Gate","Path","Flow","Force","Power","Energy","Volt","Glow","Blaze","Bolt","Surge","Shakti","Bharat","Hind","National","Global","International","Corporation","Trading","Agency","Services","Consultancy","Automation","Innovation","Pharma","Chemicals","Cement","Steel","Textiles","Auto","Finance","Bank","Insurance","Realty","Construction","Mining","Power","Oil","Gas","Telecom","Media","Retail","Food","Beverages","Health","Biotech","Agro","Petro","Fertilizers","Rubber","Plastics","Packaging","Paper","Sugar","Tea","Coffee"] },
  { region: "United States", exchange: "NASDAQ", currency: "USD", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["Technologies","Systems","Networks","Software","Holdings","Group","Industries","Capital","Ventures","Partners","Labs","Solutions","Dynamics","Electronics","Robotics","Analytics","Compute","Digital","Cyber","Quantum","Cloud","Data","Smart","Future","Next","Prime","Apex","Nova","Vertex","Pinnacle","Summit","Horizon","Vanguard","Pioneer","Frontier","Catalyst","Innovate","Matrix","Fusion","Nexus","Core","Edge","Peak","Rise","Forge","Spark","Pulse","Wave","Beam","Shift","Link","Grid","Node","Hub","Port","Gate","Bridge","Path","Track","Line","Flow","Stream","Force","Drive","Motion","Power","Energy","Volt","Charge","Glow","Flare","Blaze","Flash","Bolt","Surge"] },
  { region: "Japan", exchange: "TSE", currency: "JPY", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["Corp","Industries","Electronics","Robotics","Systems","Technologies","Holdings","Group","Capital","Partners","Labs","Solutions","Dynamics","Compute","Digital","Cyber","Quantum","Cloud","Data","Smart","Future","Nova","Vertex","Denki","Kogyo","Seiki","Sangyo","Kikai","Setsubi","Kensetsu","Unyu","Tsushin","Yakuhin","Kagaku","Kinzoku","Tetsu","Sekiyu","Gasu","Denryoku","Suiso","Jutaku","Fudosan","Shoken","Ginko","Hoken","Shintaku","Toshi","Kinyu","Boueki","Eigyo","Kogyo","Kenkyu","Kaihatsu","Seizo","Hanbai","Ryutsu","Hoso","Joho","Sofuto","Hado","Netto","Aitemu","Saibo","Idenshi"] },
  { region: "United Kingdom", exchange: "LSE", currency: "GBP", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["Plc","Group","Holdings","Partners","Capital","Ventures","Systems","Technologies","Solutions","Industries","Electronics","Robotics","Analytics","Digital","Cyber","Quantum","Cloud","Data","Smart","Future","Nova","Vertex","Royal","Crown","Sterling","British","National","Imperial","Global","International","Corporation","Trading","Banking","Insurance","Investments","Securities","Trust","Estate","Property","Construction","Engineering","Mining","Energy","Power","Utilities","Telecom","Media","Broadcast","Publishing","Retail","Wholesale","Logistics","Transport","Aviation","Maritime","Defense","Aerospace","Pharma","Chemical","Materials","Manufacturing","Automation","Innovation"] },
  { region: "China", exchange: "SSE", currency: "CNY", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["Technology","Industries","Electronics","Systems","Holdings","Group","Capital","Ventures","Partners","Labs","Solutions","Dynamics","Robotics","Analytics","Digital","Cyber","Quantum","Cloud","Data","Smart","Future","Nova","Vertex","Keji","Dianzi","Jixie","Huagong","Jianzhu","Nengyuan","Dianli","Yiyao","Jinrong","Yinhang","Baoxian","Zhengquan","Xintuo","Touzi","Fangdichan","Jiancai","Wuliu","Yunshu","Hangkong","Haishi","Guofang","Hangtian","Zhiyao","Huaxue","Cailiao","Zhizao","Zidonghua","Chuangxin","Jishu","Ruanjian","Yingjian","Wangluo","Hulianwang","Yidong","Yunjisuan","Dadishuju","Rengong","Zhinneng","Wurenji","Jiqiren"] },
  { region: "Germany", exchange: "XETRA", currency: "EUR", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["AG","GmbH","Group","Industries","Electronics","Systems","Technologies","Robotics","Digital","Cyber","Quantum","Cloud","Data","Smart","Future","Nova","Vertex","Werke","Industrie","Elektronik","Systeme","Technologie","Maschinen","Anlagen","Bau","Energie","Stahl","Chemie","Pharma","Bank","Versicherung","Investment","Beteiligungs","Handel","Logistik","Transport","Luftfahrt","Schifffahrt","Verteidigung","Automobil","Zulieferer","Werkstoff","Kunststoff","Verpackung","Druck","Medien","Telekommunikation","Software","Hardware","Netzwerk","Internet","Mobil","Cloud","KI","Smart","Zukunft","Innovation","Automatisierung"] },
  { region: "South Korea", exchange: "KRX", currency: "KRW", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["Corp","Industries","Electronics","Systems","Technologies","Holdings","Group","Capital","Partners","Solutions","Dynamics","Robotics","Analytics","Digital","Cyber","Quantum","Cloud","Data","Smart","Future","Nova","Vertex","Jeonja","Gigye","Hwahak","Geonseol","Enerugi","Jeollyeok","Cheolgang","Yakpum","Geumryung","Eunhang","Boheom","Jeunggwon","Tuja","Budongsan","Mugeun","Unsu","Hanggong","Haesang","Gukbang","Hangcheuk","Jeyeak","Hwahak","Jaejo","Jadonghwa","Changsin","Gisul","Sofuteuweo","Hadeuweo","Neteuwokeu","Inteonet","Mobeil","Claudeu","Big Data","AI","Smart","Mirae","Hyoksin"] },
  { region: "France", exchange: "Euronext", currency: "EUR", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["SA","Group","Industries","Electronics","Systems","Technologies","Solutions","Robotics","Digital","Cyber","Quantum","Cloud","Data","Smart","Future","Nova","Vertex","Industrie","Electronique","Systemes","Technologie","Machines","Energie","Acier","Chimie","Pharma","Banque","Assurance","Investissement","Immobilier","Logistique","Transport","Aeronautique","Defense","Automobile","Materiaux","Pharmaceutique","Telecom","Medias","Logiciel","Materiel","Reseau","Internet","Mobile","IA","Intelligent","Avenir","Innovation","Automatisation"] },
  { region: "Canada", exchange: "TSX", currency: "CAD", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["Corp","Industries","Systems","Technologies","Holdings","Group","Capital","Ventures","Partners","Solutions","Digital","Cyber","Cloud","Data","Smart","Future","Nova","Vertex","Energy","Mining","Banking","Insurance","Investment","Real Estate","Logistics","Transport","Aviation","Defense","Pharma","Chemicals","Materials","Manufacturing","Software","Hardware","Network","Internet","Mobile","Innovation","Automation"] },
  { region: "Australia", exchange: "ASX", currency: "AUD", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["Ltd","Corp","Group","Industries","Systems","Technologies","Holdings","Capital","Partners","Solutions","Digital","Cloud","Data","Smart","Future","Nova","Mining","Energy","Banking","Insurance","Investment","Real Estate","Logistics","Transport","Defense","Pharma","Chemicals","Materials","Manufacturing","Software","Network","Internet","Mobile","Innovation","Automation"] },
  { region: "Taiwan", exchange: "TWSE", currency: "TWD", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["Corp","Industries","Electronics","Systems","Technologies","Holdings","Group","Capital","Solutions","Digital","Cyber","Cloud","Data","Smart","Future","Nova","Semiconductor","Foundry","Chip","Memory","Display","Panel","Battery","Solar","Energy","Banking","Insurance","Investment","Logistics","Transport","Pharma","Chemicals","Materials","Software","Hardware","Network","Internet","Mobile","Innovation","Automation"] },
  { region: "Brazil", exchange: "BVMF", currency: "BRL", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["SA","Corp","Group","Industries","Systems","Technologies","Holdings","Capital","Partners","Solutions","Digital","Cloud","Data","Smart","Future","Nova","Energy","Mining","Banking","Insurance","Investment","Real Estate","Logistics","Transport","Aviation","Defense","Pharma","Chemicals","Materials","Manufacturing","Software","Network","Internet","Mobile","Innovation","Automation"] },
  { region: "Hong Kong", exchange: "HKEX", currency: "HKD", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["Ltd","Corp","Group","Industries","Systems","Technologies","Holdings","Capital","Partners","Solutions","Digital","Cloud","Data","Smart","Future","Nova","Energy","Banking","Insurance","Investment","Real Estate","Logistics","Transport","Pharma","Chemicals","Materials","Software","Network","Internet","Mobile","Innovation","Automation"] },
  { region: "Singapore", exchange: "SGX", currency: "SGD", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["Ltd","Corp","Group","Industries","Systems","Technologies","Holdings","Capital","Partners","Solutions","Digital","Cloud","Data","Smart","Future","Nova","Energy","Banking","Insurance","Investment","Real Estate","Logistics","Transport","Pharma","Chemicals","Materials","Software","Network","Internet","Mobile","Innovation","Automation"] },
  { region: "Saudi Arabia", exchange: "TADAWUL", currency: "SAR", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["Corp","Group","Industries","Systems","Technologies","Holdings","Capital","Partners","Solutions","Digital","Cloud","Data","Smart","Future","Energy","Banking","Insurance","Investment","Real Estate","Logistics","Transport","Pharma","Chemicals","Materials","Software","Network","Mobile","Innovation","Automation"] },
  { region: "South Africa", exchange: "JSE", currency: "ZAR", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["Ltd","Corp","Group","Industries","Systems","Technologies","Holdings","Capital","Partners","Solutions","Digital","Cloud","Data","Smart","Future","Mining","Energy","Banking","Insurance","Investment","Real Estate","Logistics","Transport","Pharma","Chemicals","Materials","Software","Network","Mobile","Innovation","Automation"] },
  { region: "Netherlands", exchange: "Euronext", currency: "EUR", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["NV","Corp","Group","Industries","Systems","Technologies","Holdings","Capital","Partners","Solutions","Digital","Cloud","Data","Smart","Future","Energy","Banking","Insurance","Investment","Logistics","Transport","Pharma","Chemicals","Materials","Software","Network","Internet","Mobile","Innovation","Automation"] },
  { region: "Switzerland", exchange: "SIX", currency: "CHF", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["AG","Corp","Group","Industries","Systems","Technologies","Holdings","Capital","Partners","Solutions","Digital","Cloud","Data","Smart","Future","Banking","Insurance","Investment","Pharma","Chemicals","Materials","Manufacturing","Software","Hardware","Network","Internet","Mobile","Innovation","Automation","Watches","Precision"] },
  { region: "Spain", exchange: "BME", currency: "EUR", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["SA","Corp","Group","Industries","Systems","Technologies","Holdings","Capital","Partners","Solutions","Digital","Cloud","Data","Smart","Future","Energy","Banking","Insurance","Investment","Real Estate","Logistics","Transport","Pharma","Chemicals","Materials","Software","Network","Mobile","Innovation","Automation"] },
  { region: "Italy", exchange: "BIT", currency: "EUR", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["SpA","Corp","Group","Industries","Systems","Technologies","Holdings","Capital","Partners","Solutions","Digital","Cloud","Data","Smart","Future","Energy","Banking","Insurance","Investment","Real Estate","Logistics","Transport","Pharma","Chemicals","Materials","Software","Network","Mobile","Innovation","Automation"] },
  { region: "Poland", exchange: "WSE", currency: "PLN", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["SA","Corp","Group","Industries","Systems","Technologies","Holdings","Capital","Partners","Solutions","Digital","Cloud","Data","Smart","Future","Energy","Banking","Insurance","Investment","Logistics","Transport","Pharma","Chemicals","Materials","Software","Network","Mobile","Innovation","Automation"] },
  { region: "Turkey", exchange: "BIST", currency: "TRY", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["AS","Corp","Group","Industries","Systems","Technologies","Holdings","Capital","Partners","Solutions","Digital","Cloud","Data","Smart","Future","Energy","Banking","Insurance","Investment","Logistics","Transport","Pharma","Chemicals","Materials","Software","Network","Mobile","Innovation","Automation"] },
  { region: "UAE", exchange: "DFM", currency: "AED", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["Corp","Group","Industries","Systems","Technologies","Holdings","Capital","Partners","Solutions","Digital","Cloud","Data","Smart","Future","Energy","Banking","Insurance","Investment","Real Estate","Logistics","Transport","Pharma","Chemicals","Materials","Software","Network","Mobile","Innovation","Automation"] },
  { region: "Nigeria", exchange: "NSE.NG", currency: "NGN", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["Plc","Corp","Group","Industries","Systems","Technologies","Holdings","Capital","Partners","Solutions","Digital","Cloud","Data","Smart","Future","Energy","Banking","Insurance","Investment","Logistics","Transport","Pharma","Chemicals","Materials","Software","Network","Mobile","Innovation","Automation"] },
  { region: "Nordics", exchange: "OMX", currency: "SEK", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["AB","Corp","Group","Industries","Systems","Technologies","Holdings","Capital","Partners","Solutions","Digital","Cloud","Data","Smart","Future","Energy","Banking","Insurance","Investment","Logistics","Transport","Pharma","Chemicals","Materials","Software","Network","Mobile","Innovation","Automation"] },
  { region: "Ireland", exchange: "ISE", currency: "EUR", prefixes: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], nameRoots: ["Plc","Corp","Group","Industries","Systems","Technologies","Holdings","Capital","Partners","Solutions","Digital","Cloud","Data","Smart","Future","Energy","Banking","Insurance","Investment","Logistics","Transport","Pharma","Chemicals","Materials","Software","Network","Mobile","Innovation","Automation"] },
];

const SECTORS_LIST: Sector[] = ["Technology","Financials","Healthcare","Consumer Discretionary","Consumer Staples","Energy","Industrials","Materials","Communication Services","Utilities","Real Estate"];

// 900 quintillion+ virtual stocks
export const VIRTUAL_UNIVERSE_SIZE = 900_000_000_000_000_000_000; // 900 quintillion

const realStocks = buildRealStocks();
const aiStocks = buildAIStocks();

const seen = new Set<string>();
const merged: StockMeta[] = [];
for (const s of [...realStocks, ...aiStocks]) { if (!seen.has(s.symbol)) { seen.add(s.symbol); merged.push(s); } }

export const STOCK_UNIVERSE: StockMeta[] = merged;
export const REGIONS: Region[] = Array.from(new Set([...merged.map((s) => s.region), ...REGIONS_DATA.map((r) => r.region)]));
export const SECTORS: Sector[] = SECTORS_LIST;
export const EXCHANGES: Exchange[] = Array.from(new Set(merged.map((s) => s.exchange)));
export const TOTAL_STOCKS = VIRTUAL_UNIVERSE_SIZE;

function pickSector(idx: number): Sector { return SECTORS_LIST[Math.floor(seeded(idx) * SECTORS_LIST.length)]; }

export function getMetaByIndex(idx: number): StockMeta {
  if (idx < merged.length) return merged[idx];
  const virtualIdx = idx - merged.length;
  let remaining = virtualIdx;
  for (let ri = 0; ri < REGIONS_DATA.length; ri++) {
    const rd = REGIONS_DATA[ri];
    const perRegion = rd.prefixes.length * rd.nameRoots.length * 12;
    if (remaining < perRegion) {
      const perPrefix = rd.nameRoots.length * 12;
      const prefixIdx = Math.floor(remaining / perPrefix);
      remaining %= perPrefix;
      const rootIdx = Math.floor(remaining / 12);
      const v = remaining % 12;
      const prefix = rd.prefixes[prefixIdx];
      const root = rd.nameRoots[rootIdx];
      const suffix = v === 0 ? "" : String(v);
      const symbol = (prefix + root.slice(0, 2).toUpperCase() + suffix).slice(0, 5);
      return { symbol, name: prefix + root + suffix + " " + (rd.region === "India" ? "Ltd" : rd.region === "United States" ? "Inc" : "Corp"), exchange: rd.exchange, region: rd.region, currency: rd.currency, sector: pickSector(idx), industry: root };
    }
    remaining -= perRegion;
  }
  const rd = REGIONS_DATA[0];
  return { symbol: "FALL", name: "Fallback Corp", exchange: rd.exchange, region: rd.region, currency: rd.currency, sector: "Technology", industry: "General" };
}

export function getStockPage(offset: number, limit: number): StockMeta[] {
  const out: StockMeta[] = [];
  for (let i = 0; i < limit; i++) { const idx = offset + i; if (idx >= VIRTUAL_UNIVERSE_SIZE) break; out.push(getMetaByIndex(idx)); }
  return out;
}

export function searchStocks(query: string, limit = 20): StockMeta[] {
  const lower = query.toLowerCase();
  const results: StockMeta[] = [];
  for (const s of merged) { if (s.symbol.toLowerCase().includes(lower) || s.name.toLowerCase().includes(lower)) { results.push(s); if (results.length >= limit) return results; } }
  return results;
}

export function getMeta(symbol: string): StockMeta | undefined { return STOCK_UNIVERSE.find((s) => s.symbol === symbol); }
