import type { StockMeta, Region, Sector, Exchange } from './types';

// A broad universe spanning major world markets. Deterministic data is
// generated per-symbol so the app is fully functional offline; a live feed can
// be layered in by replacing the data service.
export const STOCK_UNIVERSE: StockMeta[] = [
  // ===== United States — NYSE / NASDAQ (60) =====
  { symbol: 'AAPL', name: 'Apple Inc.', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Technology', industry: 'Consumer Electronics' },
  { symbol: 'MSFT', name: 'Microsoft Corporation', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Technology', industry: 'Software' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Technology', industry: 'Semiconductors' },
  { symbol: 'AMZN', name: 'Amazon.com, Inc.', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Consumer Discretionary', industry: 'Internet Retail' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. Class A', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Communication Services', industry: 'Internet Content' },
  { symbol: 'META', name: 'Meta Platforms, Inc.', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Communication Services', industry: 'Internet Content' },
  { symbol: 'TSLA', name: 'Tesla, Inc.', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Consumer Discretionary', industry: 'Auto Manufacturers' },
  { symbol: 'BRK.B', name: 'Berkshire Hathaway Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Financials', industry: 'Insurance—Diversified' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Financials', industry: 'Banks—Diversified' },
  { symbol: 'V', name: 'Visa Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Financials', industry: 'Credit Services' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Healthcare', industry: 'Drug Manufacturers' },
  { symbol: 'WMT', name: 'Walmart Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Consumer Staples', industry: 'Discount Stores' },
  { symbol: 'XOM', name: 'Exxon Mobil Corporation', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Energy', industry: 'Oil & Gas Integrated' },
  { symbol: 'UNH', name: 'UnitedHealth Group Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Healthcare', industry: 'Healthcare Plans' },
  { symbol: 'HD', name: 'The Home Depot, Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Consumer Discretionary', industry: 'Home Improvement' },
  { symbol: 'PG', name: 'Procter & Gamble Company', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Consumer Staples', industry: 'Household Products' },
  { symbol: 'MA', name: 'Mastercard Incorporated', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Financials', industry: 'Credit Services' },
  { symbol: 'KO', name: 'The Coca-Cola Company', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Consumer Staples', industry: 'Beverages' },
  { symbol: 'DIS', name: 'The Walt Disney Company', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Communication Services', industry: 'Entertainment' },
  { symbol: 'NFLX', name: 'Netflix, Inc.', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Communication Services', industry: 'Entertainment' },
  { symbol: 'AMD', name: 'Advanced Micro Devices, Inc.', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Technology', industry: 'Semiconductors' },
  { symbol: 'INTC', name: 'Intel Corporation', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Technology', industry: 'Semiconductors' },
  { symbol: 'BAC', name: 'Bank of America Corporation', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Financials', industry: 'Banks—Diversified' },
  { symbol: 'PFE', name: 'Pfizer Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Healthcare', industry: 'Drug Manufacturers' },
  { symbol: 'CVX', name: 'Chevron Corporation', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Energy', industry: 'Oil & Gas Integrated' },
  { symbol: 'AVGO', name: 'Broadcom Inc.', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Technology', industry: 'Semiconductors' },
  { symbol: 'PEP', name: 'PepsiCo, Inc.', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Consumer Staples', industry: 'Beverages' },
  { symbol: 'COST', name: 'Costco Wholesale Corporation', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Consumer Staples', industry: 'Discount Stores' },
  { symbol: 'ABBV', name: 'AbbVie Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Healthcare', industry: 'Drug Manufacturers' },
  { symbol: 'MRK', name: 'Merck & Co., Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Healthcare', industry: 'Drug Manufacturers' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Healthcare', industry: 'Diagnostics' },
  { symbol: 'ABT', name: 'Abbott Laboratories', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Healthcare', industry: 'Medical Devices' },
  { symbol: 'CRM', name: 'Salesforce, Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Technology', industry: 'Software' },
  { symbol: 'ADBE', name: 'Adobe Inc.', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Technology', industry: 'Software' },
  { symbol: 'ORCL', name: 'Oracle Corporation', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Technology', industry: 'Software' },
  { symbol: 'CSCO', name: 'Cisco Systems, Inc.', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Technology', industry: 'Communication Equipment' },
  { symbol: 'MCD', name: "McDonald's Corporation", exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Consumer Discretionary', industry: 'Restaurants' },
  { symbol: 'NKE', name: 'NIKE, Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Consumer Discretionary', industry: 'Footwear & Accessories' },
  { symbol: 'PYPL', name: 'PayPal Holdings, Inc.', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Financials', industry: 'Credit Services' },
  { symbol: 'QCOM', name: 'QUALCOMM Incorporated', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Technology', industry: 'Semiconductors' },
  { symbol: 'TXN', name: 'Texas Instruments Incorporated', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Technology', industry: 'Semiconductors' },
  { symbol: 'LOW', name: "Lowe's Companies, Inc.", exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Consumer Discretionary', industry: 'Home Improvement' },
  { symbol: 'UPS', name: 'United Parcel Service, Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Industrials', industry: 'Integrated Freight' },
  { symbol: 'BA', name: 'The Boeing Company', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { symbol: 'CAT', name: 'Caterpillar Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Industrials', industry: 'Farm & Heavy Machinery' },
  { symbol: 'GS', name: 'The Goldman Sachs Group, Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Financials', industry: 'Capital Markets' },
  { symbol: 'MS', name: 'Morgan Stanley', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Financials', industry: 'Capital Markets' },
  { symbol: 'IBM', name: 'International Business Machines', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Technology', industry: 'IT Services' },
  { symbol: 'GE', name: 'GE Aerospace', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { symbol: 'F', name: 'Ford Motor Company', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Consumer Discretionary', industry: 'Auto Manufacturers' },
  { symbol: 'GM', name: 'General Motors Company', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Consumer Discretionary', industry: 'Auto Manufacturers' },
  { symbol: 'SBUX', name: 'Starbucks Corporation', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Consumer Discretionary', industry: 'Restaurants' },
  { symbol: 'UBER', name: 'Uber Technologies, Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Technology', industry: 'Software' },
  { symbol: 'SHOP', name: 'Shopify Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Technology', industry: 'Software' },
  { symbol: 'SQ', name: 'Block, Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Financials', industry: 'Credit Services' },
  { symbol: 'ZM', name: 'Zoom Video Communications, Inc.', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Technology', industry: 'Software' },
  { symbol: 'SNAP', name: 'Snap Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Communication Services', industry: 'Internet Content' },
  { symbol: 'PINS', name: 'Pinterest, Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Communication Services', industry: 'Internet Content' },
  { symbol: 'ROKU', name: 'Roku, Inc.', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Communication Services', industry: 'Entertainment' },
  { symbol: 'PLTR', name: 'Palantir Technologies Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Technology', industry: 'Software' },
  { symbol: 'COIN', name: 'Coinbase Global, Inc.', exchange: 'NASDAQ', region: 'United States', currency: 'USD', sector: 'Financials', industry: 'Capital Markets' },
  { symbol: 'DASH', name: 'DoorDash, Inc.', exchange: 'NYSE', region: 'United States', currency: 'USD', sector: 'Consumer Discretionary', industry: 'Internet Retail' },

  // ===== India — NSE / BSE (40) =====
  { symbol: 'RELIANCE', name: 'Reliance Industries Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Energy', industry: 'Oil & Gas Refining' },
  { symbol: 'TCS', name: 'Tata Consultancy Services Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Technology', industry: 'IT Services' },
  { symbol: 'HDFCBANK', name: 'HDFC Bank Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Financials', industry: 'Banks—Regional' },
  { symbol: 'INFY', name: 'Infosys Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Technology', industry: 'IT Services' },
  { symbol: 'ICICIBANK', name: 'ICICI Bank Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Financials', industry: 'Banks—Regional' },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Communication Services', industry: 'Telecom' },
  { symbol: 'SBIN', name: 'State Bank of India', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Financials', industry: 'Banks—Regional' },
  { symbol: 'ITC', name: 'ITC Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Consumer Staples', industry: 'Tobacco' },
  { symbol: 'LT', name: 'Larsen & Toubro Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Industrials', industry: 'Engineering & Construction' },
  { symbol: 'AXISBANK', name: 'Axis Bank Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Financials', industry: 'Banks—Regional' },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Financials', industry: 'Banks—Regional' },
  { symbol: 'MARUTI', name: 'Maruti Suzuki India Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Consumer Discretionary', industry: 'Auto Manufacturers' },
  { symbol: 'ASIANPAINT', name: 'Asian Paints Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Materials', industry: 'Specialty Chemicals' },
  { symbol: 'SUNPHARMA', name: 'Sun Pharmaceutical Industries Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Healthcare', industry: 'Drug Manufacturers' },
  { symbol: 'TATAMOTORS', name: 'Tata Motors Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Consumer Discretionary', industry: 'Auto Manufacturers' },
  { symbol: 'WIPRO', name: 'Wipro Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Technology', industry: 'IT Services' },
  { symbol: 'HCLTECH', name: 'HCL Technologies Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Technology', industry: 'IT Services' },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Materials', industry: 'Building Materials' },
  { symbol: 'TITAN', name: 'Titan Company Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Consumer Discretionary', industry: 'Luxury Goods' },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Financials', industry: 'Credit Services' },
  { symbol: 'NESTLEIND', name: 'Nestlé India Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Consumer Staples', industry: 'Packaged Foods' },
  { symbol: 'ONGC', name: 'Oil & Natural Gas Corporation Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Energy', industry: 'Oil & Gas E&P' },
  { symbol: 'NTPC', name: 'NTPC Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Utilities', industry: 'Utilities—Regulated' },
  { symbol: 'POWERGRID', name: 'Power Grid Corporation of India', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Utilities', industry: 'Utilities—Regulated' },
  { symbol: 'TATASTEEL', name: 'Tata Steel Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Materials', industry: 'Steel' },
  { symbol: 'JSWSTEEL', name: 'JSW Steel Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Materials', industry: 'Steel' },
  { symbol: 'HINDALCO', name: 'Hindalco Industries Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Materials', industry: 'Aluminum' },
  { symbol: 'COALINDIA', name: 'Coal India Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Energy', industry: 'Thermal Coal' },
  { symbol: 'DRREDDY', name: "Dr. Reddy's Laboratories Ltd.", exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Healthcare', industry: 'Drug Manufacturers' },
  { symbol: 'CIPLA', name: 'Cipla Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Healthcare', industry: 'Drug Manufacturers' },
  { symbol: 'GRASIM', name: 'Grasim Industries Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Materials', industry: 'Chemicals' },
  { symbol: 'ADANIENT', name: 'Adani Enterprises Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Industrials', industry: 'Conglomerates' },
  { symbol: 'ADANIPORTS', name: 'Adani Ports & Special Economic Zone', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Industrials', industry: 'Marine Ports' },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Financials', industry: 'Insurance—Diversified' },
  { symbol: 'TECHM', name: 'Tech Mahindra Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Technology', industry: 'IT Services' },
  { symbol: 'DIVISLAB', name: 'Divi\u2019s Laboratories Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Healthcare', industry: 'Drug Manufacturers' },
  { symbol: 'BRITANNIA', name: 'Britannia Industries Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Consumer Staples', industry: 'Packaged Foods' },
  { symbol: 'EICHERMOT', name: 'Eicher Motors Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Consumer Discretionary', industry: 'Auto Manufacturers' },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Consumer Discretionary', industry: 'Auto Manufacturers' },
  { symbol: 'M&M', name: 'Mahindra & Mahindra Ltd.', exchange: 'NSE', region: 'India', currency: 'INR', sector: 'Consumer Discretionary', industry: 'Auto Manufacturers' },

  // ===== Europe (45) =====
  { symbol: 'MC.PA', name: 'LVMH Moët Hennessy Louis Vuitton', exchange: 'Euronext', region: 'France', currency: 'EUR', sector: 'Consumer Discretionary', industry: 'Luxury Goods' },
  { symbol: 'OR.PA', name: "L'Oréal S.A.", exchange: 'Euronext', region: 'France', currency: 'EUR', sector: 'Consumer Staples', industry: 'Personal Products' },
  { symbol: 'AIR.PA', name: 'Airbus SE', exchange: 'Euronext', region: 'France', currency: 'EUR', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { symbol: 'SAN.PA', name: 'Sanofi S.A.', exchange: 'Euronext', region: 'France', currency: 'EUR', sector: 'Healthcare', industry: 'Drug Manufacturers' },
  { symbol: 'TTE.PA', name: 'TotalEnergies SE', exchange: 'Euronext', region: 'France', currency: 'EUR', sector: 'Energy', industry: 'Oil & Gas Integrated' },
  { symbol: 'BN.PA', name: 'Danone S.A.', exchange: 'Euronext', region: 'France', currency: 'EUR', sector: 'Consumer Staples', industry: 'Packaged Foods' },
  { symbol: 'SAP.DE', name: 'SAP SE', exchange: 'XETRA', region: 'Germany', currency: 'EUR', sector: 'Technology', industry: 'Software' },
  { symbol: 'SIE.DE', name: 'Siemens AG', exchange: 'XETRA', region: 'Germany', currency: 'EUR', sector: 'Industrials', industry: 'Conglomerates' },
  { symbol: 'ALV.DE', name: 'Allianz SE', exchange: 'XETRA', region: 'Germany', currency: 'EUR', sector: 'Financials', industry: 'Insurance—Diversified' },
  { symbol: 'BAS.DE', name: 'BASF SE', exchange: 'XETRA', region: 'Germany', currency: 'EUR', sector: 'Materials', industry: 'Chemicals' },
  { symbol: 'BAYN.DE', name: 'Bayer AG', exchange: 'XETRA', region: 'Germany', currency: 'EUR', sector: 'Healthcare', industry: 'Drug Manufacturers' },
  { symbol: 'DTE.DE', name: 'Deutsche Telekom AG', exchange: 'XETRA', region: 'Germany', currency: 'EUR', sector: 'Communication Services', industry: 'Telecom' },
  { symbol: 'VOW3.DE', name: 'Volkswagen AG', exchange: 'XETRA', region: 'Germany', currency: 'EUR', sector: 'Consumer Discretionary', industry: 'Auto Manufacturers' },
  { symbol: 'BMW.DE', name: 'Bayerische Motoren Werke AG', exchange: 'XETRA', region: 'Germany', currency: 'EUR', sector: 'Consumer Discretionary', industry: 'Auto Manufacturers' },
  { symbol: 'DBK.DE', name: 'Deutsche Bank AG', exchange: 'XETRA', region: 'Germany', currency: 'EUR', sector: 'Financials', industry: 'Banks—Diversified' },
  { symbol: 'NESN.SW', name: 'Nestlé S.A.', exchange: 'SIX', region: 'Switzerland', currency: 'CHF', sector: 'Consumer Staples', industry: 'Packaged Foods' },
  { symbol: 'NOVN.SW', name: 'Novartis AG', exchange: 'SIX', region: 'Switzerland', currency: 'CHF', sector: 'Healthcare', industry: 'Drug Manufacturers' },
  { symbol: 'ROG.SW', name: 'Roche Holding AG', exchange: 'SIX', region: 'Switzerland', currency: 'CHF', sector: 'Healthcare', industry: 'Drug Manufacturers' },
  { symbol: 'ABB.SW', name: 'ABB Ltd.', exchange: 'SIX', region: 'Switzerland', currency: 'CHF', sector: 'Industrials', industry: 'Electrical Equipment' },
  { symbol: 'GIVN.SW', name: 'Givaudan SA', exchange: 'SIX', region: 'Switzerland', currency: 'CHF', sector: 'Materials', industry: 'Specialty Chemicals' },
  { symbol: 'ASML.AS', name: 'ASML Holding N.V.', exchange: 'Euronext', region: 'Netherlands', currency: 'EUR', sector: 'Technology', industry: 'Semiconductors' },
  { symbol: 'INGA.AS', name: 'ING Groep N.V.', exchange: 'Euronext', region: 'Netherlands', currency: 'EUR', sector: 'Financials', industry: 'Banks—Diversified' },
  { symbol: 'RDSA.AS', name: 'Shell plc', exchange: 'Euronext', region: 'Netherlands', currency: 'EUR', sector: 'Energy', industry: 'Oil & Gas Integrated' },
  { symbol: 'SHEL.L', name: 'Shell plc', exchange: 'LSE', region: 'United Kingdom', currency: 'GBP', sector: 'Energy', industry: 'Oil & Gas Integrated' },
  { symbol: 'AZN.L', name: 'AstraZeneca PLC', exchange: 'LSE', region: 'United Kingdom', currency: 'GBP', sector: 'Healthcare', industry: 'Drug Manufacturers' },
  { symbol: 'HSBA.L', name: 'HSBC Holdings plc', exchange: 'LSE', region: 'United Kingdom', currency: 'GBP', sector: 'Financials', industry: 'Banks—Diversified' },
  { symbol: 'ULVR.L', name: 'Unilever PLC', exchange: 'LSE', region: 'United Kingdom', currency: 'GBP', sector: 'Consumer Staples', industry: 'Household Products' },
  { symbol: 'BP.L', name: 'BP p.l.c.', exchange: 'LSE', region: 'United Kingdom', currency: 'GBP', sector: 'Energy', industry: 'Oil & Gas Integrated' },
  { symbol: 'GSK.L', name: 'GSK plc', exchange: 'LSE', region: 'United Kingdom', currency: 'GBP', sector: 'Healthcare', industry: 'Drug Manufacturers' },
  { symbol: 'RIO.L', name: 'Rio Tinto Group', exchange: 'LSE', region: 'United Kingdom', currency: 'GBP', sector: 'Materials', industry: 'Other Industrial Metals' },
  { symbol: 'BARC.L', name: 'Barclays PLC', exchange: 'LSE', region: 'United Kingdom', currency: 'GBP', sector: 'Financials', industry: 'Banks—Diversified' },
  { symbol: 'LLOY.L', name: 'Lloyds Banking Group plc', exchange: 'LSE', region: 'United Kingdom', currency: 'GBP', sector: 'Financials', industry: 'Banks—Regional' },
  { symbol: 'DGE.L', name: 'Diageo plc', exchange: 'LSE', region: 'United Kingdom', currency: 'GBP', sector: 'Consumer Staples', industry: 'Beverages' },
  { symbol: 'BATS.L', name: 'British American Tobacco p.l.c.', exchange: 'LSE', region: 'United Kingdom', currency: 'GBP', sector: 'Consumer Staples', industry: 'Tobacco' },
  { symbol: 'IBE.MC', name: 'Iberdrola, S.A.', exchange: 'BME', region: 'Spain', currency: 'EUR', sector: 'Utilities', industry: 'Utilities—Renewable' },
  { symbol: 'ITX.MC', name: 'Inditex, S.A.', exchange: 'BME', region: 'Spain', currency: 'EUR', sector: 'Consumer Discretionary', industry: 'Apparel Retail' },
  { symbol: 'SAN.MC', name: 'Banco Santander, S.A.', exchange: 'BME', region: 'Spain', currency: 'EUR', sector: 'Financials', industry: 'Banks—Diversified' },
  { symbol: 'ENEL.MI', name: 'Enel S.p.A.', exchange: 'BIT', region: 'Italy', currency: 'EUR', sector: 'Utilities', industry: 'Utilities—Regulated' },
  { symbol: 'ENI.MI', name: 'Eni S.p.A.', exchange: 'BIT', region: 'Italy', currency: 'EUR', sector: 'Energy', industry: 'Oil & Gas Integrated' },
  { symbol: 'STLAM.MI', name: 'Stellantis N.V.', exchange: 'BIT', region: 'Italy', currency: 'EUR', sector: 'Consumer Discretionary', industry: 'Auto Manufacturers' },
  { symbol: 'ISP.MI', name: 'Intesa Sanpaolo S.p.A.', exchange: 'BIT', region: 'Italy', currency: 'EUR', sector: 'Financials', industry: 'Banks—Diversified' },
  { symbol: 'NDA-FI.HE', name: 'Nokia Oyj', exchange: 'OMX', region: 'Nordics', currency: 'EUR', sector: 'Technology', industry: 'Communication Equipment' },
  { symbol: 'ERIC-B.ST', name: 'Telefonaktiebolaget LM Ericsson', exchange: 'OMX', region: 'Nordics', currency: 'SEK', sector: 'Technology', industry: 'Communication Equipment' },
  { symbol: 'VOLV-B.ST', name: 'Volvo, AB', exchange: 'OMX', region: 'Nordics', currency: 'SEK', sector: 'Industrials', industry: 'Farm & Heavy Machinery' },
  { symbol: 'NOVO-B.CO', name: 'Novo Nordisk A/S', exchange: 'OMX', region: 'Nordics', currency: 'DKK', sector: 'Healthcare', industry: 'Drug Manufacturers' },
  { symbol: 'PKN.WA', name: 'PKN Orlen S.A.', exchange: 'WSE', region: 'Poland', currency: 'PLN', sector: 'Energy', industry: 'Oil & Gas Refining' },

  // ===== Asia-Pacific (40) =====
  { symbol: '7203.T', name: 'Toyota Motor Corporation', exchange: 'TSE', region: 'Japan', currency: 'JPY', sector: 'Consumer Discretionary', industry: 'Auto Manufacturers' },
  { symbol: '6758.T', name: 'Sony Group Corporation', exchange: 'TSE', region: 'Japan', currency: 'JPY', sector: 'Technology', industry: 'Consumer Electronics' },
  { symbol: '9984.T', name: 'SoftBank Group Corp.', exchange: 'TSE', region: 'Japan', currency: 'JPY', sector: 'Communication Services', industry: 'Telecom' },
  { symbol: '8306.T', name: 'Mitsubishi UFJ Financial Group', exchange: 'TSE', region: 'Japan', currency: 'JPY', sector: 'Financials', industry: 'Banks—Diversified' },
  { symbol: '7974.T', name: 'Nintendo Co., Ltd.', exchange: 'TSE', region: 'Japan', currency: 'JPY', sector: 'Communication Services', industry: 'Electronic Gaming' },
  { symbol: '6861.T', name: 'Keyence Corporation', exchange: 'TSE', region: 'Japan', currency: 'JPY', sector: 'Technology', industry: 'Electronic Components' },
  { symbol: '4519.T', name: 'Chugai Pharmaceutical Co., Ltd.', exchange: 'TSE', region: 'Japan', currency: 'JPY', sector: 'Healthcare', industry: 'Drug Manufacturers' },
  { symbol: '0700.HK', name: 'Tencent Holdings Ltd.', exchange: 'HKEX', region: 'Hong Kong', currency: 'HKD', sector: 'Communication Services', industry: 'Internet Content' },
  { symbol: '9988.HK', name: 'Alibaba Group Holding Ltd.', exchange: 'HKEX', region: 'Hong Kong', currency: 'HKD', sector: 'Consumer Discretionary', industry: 'Internet Retail' },
  { symbol: '3690.HK', name: 'Meituan', exchange: 'HKEX', region: 'Hong Kong', currency: 'HKD', sector: 'Consumer Discretionary', industry: 'Internet Retail' },
  { symbol: '1299.HK', name: 'AIA Group Limited', exchange: 'HKEX', region: 'Hong Kong', currency: 'HKD', sector: 'Financials', industry: 'Insurance—Life' },
  { symbol: '600519.SS', name: 'Kweichow Moutai Co., Ltd.', exchange: 'SSE', region: 'China', currency: 'CNY', sector: 'Consumer Staples', industry: 'Beverages' },
  { symbol: '601318.SS', name: 'Ping An Insurance Co.', exchange: 'SSE', region: 'China', currency: 'CNY', sector: 'Financials', industry: 'Insurance—Diversified' },
  { symbol: '600036.SS', name: 'China Merchants Bank Co., Ltd.', exchange: 'SSE', region: 'China', currency: 'CNY', sector: 'Financials', industry: 'Banks—Regional' },
  { symbol: '601398.SS', name: 'Industrial and Commercial Bank of China', exchange: 'SSE', region: 'China', currency: 'CNY', sector: 'Financials', industry: 'Banks—Diversified' },
  { symbol: '600028.SS', name: 'China Petroleum & Chemical (Sinopec)', exchange: 'SSE', region: 'China', currency: 'CNY', sector: 'Energy', industry: 'Oil & Gas Integrated' },
  { symbol: '005930.KS', name: 'Samsung Electronics Co., Ltd.', exchange: 'KRX', region: 'South Korea', currency: 'KRW', sector: 'Technology', industry: 'Semiconductors' },
  { symbol: '005380.KS', name: 'Hyundai Motor Company', exchange: 'KRX', region: 'South Korea', currency: 'KRW', sector: 'Consumer Discretionary', industry: 'Auto Manufacturers' },
  { symbol: '000660.KS', name: 'SK Hynix Inc.', exchange: 'KRX', region: 'South Korea', currency: 'KRW', sector: 'Technology', industry: 'Semiconductors' },
  { symbol: '2330.TW', name: 'Taiwan Semiconductor Manufacturing Co.', exchange: 'TWSE', region: 'Taiwan', currency: 'TWD', sector: 'Technology', industry: 'Semiconductors' },
  { symbol: '2454.TW', name: 'MediaTek Inc.', exchange: 'TWSE', region: 'Taiwan', currency: 'TWD', sector: 'Technology', industry: 'Semiconductors' },
  { symbol: '2317.TW', name: 'Hon Hai Precision Industry (Foxconn)', exchange: 'TWSE', region: 'Taiwan', currency: 'TWD', sector: 'Technology', industry: 'Electronic Components' },
  { symbol: 'BHP.AX', name: 'BHP Group Ltd.', exchange: 'ASX', region: 'Australia', currency: 'AUD', sector: 'Materials', industry: 'Other Industrial Metals' },
  { symbol: 'CBA.AX', name: 'Commonwealth Bank of Australia', exchange: 'ASX', region: 'Australia', currency: 'AUD', sector: 'Financials', industry: 'Banks—Regional' },
  { symbol: 'CSL.AX', name: 'CSL Limited', exchange: 'ASX', region: 'Australia', currency: 'AUD', sector: 'Healthcare', industry: 'Biotechnology' },
  { symbol: 'RIO.AX', name: 'Rio Tinto Limited', exchange: 'ASX', region: 'Australia', currency: 'AUD', sector: 'Materials', industry: 'Other Industrial Metals' },
  { symbol: 'NAB.AX', name: 'National Australia Bank Limited', exchange: 'ASX', region: 'Australia', currency: 'AUD', sector: 'Financials', industry: 'Banks—Regional' },
  { symbol: 'WBC.AX', name: 'Westpac Banking Corporation', exchange: 'ASX', region: 'Australia', currency: 'AUD', sector: 'Financials', industry: 'Banks—Regional' },
  { symbol: 'D05.SI', name: 'DBS Group Holdings Ltd.', exchange: 'SGX', region: 'Singapore', currency: 'SGD', sector: 'Financials', industry: 'Banks—Regional' },
  { symbol: 'U11.SI', name: 'United Overseas Bank Ltd.', exchange: 'SGX', region: 'Singapore', currency: 'SGD', sector: 'Financials', industry: 'Banks—Regional' },
  { symbol: 'C6L.SI', name: 'Singapore Airlines Limited', exchange: 'SGX', region: 'Singapore', currency: 'SGD', sector: 'Industrials', industry: 'Airlines' },
  { symbol: 'RY.TO', name: 'Royal Bank of Canada', exchange: 'TSX', region: 'Canada', currency: 'CAD', sector: 'Financials', industry: 'Banks—Diversified' },
  { symbol: 'SHOP.TO', name: 'Shopify Inc.', exchange: 'TSX', region: 'Canada', currency: 'CAD', sector: 'Technology', industry: 'Software' },
  { symbol: 'ENB.TO', name: 'Enbridge Inc.', exchange: 'TSX', region: 'Canada', currency: 'CAD', sector: 'Energy', industry: 'Oil & Gas Midstream' },
  { symbol: 'TD.TO', name: 'The Toronto-Dominion Bank', exchange: 'TSX', region: 'Canada', currency: 'CAD', sector: 'Financials', industry: 'Banks—Diversified' },
  { symbol: 'BNS.TO', name: 'The Bank of Nova Scotia', exchange: 'TSX', region: 'Canada', currency: 'CAD', sector: 'Financials', industry: 'Banks—Diversified' },
  { symbol: 'CNQ.TO', name: 'Canadian Natural Resources Limited', exchange: 'TSX', region: 'Canada', currency: 'CAD', sector: 'Energy', industry: 'Oil & Gas E&P' },
  { symbol: 'NVO', name: 'Novo Nordisk A/S', exchange: 'NYSE', region: 'Europe', currency: 'USD', sector: 'Healthcare', industry: 'Drug Manufacturers' },
  { symbol: 'SAP', name: 'SAP SE', exchange: 'NYSE', region: 'Europe', currency: 'USD', sector: 'Technology', industry: 'Software' },
  { symbol: 'TSM', name: 'Taiwan Semiconductor Manufacturing Co.', exchange: 'NYSE', region: 'Taiwan', currency: 'USD', sector: 'Technology', industry: 'Semiconductors' },

  // ===== Emerging markets (25) =====
  { symbol: 'PETR4.SA', name: 'Petróleo Brasileiro S.A. (Petrobras)', exchange: 'BVMF', region: 'Brazil', currency: 'BRL', sector: 'Energy', industry: 'Oil & Gas Integrated' },
  { symbol: 'VALE3.SA', name: 'Vale S.A.', exchange: 'BVMF', region: 'Brazil', currency: 'BRL', sector: 'Materials', industry: 'Other Industrial Metals' },
  { symbol: 'ITUB4.SA', name: 'Itaú Unibanco Holding S.A.', exchange: 'BVMF', region: 'Brazil', currency: 'BRL', sector: 'Financials', industry: 'Banks—Diversified' },
  { symbol: 'BBDC4.SA', name: 'Banco Bradesco S.A.', exchange: 'BVMF', region: 'Brazil', currency: 'BRL', sector: 'Financials', industry: 'Banks—Diversified' },
  { symbol: 'ABEV3.SA', name: 'Ambev S.A.', exchange: 'BVMF', region: 'Brazil', currency: 'BRL', sector: 'Consumer Staples', industry: 'Beverages' },
  { symbol: 'GEBR11.SA', name: 'Engie Brasil Energia S.A.', exchange: 'BVMF', region: 'Brazil', currency: 'BRL', sector: 'Utilities', industry: 'Utilities—Regulated' },
  { symbol: '2222.SR', name: 'Saudi Arabian Oil Co. (Aramco)', exchange: 'TADAWUL', region: 'Saudi Arabia', currency: 'SAR', sector: 'Energy', industry: 'Oil & Gas Integrated' },
  { symbol: '1180.SR', name: 'Al Rajhi Banking & Investment Corp.', exchange: 'TADAWUL', region: 'Saudi Arabia', currency: 'SAR', sector: 'Financials', industry: 'Banks—Diversified' },
  { symbol: '2010.SR', name: 'Saudi Basic Industries Corp. (SABIC)', exchange: 'TADAWUL', region: 'Saudi Arabia', currency: 'SAR', sector: 'Materials', industry: 'Chemicals' },
  { symbol: 'EMIRATES', name: 'Emirates NBD Bank PJSC', exchange: 'DFM', region: 'UAE', currency: 'AED', sector: 'Financials', industry: 'Banks—Regional' },
  { symbol: 'EMAAR', name: 'Emaar Properties PJSC', exchange: 'DFM', region: 'UAE', currency: 'AED', sector: 'Real Estate', industry: 'Real Estate—Development' },
  { symbol: 'GARAN', name: 'Garanti BBVA', exchange: 'BIST', region: 'Turkey', currency: 'TRY', sector: 'Financials', industry: 'Banks—Diversified' },
  { symbol: 'AKBNK', name: 'Akbank T.A.S.', exchange: 'BIST', region: 'Turkey', currency: 'TRY', sector: 'Financials', industry: 'Banks—Diversified' },
  { symbol: 'THYAO', name: 'Turkish Airlines', exchange: 'BIST', region: 'Turkey', currency: 'TRY', sector: 'Industrials', industry: 'Airlines' },
  { symbol: 'JSE.JO', name: 'JSE Limited', exchange: 'JSE', region: 'South Africa', currency: 'ZAR', sector: 'Financials', industry: 'Capital Markets' },
  { symbol: 'NPN.JO', name: 'Naspers Limited', exchange: 'JSE', region: 'South Africa', currency: 'ZAR', sector: 'Communication Services', industry: 'Internet Content' },
  { symbol: 'SOL.JO', name: 'Sasol Limited', exchange: 'JSE', region: 'South Africa', currency: 'ZAR', sector: 'Energy', industry: 'Oil & Gas Integrated' },
  { symbol: 'MTN.JO', name: 'MTN Group Limited', exchange: 'JSE', region: 'South Africa', currency: 'ZAR', sector: 'Communication Services', industry: 'Telecom' },
  { symbol: 'DANGCEM', name: 'Dangote Cement Plc', exchange: 'NSE.NG', region: 'Nigeria', currency: 'NGN', sector: 'Materials', industry: 'Building Materials' },
  { symbol: 'MTNN', name: 'MTN Nigeria Communications Plc', exchange: 'NSE.NG', region: 'Nigeria', currency: 'NGN', sector: 'Communication Services', industry: 'Telecom' },
  { symbol: 'GTCO', name: 'Guaranty Trust Holding Company Plc', exchange: 'NSE.NG', region: 'Nigeria', currency: 'NGN', sector: 'Financials', industry: 'Banks—Regional' },
  { symbol: 'ZENITHBANK', name: 'Zenith Bank Plc', exchange: 'NSE.NG', region: 'Nigeria', currency: 'NGN', sector: 'Financials', industry: 'Banks—Regional' },
  { symbol: 'OPAY', name: 'OPay (Opera Limited)', exchange: 'NYSE', region: 'Nigeria', currency: 'USD', sector: 'Financials', industry: 'Credit Services' },
  { symbol: 'STERB.NS', name: 'Sterling Bank Plc', exchange: 'NSE.NG', region: 'Nigeria', currency: 'NGN', sector: 'Financials', industry: 'Banks—Regional' },
  { symbol: 'ETI', name: 'Ecobank Transnational Incorporated', exchange: 'NSE.NG', region: 'Nigeria', currency: 'NGN', sector: 'Financials', industry: 'Banks—Diversified' },
];

import { GENERATED_UNIVERSE } from './universeGenerator';

const _seen = new Set(STOCK_UNIVERSE.map((s) => s.symbol));
for (const s of GENERATED_UNIVERSE) {
  if (!_seen.has(s.symbol)) {
    _seen.add(s.symbol);
    STOCK_UNIVERSE.push(s);
  }
}

export const REGIONS: Region[] = Array.from(new Set(STOCK_UNIVERSE.map((s) => s.region)));
export const SECTORS: Sector[] = Array.from(new Set(STOCK_UNIVERSE.map((s) => s.sector)));
export const EXCHANGES: Exchange[] = Array.from(new Set(STOCK_UNIVERSE.map((s) => s.exchange)));
